$axure.loadCurrentPage({
  "url":"查看标段.html",
  "generationDate":new Date(1430724550931.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4ee4f7bc92f04a11a1665d6b2cdfe4d5",
    "type":"Axure:Page",
    "name":"查看标段",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3581f3d3536f46c685bc0d0f15c0a187",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":56},
            "size":{
              "width":848,
              "height":274}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d773f18015d6426db47d9faa2abcd319",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b08eed3a2034238a2d2c83a5b193743",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"4b2da51f41864c428e221da4f92cc270",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6c36dc66a9464062a0e784198e1cfc6e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"203196fe545c4566a594ecd17988afff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9257f9589b1b4e9880788c3e4fbe730a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u33.png"}},
{
              "id":"3b57fc8b481949048971707f8fb8f5af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa0604999cfb47cf965a2ed46b036fbf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"83741f53bd194023b9ce0a35dea1724c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22166e3d98c24201860fc5019ded0b70",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"d9c88fcf8b624198aef897cf94d1c7fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f91d9da740d44e73bd68a2b9696e4b0a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u33.png"}},
{
              "id":"21d56f56af7f404fa59f8f57d3958b8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1220c8dfc4ca44d4803ea233286ff258",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"31b7813911c5460eb1f7164680f2bfb7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21df2a43cf0444cfb69fccbef4336971",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"088552f5a3a94389aa952f55d305b447",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":120,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d0f8bd0f6b0342da867c97a12a9182bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":60},
                    "size":{
                      "width":120,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u39.png"}},
{
              "id":"8f7d75bb3d6a4e2bb44ee030fe06a78e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":244},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"84b46af0dc224591ac5b6d2bdd445804",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":244},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u129.png"}},
{
              "id":"cc7343f854d143c095d4b85ee1d325e5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":244},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"adda2cc76c0a46bebe7e4e8449f737fc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":244},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u129.png"}},
{
              "id":"ab427c58882d4bf1ab11bcd195514b1a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":244},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18aa5d683ae54b768a439c57ccec09a1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":244},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u135.png"}},
{
              "id":"ec284a9d796742bd85275aae5c06c3de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":214},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f7c5459281e438088d306e920f80402",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":214},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"f22df09fc9aa4e31af7912476b019e32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":214},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a5439711c7b4570b5f48b070f184f3b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":214},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"33545bea77cf41e487c36f6dd62f19c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":214},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc4718fe232c418283215942eb4ff98b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":214},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"35cabd2b74124d0a8e68b4ce66dfdf8e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":184},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a397d9f865ff43b680f1391f660fb9d3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":184},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"da1cb1215f664ca28a1ebf9c3e30d8f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":184},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"93fe5171a99548c482fd3b7cfca6fa5d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":184},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"756354dd7ec84bef8e78b760f9723bc4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":184},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dae34303b4c347448e0203c515ddd758",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":184},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"23bb42fb56554461aefb7828d543f0c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":154},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ca10ba5761341d6bc3f43abfd58a56d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":154},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"c26ab43da8504f1f952dc95d7f8166a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":154},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3fd9ab53469f407980f640bfbb674171",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":154},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"e77cebbd9d9348f6b795865ecb1ddca6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":154},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"318cec7edcb742619513a4d2bffe587d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":154},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"a6e60a5fb79643beac0c6d54c2dd0ab9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":124},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6618f204d99b44aab5bc7d32a1836740",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":124},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"7ff6f64934dd41ec98c9903e0012b6a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":124},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d6e4eaf5cb13425191e15deddd6f0419",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":124},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"de2c4fad8d42429f96706a437dbe309c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":124},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3821405ec0084580964ee7b69e5b4f5c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":124},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"f6591879c48b408d90edd29d77ed1a70",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":88},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"be8e63cef9ec44c79d3f38598d4c81a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":88},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u49.png"}},
{
              "id":"4952396b58a748009caeef5d9d7d55ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":88},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de42919ff98b4148a237f97598ad8db4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":88},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u49.png"}},
{
              "id":"4e6abc5cb58c4bb783d7ff437088ee43",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":88},
                "size":{
                  "width":120,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1498b45b16cd49439fb740990eecb299",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":88},
                    "size":{
                      "width":120,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u55.png"}},
{
              "id":"df0d7b7dbfaf4a0b8b751ce685b92d83",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8db8342a2b14855a873c491d2434a29",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"f300c7c30c93434faefb472bf352fb54",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"101f1c12d4214509ab0d13362da3070e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"8af8b5738f0c4b3e87242d224eae747d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":60},
                "size":{
                  "width":120,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"730e88c777764c5b9b31fbcba6838241",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":60},
                    "size":{
                      "width":120,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u39.png"}},
{
              "id":"cf50d9dacc0d45fc93aa085c64ddc65a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":88},
                "size":{
                  "width":120,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a0c040cce3714ad39f436bf8eeca0eb1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":88},
                    "size":{
                      "width":120,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u55.png"}},
{
              "id":"30239e238a374d2aaac32384655f45d2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":124},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95eef67f98f74874935476a185d37b11",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":124},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"f395f7b0d3c1427b8d597608aecc05fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":154},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7360d628261d4f009a5e4619a7ae2e14",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":154},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"ffebf23664954e6d95a98e82da172600",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":184},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d751713bb234c4c8ef2f54003b0c109",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":184},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"f86be2341d034e579fff69176e2fdd53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":214},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c9a5d8a0cecd4c189e3459c9b2c2f603",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":214},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u7.png"}},
{
              "id":"bb8aba683bc948089433c2e6281eee00",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":244},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e62d504d02849b78b2cfecc1872630c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":244},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u135.png"}},
{
              "id":"af4fba5ff4fa4dfeabef4326c16df4fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":640,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d34e685bcfb244fa9d246b62a4c63a50",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":640,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"29af9690899346bd92deb41aac8b9e45",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":640,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b76218073cb4c00bc31d586fd05a2af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":640,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"71b5fd23b6074128afeda5fb38b7a8d2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":640,
                  "y":60},
                "size":{
                  "width":100,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cb59fa0050a54ded996c26e45eedafba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":640,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u33.png"}},
{
              "id":"99034d57ebce4655aa424b2a1e385cfe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":640,
                  "y":88},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ff401826ad843bf8c2e523c428b400b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":640,
                      "y":88},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u49.png"}},
{
              "id":"782b0ba00c594bcd8444756966e95d8e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":640,
                  "y":124},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd72b3525a41447eab468ba3b3d9d1b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":640,
                      "y":124},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"e42b0dfd9201492ab1a7fc3c7923aa7d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":640,
                  "y":154},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f8efbfbf92b48029332dc3832d30489",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":640,
                      "y":154},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"3b07d48a46164a38b06bccf462db799a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":640,
                  "y":184},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f9cace94f5e24c20bf070efc422bfdb1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":640,
                      "y":184},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"c864f6a9670c40ef969743a2295b1301",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":640,
                  "y":214},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3a3b541704d4d9187d58e53f2eb18d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":640,
                      "y":214},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u1.png"}},
{
              "id":"a5c0cbd5ede34ecb8a22ecdf6302dba7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":640,
                  "y":244},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4e90189222d47e29a0b1b12a0795f72",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":640,
                      "y":244},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目基本信息管理/u129.png"}},
{
              "id":"2c405fc2d1ab497dbd48aadd03ae24f8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9915638a599d455693aafaeae2bed9e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u3.png"}},
{
              "id":"89f863cfc7ef4e0bb5a8f1d0043f19ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8dc6f9715e1c49d19102719d005714ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u3.png"}},
{
              "id":"beb513e118fe493e9a1ec805df67483b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":200,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90c87d74020c4502bc0d2f2856df4c1e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":200,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u31.png"}},
{
              "id":"c68ea761000645d6b35a9320eda39e80",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":88},
                "size":{
                  "width":200,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a57d03aa14a24812a07a3dade2ff1407",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":88},
                    "size":{
                      "width":200,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u45.png"}},
{
              "id":"0a469c0e224141cfb96b1675b459565b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":124},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"afdc98781f7d42778890269f580988a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":124},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u3.png"}},
{
              "id":"292ca14fd64b463cb611328edef5dbcf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":154},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c144ca09c98d42f7aacafbd62a27ce64",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":154},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u3.png"}},
{
              "id":"012af333102c4f7db0f77eaa9699f0e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":184},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55eaf4b8cfe040a7ab59ef59d51f5276",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":184},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u3.png"}},
{
              "id":"74831f8f0471440f80cf650df35021aa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":214},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9e42a06ad9d94cc3b532127d356eee8a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":214},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u3.png"}},
{
              "id":"a71f7f37d05742ff96d9e63c1a75e68b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":244},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c443eefa29a945db8cc918c325eccdc0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":244},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u115.png"}},
{
              "id":"129a1573b87b43ab8c4d0c805ea3e0dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":0},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5bde3e91932a4712bc685adc770c4cfb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":740,
                      "y":0},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u13.png"}},
{
              "id":"1e0ffd452fe44e938a325eefcad3ed9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":30},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"35ce64b0e692478c9eb557ad6066f00d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":740,
                      "y":30},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u13.png"}},
{
              "id":"13940bb946cb48a3a4c51dc2f0a92df2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":60},
                "size":{
                  "width":108,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2d310d2a1f2947a3951a0428219861d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":740,
                      "y":60},
                    "size":{
                      "width":108,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u41.png"}},
{
              "id":"e61686bdb5ad4d63b2611c1a0fa16c26",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":88},
                "size":{
                  "width":108,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61e805e3b0334d08b99f271ae60c2810",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":740,
                      "y":88},
                    "size":{
                      "width":108,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u55.png"}},
{
              "id":"563f5df957aa47d6bdc9b350ff3a439e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":124},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"76f16ecc173a400ba65cee660ea37e11",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":740,
                      "y":124},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u13.png"}},
{
              "id":"705ff36f5ec94927b0d9893c26b38b9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":154},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a96222e9e88416b8a59a481f4d20de6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":740,
                      "y":154},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u13.png"}},
{
              "id":"14360fe65c7f4e51a874506a13e0f7d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":184},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e637491c7bb8426382d147dbc05ee094",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":740,
                      "y":184},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u13.png"}},
{
              "id":"4e2d10149238401797537a54b4671995",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":214},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5418732a5b545bc80db150c68aaa298",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":740,
                      "y":214},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u13.png"}},
{
              "id":"328ec51cce2e4c00949ade4778b748e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":244},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61d44f2bef4a4bb2974030427c2b6ebe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":740,
                      "y":244},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看标段/u125.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "3581f3d3536f46c685bc0d0f15c0a187":{
      "scriptId":"u0"},
    "d773f18015d6426db47d9faa2abcd319":{
      "scriptId":"u1"},
    "0b08eed3a2034238a2d2c83a5b193743":{
      "scriptId":"u2"},
    "2c405fc2d1ab497dbd48aadd03ae24f8":{
      "scriptId":"u3"},
    "9915638a599d455693aafaeae2bed9e4":{
      "scriptId":"u4"},
    "3b57fc8b481949048971707f8fb8f5af":{
      "scriptId":"u5"},
    "aa0604999cfb47cf965a2ed46b036fbf":{
      "scriptId":"u6"},
    "21d56f56af7f404fa59f8f57d3958b8a":{
      "scriptId":"u7"},
    "1220c8dfc4ca44d4803ea233286ff258":{
      "scriptId":"u8"},
    "df0d7b7dbfaf4a0b8b751ce685b92d83":{
      "scriptId":"u9"},
    "d8db8342a2b14855a873c491d2434a29":{
      "scriptId":"u10"},
    "af4fba5ff4fa4dfeabef4326c16df4fd":{
      "scriptId":"u11"},
    "d34e685bcfb244fa9d246b62a4c63a50":{
      "scriptId":"u12"},
    "129a1573b87b43ab8c4d0c805ea3e0dc":{
      "scriptId":"u13"},
    "5bde3e91932a4712bc685adc770c4cfb":{
      "scriptId":"u14"},
    "4b2da51f41864c428e221da4f92cc270":{
      "scriptId":"u15"},
    "6c36dc66a9464062a0e784198e1cfc6e":{
      "scriptId":"u16"},
    "89f863cfc7ef4e0bb5a8f1d0043f19ea":{
      "scriptId":"u17"},
    "8dc6f9715e1c49d19102719d005714ed":{
      "scriptId":"u18"},
    "83741f53bd194023b9ce0a35dea1724c":{
      "scriptId":"u19"},
    "22166e3d98c24201860fc5019ded0b70":{
      "scriptId":"u20"},
    "31b7813911c5460eb1f7164680f2bfb7":{
      "scriptId":"u21"},
    "21df2a43cf0444cfb69fccbef4336971":{
      "scriptId":"u22"},
    "f300c7c30c93434faefb472bf352fb54":{
      "scriptId":"u23"},
    "101f1c12d4214509ab0d13362da3070e":{
      "scriptId":"u24"},
    "29af9690899346bd92deb41aac8b9e45":{
      "scriptId":"u25"},
    "0b76218073cb4c00bc31d586fd05a2af":{
      "scriptId":"u26"},
    "1e0ffd452fe44e938a325eefcad3ed9b":{
      "scriptId":"u27"},
    "35ce64b0e692478c9eb557ad6066f00d":{
      "scriptId":"u28"},
    "203196fe545c4566a594ecd17988afff":{
      "scriptId":"u29"},
    "9257f9589b1b4e9880788c3e4fbe730a":{
      "scriptId":"u30"},
    "beb513e118fe493e9a1ec805df67483b":{
      "scriptId":"u31"},
    "90c87d74020c4502bc0d2f2856df4c1e":{
      "scriptId":"u32"},
    "d9c88fcf8b624198aef897cf94d1c7fd":{
      "scriptId":"u33"},
    "f91d9da740d44e73bd68a2b9696e4b0a":{
      "scriptId":"u34"},
    "088552f5a3a94389aa952f55d305b447":{
      "scriptId":"u35"},
    "d0f8bd0f6b0342da867c97a12a9182bd":{
      "scriptId":"u36"},
    "8af8b5738f0c4b3e87242d224eae747d":{
      "scriptId":"u37"},
    "730e88c777764c5b9b31fbcba6838241":{
      "scriptId":"u38"},
    "71b5fd23b6074128afeda5fb38b7a8d2":{
      "scriptId":"u39"},
    "cb59fa0050a54ded996c26e45eedafba":{
      "scriptId":"u40"},
    "13940bb946cb48a3a4c51dc2f0a92df2":{
      "scriptId":"u41"},
    "2d310d2a1f2947a3951a0428219861d0":{
      "scriptId":"u42"},
    "f6591879c48b408d90edd29d77ed1a70":{
      "scriptId":"u43"},
    "be8e63cef9ec44c79d3f38598d4c81a3":{
      "scriptId":"u44"},
    "c68ea761000645d6b35a9320eda39e80":{
      "scriptId":"u45"},
    "a57d03aa14a24812a07a3dade2ff1407":{
      "scriptId":"u46"},
    "4952396b58a748009caeef5d9d7d55ee":{
      "scriptId":"u47"},
    "de42919ff98b4148a237f97598ad8db4":{
      "scriptId":"u48"},
    "4e6abc5cb58c4bb783d7ff437088ee43":{
      "scriptId":"u49"},
    "1498b45b16cd49439fb740990eecb299":{
      "scriptId":"u50"},
    "cf50d9dacc0d45fc93aa085c64ddc65a":{
      "scriptId":"u51"},
    "a0c040cce3714ad39f436bf8eeca0eb1":{
      "scriptId":"u52"},
    "99034d57ebce4655aa424b2a1e385cfe":{
      "scriptId":"u53"},
    "6ff401826ad843bf8c2e523c428b400b":{
      "scriptId":"u54"},
    "e61686bdb5ad4d63b2611c1a0fa16c26":{
      "scriptId":"u55"},
    "61e805e3b0334d08b99f271ae60c2810":{
      "scriptId":"u56"},
    "a6e60a5fb79643beac0c6d54c2dd0ab9":{
      "scriptId":"u57"},
    "6618f204d99b44aab5bc7d32a1836740":{
      "scriptId":"u58"},
    "0a469c0e224141cfb96b1675b459565b":{
      "scriptId":"u59"},
    "afdc98781f7d42778890269f580988a5":{
      "scriptId":"u60"},
    "7ff6f64934dd41ec98c9903e0012b6a9":{
      "scriptId":"u61"},
    "d6e4eaf5cb13425191e15deddd6f0419":{
      "scriptId":"u62"},
    "de2c4fad8d42429f96706a437dbe309c":{
      "scriptId":"u63"},
    "3821405ec0084580964ee7b69e5b4f5c":{
      "scriptId":"u64"},
    "30239e238a374d2aaac32384655f45d2":{
      "scriptId":"u65"},
    "95eef67f98f74874935476a185d37b11":{
      "scriptId":"u66"},
    "782b0ba00c594bcd8444756966e95d8e":{
      "scriptId":"u67"},
    "bd72b3525a41447eab468ba3b3d9d1b5":{
      "scriptId":"u68"},
    "563f5df957aa47d6bdc9b350ff3a439e":{
      "scriptId":"u69"},
    "76f16ecc173a400ba65cee660ea37e11":{
      "scriptId":"u70"},
    "23bb42fb56554461aefb7828d543f0c1":{
      "scriptId":"u71"},
    "9ca10ba5761341d6bc3f43abfd58a56d":{
      "scriptId":"u72"},
    "292ca14fd64b463cb611328edef5dbcf":{
      "scriptId":"u73"},
    "c144ca09c98d42f7aacafbd62a27ce64":{
      "scriptId":"u74"},
    "c26ab43da8504f1f952dc95d7f8166a8":{
      "scriptId":"u75"},
    "3fd9ab53469f407980f640bfbb674171":{
      "scriptId":"u76"},
    "e77cebbd9d9348f6b795865ecb1ddca6":{
      "scriptId":"u77"},
    "318cec7edcb742619513a4d2bffe587d":{
      "scriptId":"u78"},
    "f395f7b0d3c1427b8d597608aecc05fd":{
      "scriptId":"u79"},
    "7360d628261d4f009a5e4619a7ae2e14":{
      "scriptId":"u80"},
    "e42b0dfd9201492ab1a7fc3c7923aa7d":{
      "scriptId":"u81"},
    "1f8efbfbf92b48029332dc3832d30489":{
      "scriptId":"u82"},
    "705ff36f5ec94927b0d9893c26b38b9b":{
      "scriptId":"u83"},
    "4a96222e9e88416b8a59a481f4d20de6":{
      "scriptId":"u84"},
    "35cabd2b74124d0a8e68b4ce66dfdf8e":{
      "scriptId":"u85"},
    "a397d9f865ff43b680f1391f660fb9d3":{
      "scriptId":"u86"},
    "012af333102c4f7db0f77eaa9699f0e1":{
      "scriptId":"u87"},
    "55eaf4b8cfe040a7ab59ef59d51f5276":{
      "scriptId":"u88"},
    "da1cb1215f664ca28a1ebf9c3e30d8f0":{
      "scriptId":"u89"},
    "93fe5171a99548c482fd3b7cfca6fa5d":{
      "scriptId":"u90"},
    "756354dd7ec84bef8e78b760f9723bc4":{
      "scriptId":"u91"},
    "dae34303b4c347448e0203c515ddd758":{
      "scriptId":"u92"},
    "ffebf23664954e6d95a98e82da172600":{
      "scriptId":"u93"},
    "9d751713bb234c4c8ef2f54003b0c109":{
      "scriptId":"u94"},
    "3b07d48a46164a38b06bccf462db799a":{
      "scriptId":"u95"},
    "f9cace94f5e24c20bf070efc422bfdb1":{
      "scriptId":"u96"},
    "14360fe65c7f4e51a874506a13e0f7d8":{
      "scriptId":"u97"},
    "e637491c7bb8426382d147dbc05ee094":{
      "scriptId":"u98"},
    "ec284a9d796742bd85275aae5c06c3de":{
      "scriptId":"u99"},
    "9f7c5459281e438088d306e920f80402":{
      "scriptId":"u100"},
    "74831f8f0471440f80cf650df35021aa":{
      "scriptId":"u101"},
    "9e42a06ad9d94cc3b532127d356eee8a":{
      "scriptId":"u102"},
    "f22df09fc9aa4e31af7912476b019e32":{
      "scriptId":"u103"},
    "3a5439711c7b4570b5f48b070f184f3b":{
      "scriptId":"u104"},
    "33545bea77cf41e487c36f6dd62f19c7":{
      "scriptId":"u105"},
    "bc4718fe232c418283215942eb4ff98b":{
      "scriptId":"u106"},
    "f86be2341d034e579fff69176e2fdd53":{
      "scriptId":"u107"},
    "c9a5d8a0cecd4c189e3459c9b2c2f603":{
      "scriptId":"u108"},
    "c864f6a9670c40ef969743a2295b1301":{
      "scriptId":"u109"},
    "e3a3b541704d4d9187d58e53f2eb18d6":{
      "scriptId":"u110"},
    "4e2d10149238401797537a54b4671995":{
      "scriptId":"u111"},
    "a5418732a5b545bc80db150c68aaa298":{
      "scriptId":"u112"},
    "8f7d75bb3d6a4e2bb44ee030fe06a78e":{
      "scriptId":"u113"},
    "84b46af0dc224591ac5b6d2bdd445804":{
      "scriptId":"u114"},
    "a71f7f37d05742ff96d9e63c1a75e68b":{
      "scriptId":"u115"},
    "c443eefa29a945db8cc918c325eccdc0":{
      "scriptId":"u116"},
    "cc7343f854d143c095d4b85ee1d325e5":{
      "scriptId":"u117"},
    "adda2cc76c0a46bebe7e4e8449f737fc":{
      "scriptId":"u118"},
    "ab427c58882d4bf1ab11bcd195514b1a":{
      "scriptId":"u119"},
    "18aa5d683ae54b768a439c57ccec09a1":{
      "scriptId":"u120"},
    "bb8aba683bc948089433c2e6281eee00":{
      "scriptId":"u121"},
    "1e62d504d02849b78b2cfecc1872630c":{
      "scriptId":"u122"},
    "a5c0cbd5ede34ecb8a22ecdf6302dba7":{
      "scriptId":"u123"},
    "b4e90189222d47e29a0b1b12a0795f72":{
      "scriptId":"u124"},
    "328ec51cce2e4c00949ade4778b748e6":{
      "scriptId":"u125"},
    "61d44f2bef4a4bb2974030427c2b6ebe":{
      "scriptId":"u126"}}});