/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.cyzt.leo.service.base;

import com.justonetech.cyzt.leo.model.LEOTraining;
import com.justonetech.cyzt.leo.service.LEOTrainingLocalService;
import com.justonetech.cyzt.leo.service.persistence.LEOCertificatePersistence;
import com.justonetech.cyzt.leo.service.persistence.LEOTrainingPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the l e o training local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.justonetech.cyzt.leo.service.impl.LEOTrainingLocalServiceImpl}.
 * </p>
 *
 * @author fanqi
 * @see com.justonetech.cyzt.leo.service.impl.LEOTrainingLocalServiceImpl
 * @see com.justonetech.cyzt.leo.service.LEOTrainingLocalServiceUtil
 * @generated
 */
public abstract class LEOTrainingLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements LEOTrainingLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.justonetech.cyzt.leo.service.LEOTrainingLocalServiceUtil} to access the l e o training local service.
	 */

	/**
	 * Adds the l e o training to the database. Also notifies the appropriate model listeners.
	 *
	 * @param leoTraining the l e o training
	 * @return the l e o training that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LEOTraining addLEOTraining(LEOTraining leoTraining)
		throws SystemException {
		leoTraining.setNew(true);

		return leoTrainingPersistence.update(leoTraining);
	}

	/**
	 * Creates a new l e o training with the primary key. Does not add the l e o training to the database.
	 *
	 * @param trainingId the primary key for the new l e o training
	 * @return the new l e o training
	 */
	@Override
	public LEOTraining createLEOTraining(long trainingId) {
		return leoTrainingPersistence.create(trainingId);
	}

	/**
	 * Deletes the l e o training with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param trainingId the primary key of the l e o training
	 * @return the l e o training that was removed
	 * @throws PortalException if a l e o training with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LEOTraining deleteLEOTraining(long trainingId)
		throws PortalException, SystemException {
		return leoTrainingPersistence.remove(trainingId);
	}

	/**
	 * Deletes the l e o training from the database. Also notifies the appropriate model listeners.
	 *
	 * @param leoTraining the l e o training
	 * @return the l e o training that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LEOTraining deleteLEOTraining(LEOTraining leoTraining)
		throws SystemException {
		return leoTrainingPersistence.remove(leoTraining);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(LEOTraining.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return leoTrainingPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.justonetech.cyzt.leo.model.impl.LEOTrainingModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return leoTrainingPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.justonetech.cyzt.leo.model.impl.LEOTrainingModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return leoTrainingPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return leoTrainingPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return leoTrainingPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public LEOTraining fetchLEOTraining(long trainingId)
		throws SystemException {
		return leoTrainingPersistence.fetchByPrimaryKey(trainingId);
	}

	/**
	 * Returns the l e o training with the primary key.
	 *
	 * @param trainingId the primary key of the l e o training
	 * @return the l e o training
	 * @throws PortalException if a l e o training with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public LEOTraining getLEOTraining(long trainingId)
		throws PortalException, SystemException {
		return leoTrainingPersistence.findByPrimaryKey(trainingId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return leoTrainingPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the l e o trainings.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.justonetech.cyzt.leo.model.impl.LEOTrainingModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of l e o trainings
	 * @param end the upper bound of the range of l e o trainings (not inclusive)
	 * @return the range of l e o trainings
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<LEOTraining> getLEOTrainings(int start, int end)
		throws SystemException {
		return leoTrainingPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of l e o trainings.
	 *
	 * @return the number of l e o trainings
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getLEOTrainingsCount() throws SystemException {
		return leoTrainingPersistence.countAll();
	}

	/**
	 * Updates the l e o training in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param leoTraining the l e o training
	 * @return the l e o training that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LEOTraining updateLEOTraining(LEOTraining leoTraining)
		throws SystemException {
		return leoTrainingPersistence.update(leoTraining);
	}

	/**
	 * Returns the l e o certificate local service.
	 *
	 * @return the l e o certificate local service
	 */
	public com.justonetech.cyzt.leo.service.LEOCertificateLocalService getLEOCertificateLocalService() {
		return leoCertificateLocalService;
	}

	/**
	 * Sets the l e o certificate local service.
	 *
	 * @param leoCertificateLocalService the l e o certificate local service
	 */
	public void setLEOCertificateLocalService(
		com.justonetech.cyzt.leo.service.LEOCertificateLocalService leoCertificateLocalService) {
		this.leoCertificateLocalService = leoCertificateLocalService;
	}

	/**
	 * Returns the l e o certificate persistence.
	 *
	 * @return the l e o certificate persistence
	 */
	public LEOCertificatePersistence getLEOCertificatePersistence() {
		return leoCertificatePersistence;
	}

	/**
	 * Sets the l e o certificate persistence.
	 *
	 * @param leoCertificatePersistence the l e o certificate persistence
	 */
	public void setLEOCertificatePersistence(
		LEOCertificatePersistence leoCertificatePersistence) {
		this.leoCertificatePersistence = leoCertificatePersistence;
	}

	/**
	 * Returns the l e o training local service.
	 *
	 * @return the l e o training local service
	 */
	public com.justonetech.cyzt.leo.service.LEOTrainingLocalService getLEOTrainingLocalService() {
		return leoTrainingLocalService;
	}

	/**
	 * Sets the l e o training local service.
	 *
	 * @param leoTrainingLocalService the l e o training local service
	 */
	public void setLEOTrainingLocalService(
		com.justonetech.cyzt.leo.service.LEOTrainingLocalService leoTrainingLocalService) {
		this.leoTrainingLocalService = leoTrainingLocalService;
	}

	/**
	 * Returns the l e o training persistence.
	 *
	 * @return the l e o training persistence
	 */
	public LEOTrainingPersistence getLEOTrainingPersistence() {
		return leoTrainingPersistence;
	}

	/**
	 * Sets the l e o training persistence.
	 *
	 * @param leoTrainingPersistence the l e o training persistence
	 */
	public void setLEOTrainingPersistence(
		LEOTrainingPersistence leoTrainingPersistence) {
		this.leoTrainingPersistence = leoTrainingPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.justonetech.cyzt.leo.model.LEOTraining",
			leoTrainingLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.justonetech.cyzt.leo.model.LEOTraining");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return LEOTraining.class;
	}

	protected String getModelClassName() {
		return LEOTraining.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = leoTrainingPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.justonetech.cyzt.leo.service.LEOCertificateLocalService.class)
	protected com.justonetech.cyzt.leo.service.LEOCertificateLocalService leoCertificateLocalService;
	@BeanReference(type = LEOCertificatePersistence.class)
	protected LEOCertificatePersistence leoCertificatePersistence;
	@BeanReference(type = com.justonetech.cyzt.leo.service.LEOTrainingLocalService.class)
	protected com.justonetech.cyzt.leo.service.LEOTrainingLocalService leoTrainingLocalService;
	@BeanReference(type = LEOTrainingPersistence.class)
	protected LEOTrainingPersistence leoTrainingPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private LEOTrainingLocalServiceClpInvoker _clpInvoker = new LEOTrainingLocalServiceClpInvoker();
}