$axure.loadCurrentPage({
  "url":"办公用品库.html",
  "generationDate":new Date(1434534636675.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b9bfee60ca464c13816ad08cb630be33",
    "type":"Axure:Page",
    "name":"办公用品库",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f66694f352847fab4709fae3ba8a655",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":50},
            "size":{
              "width":938,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"297e7b093336415cae6c6c766073a4bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "size":{
                  "width":327,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"926957caaea046a58467f9dc7fb228c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "size":{
                      "width":327,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u1.png"}},
{
              "id":"bcdf8242b2f646e5815ef3b17c8ad0a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":35},
                "size":{
                  "width":327,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"865d64af3fde43d7b5bea88aad18a19e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":35},
                    "size":{
                      "width":327,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u11.png"}},
{
              "id":"214f2426e3f646ba8a63a6c9978b182c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":65},
                "size":{
                  "width":327,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d4f1d399bb894b69bddecabf852b34bb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":65},
                    "size":{
                      "width":327,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u11.png"}},
{
              "id":"68f936415db0437f878d0ae3f6be1873",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":611,
                  "y":0},
                "size":{
                  "width":172,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4517b5c5f7cf4bdcac1825f2a048df4d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":611,
                      "y":0},
                    "size":{
                      "width":172,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u7.png"}},
{
              "id":"d824363469624e85bc24e7a947de5958",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":611,
                  "y":35},
                "size":{
                  "width":172,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"60a65000c88d42c1b3e3227a8725b5ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":611,
                      "y":35},
                    "size":{
                      "width":172,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u17.png"}},
{
              "id":"52fae6b5683a4ec58a96456c2531799b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":611,
                  "y":65},
                "size":{
                  "width":172,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"688c622c79ab411dacebeaaaa057c5ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":611,
                      "y":65},
                    "size":{
                      "width":172,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u17.png"}},
{
              "id":"2e262edadd464add9f3f887189d8a742",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":783,
                  "y":0},
                "size":{
                  "width":155,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"924282493e6f402ba7ff17ed7c83a8c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":783,
                      "y":0},
                    "size":{
                      "width":155,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u9.png"}},
{
              "id":"ed8e87462c1243e5bbbb2f88158d25ec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":35},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ea3689e10bf477296d5699e8c0afb85",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":783,
                      "y":35},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u19.png"}},
{
              "id":"be3e13d466294cc28a1ad63077202e7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":65},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"52b3f43ed2e841e5bc823a79756093c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":783,
                      "y":65},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u19.png"}},
{
              "id":"cf99005ebaf7470d865c683fbe365cad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":327,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56a8dfcf86cf4717a9c2840c0b1eb559",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":95},
                    "size":{
                      "width":327,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u11.png"}},
{
              "id":"5eea6b0ffdd942d6a23318b3c99a081e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":611,
                  "y":95},
                "size":{
                  "width":172,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8a006072edb4b2687b566809bec9fea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":611,
                      "y":95},
                    "size":{
                      "width":172,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u17.png"}},
{
              "id":"2d8d5d34902d4c8b81ae6466da74e4e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":95},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b959a8b5d1d6434fa87b7495d2eb3f82",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":783,
                      "y":95},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u19.png"}},
{
              "id":"dfd7c8e588d644c8ac1ffb88dba53a85",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":125},
                "size":{
                  "width":327,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4acd4526f34d4a7093cdd0e516c8a135",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":327,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u41.png"}},
{
              "id":"d1478293bc0a4477837f31871924c76f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":611,
                  "y":125},
                "size":{
                  "width":172,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0861d56e4afd4d8699200777e53e4edb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":611,
                      "y":125},
                    "size":{
                      "width":172,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u47.png"}},
{
              "id":"616e3e6649be4e24877f90186e9a9506",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":125},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41a53916f5d64096983b57a77ad83535",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":783,
                      "y":125},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u49.png"}},
{
              "id":"8e8dd0fe870d49f4851588a24f5b2c8e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":327,
                  "y":0},
                "size":{
                  "width":149,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f0e14db2069413abf773d8dc1a73461",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":327,
                      "y":0},
                    "size":{
                      "width":149,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u3.png"}},
{
              "id":"69062338adb947569e125f6e75401caa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":327,
                  "y":35},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6c174011022b4ce39de239670a27255c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":327,
                      "y":35},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u13.png"}},
{
              "id":"9bdf4f25d4524d96a3ebb5cc7b5107d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":327,
                  "y":65},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f775255ea7348d08e05819b84480ef8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":327,
                      "y":65},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u13.png"}},
{
              "id":"a70ef98c34e34ae2af862d7027cdccd5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":327,
                  "y":95},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5ac5f3d899ea4c7795ac24deff81d4f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":327,
                      "y":95},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u13.png"}},
{
              "id":"13ef2971862c4274ac4f42d867c337b3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":327,
                  "y":125},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de073256619b4b64a4688f8a9caa5fb1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":327,
                      "y":125},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u43.png"}},
{
              "id":"4b70f5ba65de4eaca2612854a10efd47",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":476,
                  "y":0},
                "size":{
                  "width":135,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a04f758a36444468451add0fa9b418c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":476,
                      "y":0},
                    "size":{
                      "width":135,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u5.png"}},
{
              "id":"7cb0f36326694159bb382a921a38a0a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":35},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4f30afab9b4443ebfe572460628a96a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":35},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u23.png"}},
{
              "id":"b687f48135b14292ba37f82e15e638a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":65},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2fdb62fd477a4fcdbe48608a82bf6975",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":65},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u23.png"}},
{
              "id":"5f174d0a830e452ea42cb55cef786cba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":95},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e32ce1156ae8440ba1df0dc2a6959e2b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":95},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u23.png"}},
{
              "id":"8ffe8a312be147d395c7c736cd5b39a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":125},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67ea1fc2c5d4407989c301061cf8dd0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":125},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u103.png"}}]},
{
          "id":"a93e4b55631c4feea8ba01735956c4ea",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":15},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "8f66694f352847fab4709fae3ba8a655":{
      "scriptId":"u0"},
    "297e7b093336415cae6c6c766073a4bc":{
      "scriptId":"u1"},
    "926957caaea046a58467f9dc7fb228c4":{
      "scriptId":"u2"},
    "8e8dd0fe870d49f4851588a24f5b2c8e":{
      "scriptId":"u3"},
    "7f0e14db2069413abf773d8dc1a73461":{
      "scriptId":"u4"},
    "4b70f5ba65de4eaca2612854a10efd47":{
      "scriptId":"u5"},
    "2a04f758a36444468451add0fa9b418c":{
      "scriptId":"u6"},
    "68f936415db0437f878d0ae3f6be1873":{
      "scriptId":"u7"},
    "4517b5c5f7cf4bdcac1825f2a048df4d":{
      "scriptId":"u8"},
    "2e262edadd464add9f3f887189d8a742":{
      "scriptId":"u9"},
    "924282493e6f402ba7ff17ed7c83a8c0":{
      "scriptId":"u10"},
    "bcdf8242b2f646e5815ef3b17c8ad0a9":{
      "scriptId":"u11"},
    "865d64af3fde43d7b5bea88aad18a19e":{
      "scriptId":"u12"},
    "69062338adb947569e125f6e75401caa":{
      "scriptId":"u13"},
    "6c174011022b4ce39de239670a27255c":{
      "scriptId":"u14"},
    "7cb0f36326694159bb382a921a38a0a6":{
      "scriptId":"u15"},
    "b4f30afab9b4443ebfe572460628a96a":{
      "scriptId":"u16"},
    "d824363469624e85bc24e7a947de5958":{
      "scriptId":"u17"},
    "60a65000c88d42c1b3e3227a8725b5ba":{
      "scriptId":"u18"},
    "ed8e87462c1243e5bbbb2f88158d25ec":{
      "scriptId":"u19"},
    "6ea3689e10bf477296d5699e8c0afb85":{
      "scriptId":"u20"},
    "214f2426e3f646ba8a63a6c9978b182c":{
      "scriptId":"u21"},
    "d4f1d399bb894b69bddecabf852b34bb":{
      "scriptId":"u22"},
    "9bdf4f25d4524d96a3ebb5cc7b5107d8":{
      "scriptId":"u23"},
    "3f775255ea7348d08e05819b84480ef8":{
      "scriptId":"u24"},
    "b687f48135b14292ba37f82e15e638a7":{
      "scriptId":"u25"},
    "2fdb62fd477a4fcdbe48608a82bf6975":{
      "scriptId":"u26"},
    "52fae6b5683a4ec58a96456c2531799b":{
      "scriptId":"u27"},
    "688c622c79ab411dacebeaaaa057c5ca":{
      "scriptId":"u28"},
    "be3e13d466294cc28a1ad63077202e7e":{
      "scriptId":"u29"},
    "52b3f43ed2e841e5bc823a79756093c8":{
      "scriptId":"u30"},
    "cf99005ebaf7470d865c683fbe365cad":{
      "scriptId":"u31"},
    "56a8dfcf86cf4717a9c2840c0b1eb559":{
      "scriptId":"u32"},
    "a70ef98c34e34ae2af862d7027cdccd5":{
      "scriptId":"u33"},
    "5ac5f3d899ea4c7795ac24deff81d4f6":{
      "scriptId":"u34"},
    "5f174d0a830e452ea42cb55cef786cba":{
      "scriptId":"u35"},
    "e32ce1156ae8440ba1df0dc2a6959e2b":{
      "scriptId":"u36"},
    "5eea6b0ffdd942d6a23318b3c99a081e":{
      "scriptId":"u37"},
    "f8a006072edb4b2687b566809bec9fea":{
      "scriptId":"u38"},
    "2d8d5d34902d4c8b81ae6466da74e4e3":{
      "scriptId":"u39"},
    "b959a8b5d1d6434fa87b7495d2eb3f82":{
      "scriptId":"u40"},
    "dfd7c8e588d644c8ac1ffb88dba53a85":{
      "scriptId":"u41"},
    "4acd4526f34d4a7093cdd0e516c8a135":{
      "scriptId":"u42"},
    "13ef2971862c4274ac4f42d867c337b3":{
      "scriptId":"u43"},
    "de073256619b4b64a4688f8a9caa5fb1":{
      "scriptId":"u44"},
    "8ffe8a312be147d395c7c736cd5b39a7":{
      "scriptId":"u45"},
    "67ea1fc2c5d4407989c301061cf8dd0d":{
      "scriptId":"u46"},
    "d1478293bc0a4477837f31871924c76f":{
      "scriptId":"u47"},
    "0861d56e4afd4d8699200777e53e4edb":{
      "scriptId":"u48"},
    "616e3e6649be4e24877f90186e9a9506":{
      "scriptId":"u49"},
    "41a53916f5d64096983b57a77ad83535":{
      "scriptId":"u50"},
    "a93e4b55631c4feea8ba01735956c4ea":{
      "scriptId":"u51"}}});