$axure.loadCurrentPage({
  "url":"办公用品管理.html",
  "generationDate":new Date(1434534636599.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"66dd6e2c8ffb4065994b24a888266ba9",
    "type":"Axure:Page",
    "name":"办公用品管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8377377c6b334fcd9885511fa6bba06b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":100},
            "size":{
              "width":590,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2347383836e4465e8a9944a92d089164",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"caaceb8e7aff42f4b264534a9b76e7af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u1.png"}},
{
              "id":"1a60ab59591c4746922beb2f0a31bcb1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f88028cca6a540d6aa6a64d251a85dc6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"114a5db27323462cb1b5fc22129ad18d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8bbf72dbda3d4db9b851f3efeefc925d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"1d3c2831ebdf48a88981042f72f802c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8d0c99d8f574a808987cc844820ce00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u1.png"}},
{
              "id":"ea22640d7a1c44a38f56a9b051969ae3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25de7481622a41cb96a558ce6b12d0bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"f39cac89c48041648a42ce2a46e3a30e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2da6416e920a487fbc653c05e42ddef3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"717c940f2c3a442881764c63b94d1177",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cab314127fd641a6b077f626270678c7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u1.png"}},
{
              "id":"4b5638756bdf41be8261c5e4b5eaf825",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1d5cfd554ebd4d13be49b36055e517c2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"524e5be375eb4577af785e0a3911013c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8cf3eba9fdf54804a9b1cdcf4b6f2db0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"47dba25492b14a01bc8f318be9a91447",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d72107c55bb349da96fb0fa851542517",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u7.png"}},
{
              "id":"447ca318f965497db4493a33953c0669",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c18b556637e140e0a5be86d3b711b2bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u17.png"}},
{
              "id":"a080ef72c2584bf48b2e60a8ad43dc73",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99d6ac98fb484892a5e8976ae54427f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u17.png"}},
{
              "id":"5a4d5f3302394044a00bd2ca03eacaca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":427,
                  "y":0},
                "size":{
                  "width":163,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b2ddcab816c45f98adb81af68434dbb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":427,
                      "y":0},
                    "size":{
                      "width":163,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u9.png"}},
{
              "id":"50c46cb304e64a4c9f2bf8bfc20be06c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":427,
                  "y":30},
                "size":{
                  "width":163,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e34ece5f7024ee5a59b5d6c9d335569",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":427,
                      "y":30},
                    "size":{
                      "width":163,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u19.png"}},
{
              "id":"846cdaad2da24d83973a32bc4814b6e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":427,
                  "y":60},
                "size":{
                  "width":163,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a1ab655bee54f11a5a4aea50736610b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":427,
                      "y":60},
                    "size":{
                      "width":163,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u19.png"}},
{
              "id":"4d1b472347514bddbbad5c07e852a6d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2285452a3e4a49eaaa56b3d823ef876d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"6d62eed422ce4e1792885fd32baa35c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e117b11ec2a845d5b27a8efd71c599f5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"d3fd74de88c4495f8ce7c062d122c915",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ca8b47f53d904a44b95d99458becdb13",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"895f4d29c10b4c49bcc2e8f8215d3f09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":90},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1551e66732a2413aa975ecd7f37d6ecc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":90},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u17.png"}},
{
              "id":"b27eb70e817f4fe5b5cc9de915016119",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":427,
                  "y":90},
                "size":{
                  "width":163,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15b4a418c3b74298af5808475f4627bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":427,
                      "y":90},
                    "size":{
                      "width":163,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u19.png"}},
{
              "id":"343ef28e8c1649f0ba79c895c00abe1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77b3457bfae041b1a0090d1035b532a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"c3bdecd57f79457a9ea78ffe1d6c7613",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b92335166b94ff5b1eb0f5d725ed1bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"e58265e1746645ffb6c80ebe719afe3c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dbfb1a160e5a4d3f97553f7cc1c989dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"0c57f59113c34201ac82858b1004b902",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":120},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd1727afccd24d60941a1810a10bc681",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":120},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u17.png"}},
{
              "id":"e891c8e69e7e45cfb5614a6d3a3c4d71",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":427,
                  "y":120},
                "size":{
                  "width":163,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6e9f0a6e07b543818fef42b22a07ec20",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":427,
                      "y":120},
                    "size":{
                      "width":163,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u19.png"}},
{
              "id":"7b4ea0efb11f4b918457306106076d49",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea5ba555ef284061a84f3b5b72459347",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"e03b0403848a4bc68c16381e9a7a9e14",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":150},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"162bc889a7ff4d928a45e0b2d93f0014",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"6e8704f63118455c81fed389452ca2e5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a54e862129f4ce5a7942d9a0225c8c9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"0cb09bec72f643539c79df74487ac434",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":150},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2b57ef64da849b98b11cd59bed12081",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":150},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u17.png"}},
{
              "id":"29083ae9f57f4a2c83d384612880e94c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":427,
                  "y":150},
                "size":{
                  "width":163,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb0659da9b214f45b72ff71cf0a210da",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":427,
                      "y":150},
                    "size":{
                      "width":163,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u19.png"}},
{
              "id":"731d18044d914e939a1e35fc4c436f59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"049c0166c6ac48528b9b440b1c8e2bdf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u101.png"}},
{
              "id":"bf2ee52a3216434c8fd90f6ab7a20035",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":180},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7befc79d5a424cb8a6590ac21ca343ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":180},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u101.png"}},
{
              "id":"f556a770af534e90a10a2e4a314dd7e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":180},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7cbe2c7fc12a49cb8d6a7ba6fbc4162a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":180},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u101.png"}},
{
              "id":"18a888d7ba5043a68a69720bbca2cb07",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":180},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"476a63e2d3994a76bdcd0e454da01857",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":180},
                    "size":{
                      "width":127,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u67.png"}},
{
              "id":"4e3541cb61ea4840826e956c2aaa9ba8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":427,
                  "y":180},
                "size":{
                  "width":163,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2565746833324769bc521b07d061bf3a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":427,
                      "y":180},
                    "size":{
                      "width":163,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品管理/u69.png"}}]},
{
          "id":"5d0152208dfb4d56a5972ac4bc79e30f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":35},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a9b7c5e14ed34b9ca8ca1c7e96899c37",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":35},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"319ed5a59bb2465384fdbf672756802c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":134},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f292cf0c24fc4162aeabd980e1acb382",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":163},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0eacac66e0324117a65014eb03cad2ec",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":163},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5eb78d7d8af3425b8889798e831652f7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":193},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b76b04d60c37426484e1f73de489f033",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":193},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"aed757896c0d410da055500a12d47562",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":223},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"52f35fc77cd34422895f198d16c41e87",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":223},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"32111eb4b2434c24abafbe1022433dcd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":254},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5bf200ca2d22417382449f20bd5055a5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":254},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8933fdcb37d744a283e0ed0a7426f73a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":340},
            "size":{
              "width":220,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f14347a302ca4f8189610d43087a00a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":340},
                "size":{
                  "width":220,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8377377c6b334fcd9885511fa6bba06b":{
      "scriptId":"u0"},
    "2347383836e4465e8a9944a92d089164":{
      "scriptId":"u1"},
    "caaceb8e7aff42f4b264534a9b76e7af":{
      "scriptId":"u2"},
    "1d3c2831ebdf48a88981042f72f802c1":{
      "scriptId":"u3"},
    "e8d0c99d8f574a808987cc844820ce00":{
      "scriptId":"u4"},
    "717c940f2c3a442881764c63b94d1177":{
      "scriptId":"u5"},
    "cab314127fd641a6b077f626270678c7":{
      "scriptId":"u6"},
    "47dba25492b14a01bc8f318be9a91447":{
      "scriptId":"u7"},
    "d72107c55bb349da96fb0fa851542517":{
      "scriptId":"u8"},
    "5a4d5f3302394044a00bd2ca03eacaca":{
      "scriptId":"u9"},
    "2b2ddcab816c45f98adb81af68434dbb":{
      "scriptId":"u10"},
    "1a60ab59591c4746922beb2f0a31bcb1":{
      "scriptId":"u11"},
    "f88028cca6a540d6aa6a64d251a85dc6":{
      "scriptId":"u12"},
    "ea22640d7a1c44a38f56a9b051969ae3":{
      "scriptId":"u13"},
    "25de7481622a41cb96a558ce6b12d0bf":{
      "scriptId":"u14"},
    "4b5638756bdf41be8261c5e4b5eaf825":{
      "scriptId":"u15"},
    "1d5cfd554ebd4d13be49b36055e517c2":{
      "scriptId":"u16"},
    "447ca318f965497db4493a33953c0669":{
      "scriptId":"u17"},
    "c18b556637e140e0a5be86d3b711b2bf":{
      "scriptId":"u18"},
    "50c46cb304e64a4c9f2bf8bfc20be06c":{
      "scriptId":"u19"},
    "4e34ece5f7024ee5a59b5d6c9d335569":{
      "scriptId":"u20"},
    "114a5db27323462cb1b5fc22129ad18d":{
      "scriptId":"u21"},
    "8bbf72dbda3d4db9b851f3efeefc925d":{
      "scriptId":"u22"},
    "f39cac89c48041648a42ce2a46e3a30e":{
      "scriptId":"u23"},
    "2da6416e920a487fbc653c05e42ddef3":{
      "scriptId":"u24"},
    "524e5be375eb4577af785e0a3911013c":{
      "scriptId":"u25"},
    "8cf3eba9fdf54804a9b1cdcf4b6f2db0":{
      "scriptId":"u26"},
    "a080ef72c2584bf48b2e60a8ad43dc73":{
      "scriptId":"u27"},
    "99d6ac98fb484892a5e8976ae54427f9":{
      "scriptId":"u28"},
    "846cdaad2da24d83973a32bc4814b6e1":{
      "scriptId":"u29"},
    "0a1ab655bee54f11a5a4aea50736610b":{
      "scriptId":"u30"},
    "4d1b472347514bddbbad5c07e852a6d3":{
      "scriptId":"u31"},
    "2285452a3e4a49eaaa56b3d823ef876d":{
      "scriptId":"u32"},
    "6d62eed422ce4e1792885fd32baa35c9":{
      "scriptId":"u33"},
    "e117b11ec2a845d5b27a8efd71c599f5":{
      "scriptId":"u34"},
    "d3fd74de88c4495f8ce7c062d122c915":{
      "scriptId":"u35"},
    "ca8b47f53d904a44b95d99458becdb13":{
      "scriptId":"u36"},
    "895f4d29c10b4c49bcc2e8f8215d3f09":{
      "scriptId":"u37"},
    "1551e66732a2413aa975ecd7f37d6ecc":{
      "scriptId":"u38"},
    "b27eb70e817f4fe5b5cc9de915016119":{
      "scriptId":"u39"},
    "15b4a418c3b74298af5808475f4627bf":{
      "scriptId":"u40"},
    "343ef28e8c1649f0ba79c895c00abe1c":{
      "scriptId":"u41"},
    "77b3457bfae041b1a0090d1035b532a0":{
      "scriptId":"u42"},
    "c3bdecd57f79457a9ea78ffe1d6c7613":{
      "scriptId":"u43"},
    "6b92335166b94ff5b1eb0f5d725ed1bd":{
      "scriptId":"u44"},
    "e58265e1746645ffb6c80ebe719afe3c":{
      "scriptId":"u45"},
    "dbfb1a160e5a4d3f97553f7cc1c989dc":{
      "scriptId":"u46"},
    "0c57f59113c34201ac82858b1004b902":{
      "scriptId":"u47"},
    "bd1727afccd24d60941a1810a10bc681":{
      "scriptId":"u48"},
    "e891c8e69e7e45cfb5614a6d3a3c4d71":{
      "scriptId":"u49"},
    "6e9f0a6e07b543818fef42b22a07ec20":{
      "scriptId":"u50"},
    "7b4ea0efb11f4b918457306106076d49":{
      "scriptId":"u51"},
    "ea5ba555ef284061a84f3b5b72459347":{
      "scriptId":"u52"},
    "e03b0403848a4bc68c16381e9a7a9e14":{
      "scriptId":"u53"},
    "162bc889a7ff4d928a45e0b2d93f0014":{
      "scriptId":"u54"},
    "6e8704f63118455c81fed389452ca2e5":{
      "scriptId":"u55"},
    "4a54e862129f4ce5a7942d9a0225c8c9":{
      "scriptId":"u56"},
    "0cb09bec72f643539c79df74487ac434":{
      "scriptId":"u57"},
    "f2b57ef64da849b98b11cd59bed12081":{
      "scriptId":"u58"},
    "29083ae9f57f4a2c83d384612880e94c":{
      "scriptId":"u59"},
    "eb0659da9b214f45b72ff71cf0a210da":{
      "scriptId":"u60"},
    "731d18044d914e939a1e35fc4c436f59":{
      "scriptId":"u61"},
    "049c0166c6ac48528b9b440b1c8e2bdf":{
      "scriptId":"u62"},
    "bf2ee52a3216434c8fd90f6ab7a20035":{
      "scriptId":"u63"},
    "7befc79d5a424cb8a6590ac21ca343ad":{
      "scriptId":"u64"},
    "f556a770af534e90a10a2e4a314dd7e2":{
      "scriptId":"u65"},
    "7cbe2c7fc12a49cb8d6a7ba6fbc4162a":{
      "scriptId":"u66"},
    "18a888d7ba5043a68a69720bbca2cb07":{
      "scriptId":"u67"},
    "476a63e2d3994a76bdcd0e454da01857":{
      "scriptId":"u68"},
    "4e3541cb61ea4840826e956c2aaa9ba8":{
      "scriptId":"u69"},
    "2565746833324769bc521b07d061bf3a":{
      "scriptId":"u70"},
    "5d0152208dfb4d56a5972ac4bc79e30f":{
      "scriptId":"u71"},
    "a9b7c5e14ed34b9ca8ca1c7e96899c37":{
      "scriptId":"u72"},
    "319ed5a59bb2465384fdbf672756802c":{
      "scriptId":"u73"},
    "f292cf0c24fc4162aeabd980e1acb382":{
      "scriptId":"u74"},
    "0eacac66e0324117a65014eb03cad2ec":{
      "scriptId":"u75"},
    "5eb78d7d8af3425b8889798e831652f7":{
      "scriptId":"u76"},
    "b76b04d60c37426484e1f73de489f033":{
      "scriptId":"u77"},
    "aed757896c0d410da055500a12d47562":{
      "scriptId":"u78"},
    "52f35fc77cd34422895f198d16c41e87":{
      "scriptId":"u79"},
    "32111eb4b2434c24abafbe1022433dcd":{
      "scriptId":"u80"},
    "5bf200ca2d22417382449f20bd5055a5":{
      "scriptId":"u81"},
    "8933fdcb37d744a283e0ed0a7426f73a":{
      "scriptId":"u82"},
    "f14347a302ca4f8189610d43087a00a9":{
      "scriptId":"u83"}}});