/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.xmq.project.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Project service. Represents a row in the &quot;xmq_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.justonetech.xmq.project.model.impl.ProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.justonetech.xmq.project.model.impl.ProjectImpl}.
 * </p>
 *
 * @author fanqi
 * @see Project
 * @see com.justonetech.xmq.project.model.impl.ProjectImpl
 * @see com.justonetech.xmq.project.model.impl.ProjectModelImpl
 * @generated
 */
public interface ProjectModel extends BaseModel<Project> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link Project} interface instead.
	 */

	/**
	 * Returns the primary key of this project.
	 *
	 * @return the primary key of this project
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this project.
	 *
	 * @param primaryKey the primary key of this project
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the bjbh of this project.
	 *
	 * @return the bjbh of this project
	 */
	@AutoEscape
	public String getBjbh();

	/**
	 * Sets the bjbh of this project.
	 *
	 * @param bjbh the bjbh of this project
	 */
	public void setBjbh(String bjbh);

	/**
	 * Returns the bjrq of this project.
	 *
	 * @return the bjrq of this project
	 */
	public Date getBjrq();

	/**
	 * Sets the bjrq of this project.
	 *
	 * @param bjrq the bjrq of this project
	 */
	public void setBjrq(Date bjrq);

	/**
	 * Returns the bj webid of this project.
	 *
	 * @return the bj webid of this project
	 */
	@AutoEscape
	public String getBjWebid();

	/**
	 * Sets the bj webid of this project.
	 *
	 * @param bjWebid the bj webid of this project
	 */
	public void setBjWebid(String bjWebid);

	/**
	 * Returns the xmmc of this project.
	 *
	 * @return the xmmc of this project
	 */
	@AutoEscape
	public String getXmmc();

	/**
	 * Sets the xmmc of this project.
	 *
	 * @param xmmc the xmmc of this project
	 */
	public void setXmmc(String xmmc);

	/**
	 * Returns the bjwcbj of this project.
	 *
	 * @return the bjwcbj of this project
	 */
	@AutoEscape
	public String getBjwcbj();

	/**
	 * Sets the bjwcbj of this project.
	 *
	 * @param bjwcbj the bjwcbj of this project
	 */
	public void setBjwcbj(String bjwcbj);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.justonetech.xmq.project.model.Project project);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.justonetech.xmq.project.model.Project> toCacheModel();

	@Override
	public com.justonetech.xmq.project.model.Project toEscapedModel();

	@Override
	public com.justonetech.xmq.project.model.Project toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}