$axure.loadCurrentPage({
  "url":"项目形象进度节点管理.html",
  "generationDate":new Date(1430724551622.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fae21eb6a1224a698979032bbb3a368d",
    "type":"Axure:Page",
    "name":"项目形象进度节点管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f2eb3ad1a423483ab5fc96fc4b2685e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":22},
            "size":{
              "width":710,
              "height":427}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ccb77e3df3d4e8b963c462e26c2ff3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":22},
                "size":{
                  "width":710,
                  "height":427}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目办证阶段管理/u0.png"}},
{
          "id":"49606c34aa2946379377a435c7bada49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":20},
            "size":{
              "width":196,
              "height":529}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e552c5452e444c81aabebbbebee38c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":20},
                "size":{
                  "width":196,
                  "height":529}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目形象进度节点管理/u2.png"}},
{
          "id":"3a6aef4730674ef0a116ad1e25d0d3d2",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":23},
            "size":{
              "width":198,
              "height":500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a421b9267784956801d47d8b896a4eb",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "size":{
                  "width":93,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4658112788d148c98ca0eedc9b52be73",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":93,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"893c8909d4724c6cbafe851b2653f5d7",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":93,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5854723a69f84786b5a600197f46c5ef",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa5c54e9ec554e8a973dd9b777ef7341",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/项目办证阶段管理/u6.png",
                    "selected~":"images/项目办证阶段管理/u6_selected.png"}},
{
                  "id":"60a29eec59bd41369c8c522b0cf8fc8f",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":93,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f14e84c6741475784a3df5fac28cc98",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":93,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fa25acfc63ba40f4b7d7a63a9281faf5",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":93,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"e14f280067e64a60a3e5d199142a1910",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"22b790d24ace4da99ee2a88b5417a394",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"c4e350b430214a9593008fc64ef5384b",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":20},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"22b790d24ace4da99ee2a88b5417a394"},
{
                      "id":"520095d0b503444faac9b307463283a3",
                      "label":"",
                      "type":"imageBox",
                      "styleType":"imageBox",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"180406cf70ac4f39b7c86ee83ff1e43b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
}},
                            "location":{
                              "x":6,
                              "y":6},
                            "size":{
                              "width":9,
                              "height":9}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/项目办证阶段管理/u6.png",
                        "selected~":"images/项目办证阶段管理/u6_selected.png"}},
{
                      "id":"4b53d89dfd0b4143a6ff1e84ee87d6d6",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fc1ded76b7354f309fed5317737f8457",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"10c196eb4ee94dbe965281d045a3e32d",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":40},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"fc1ded76b7354f309fed5317737f8457"}],
                  "buttonShapeId":"9f14e84c6741475784a3df5fac28cc98"},
{
                  "id":"8a4b37860ed04b45aa8e2f7e3e3cbe0b",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"03c5d31df3574c52915e69004ebfdf7b",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a66fb975b1084c2f89fa361244a8657e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"e663439443a449dbaee4c82e89ad539c",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"951b9a9a45a441f2911f3650355e056c",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7f3d2eb4282e43eab5caa5bee8ed7166",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":20},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"951b9a9a45a441f2911f3650355e056c"},
{
                      "id":"5da091f6c3f748c5acc2a0e7037de88c",
                      "label":"",
                      "type":"imageBox",
                      "styleType":"imageBox",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fe335fd25eb24dfabef25f65fb9515c3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
}},
                            "location":{
                              "x":6,
                              "y":6},
                            "size":{
                              "width":9,
                              "height":9}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/项目办证阶段管理/u6.png",
                        "selected~":"images/项目办证阶段管理/u6_selected.png"}},
{
                      "id":"7d59d3375c104c8faded8fba41d83525",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9348c22f3609456babc5dc33b10395aa",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0c436c1d40a4435ba76ee0323177f7c6",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":40},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"9348c22f3609456babc5dc33b10395aa"}],
                  "buttonShapeId":"03c5d31df3574c52915e69004ebfdf7b"},
{
                  "id":"61d9125c46be47a38a4d36f6e9908d3e",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":140},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b59b7d2dff374fc18b8b2520359c62cc",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":140},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"75d9294fc41d4a20a8504d2233f1f400",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":140},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"fb9ad2f5dda34f929cf0658a3e09761d",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"894b5b05cb1d4946bb9e82c80264106a",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"e01a4979567a41e386782f1cc0bf2b81",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":20},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"894b5b05cb1d4946bb9e82c80264106a"},
{
                      "id":"0d1b2d21bc1c433bad68b803c223371b",
                      "label":"",
                      "type":"imageBox",
                      "styleType":"imageBox",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"08f02b1677a742fb807c69f23259911b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
}},
                            "location":{
                              "x":6,
                              "y":6},
                            "size":{
                              "width":9,
                              "height":9}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/项目办证阶段管理/u6.png",
                        "selected~":"images/项目办证阶段管理/u6_selected.png"}},
{
                      "id":"6b800d23f9904f008b39d7072d0ba646",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3de31cdc300a48fdadb8f7db48155869",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"49ec3fb913994e68bbab6c898b2ae454",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":40},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"3de31cdc300a48fdadb8f7db48155869"}],
                  "buttonShapeId":"b59b7d2dff374fc18b8b2520359c62cc"},
{
                  "id":"806092def80f4f14b10bfc59bb82e6b0",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":200},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a5504cc8ad4e4dd29c50f1649bd08aa5",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":200},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6b37c1cf178740f7b34dc9857d4af37b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":200},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"f90b5dc1a8a7494eb32d32d817d71c18",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f7e7ccc16a884f9f895e5f7a6ccfaca3",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"aa633bf16bce4b12806831ee602dfc35",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":20},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"f7e7ccc16a884f9f895e5f7a6ccfaca3"},
{
                      "id":"ac8c4a0a42a5422e8f30834afb44490f",
                      "label":"",
                      "type":"imageBox",
                      "styleType":"imageBox",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1eafb94a1fab421ba2f0c9393daf993c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
}},
                            "location":{
                              "x":6,
                              "y":6},
                            "size":{
                              "width":9,
                              "height":9}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/项目办证阶段管理/u6.png",
                        "selected~":"images/项目办证阶段管理/u6_selected.png"}},
{
                      "id":"861a00d331704c9f83d69b9875ee1b8c",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"de0dd869ae4e4f07b27fcb35c96083bb",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"09e638f11c404865815ea2d4b7fc8b73",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":40},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"de0dd869ae4e4f07b27fcb35c96083bb"}],
                  "buttonShapeId":"a5504cc8ad4e4dd29c50f1649bd08aa5"},
{
                  "id":"d9a64a7be9924eadaa26d06801b20308",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":260},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1739560ac4249c08cdda55cba395524",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":260},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d03eb803576c42d0979a0dad53e63891",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":260},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"3f57683fa8384de387e6e72507c58a3f",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c2cb913b659d4f02abc5d7fe457665ea",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ef3afdc61a2542b799fcca5031db295e",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":20},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"c2cb913b659d4f02abc5d7fe457665ea"},
{
                      "id":"6f490827b7be49ffa3c0dc6a15d95287",
                      "label":"",
                      "type":"imageBox",
                      "styleType":"imageBox",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f5ab15b22744430eb4b8b12b5314c2ed",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
}},
                            "location":{
                              "x":6,
                              "y":6},
                            "size":{
                              "width":9,
                              "height":9}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/项目办证阶段管理/u6.png",
                        "selected~":"images/项目办证阶段管理/u6_selected.png"}},
{
                      "id":"ac18e230546c40cd83c849920ca47b7d",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"867255a418d14de2bf37930da7d3c6bd",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"68b43424b2424a88a48d2e606f5bdf4d",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":40},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "buttonShapeId":"867255a418d14de2bf37930da7d3c6bd"}],
                  "buttonShapeId":"c1739560ac4249c08cdda55cba395524"},
{
                  "id":"8d9162c51ba6430283ce840dd213b6a0",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":320},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84b00f2ef96a408aa2f681845b061292",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":320},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"233df677c2c648fea959561210039dd9",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":320},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}},
{
                      "id":"ddbe3f2d4ed947049fa92805bba689cf",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2ca195aeb8ce4cc0a4a78d970cbd5a06",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"992b6a846fba4a11a4cdb37725394d83",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":20},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"95b58217c4624820ad9b03dde519b734",
                          "label":"",
                          "type":"treeNodeObject",
                          "styleType":"treeNodeObject",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"cdac4aec05214d5a93bc179ae2c9323b",
                              "label":"",
                              "isContained":true,
                              "type":"buttonShape",
                              "styleType":"buttonShape",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":20},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"36dd4826f3cd40e188515e89d1ffe31f",
                                  "label":"",
                                  "isContained":true,
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "location":{
                                      "x":20,
                                      "y":20},
                                    "size":{
                                      "width":80,
                                      "height":20}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"resources/images/transparent.gif"}}],
                          "buttonShapeId":"cdac4aec05214d5a93bc179ae2c9323b"},
{
                          "id":"39b4243d3fea4f289d62a1cb4b4524ed",
                          "label":"",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
}},
                            "location":{
                              "x":6,
                              "y":6},
                            "size":{
                              "width":9,
                              "height":9}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"07489b5c847142449307709afb24132f",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "selected":{
}},
                                "location":{
                                  "x":6,
                                  "y":6},
                                "size":{
                                  "width":9,
                                  "height":9}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/项目办证阶段管理/u6.png",
                            "selected~":"images/项目办证阶段管理/u6_selected.png"}},
{
                          "id":"2a3cacfa432f4e97b59b9fbffb95f748",
                          "label":"",
                          "type":"treeNodeObject",
                          "styleType":"treeNodeObject",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"dfea222e628641d08cd23d2a059904b0",
                              "label":"",
                              "isContained":true,
                              "type":"buttonShape",
                              "styleType":"buttonShape",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":40},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"cada31b14cc345948e0ce10e62629e9f",
                                  "label":"",
                                  "isContained":true,
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "location":{
                                      "x":20,
                                      "y":40},
                                    "size":{
                                      "width":80,
                                      "height":20}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"resources/images/transparent.gif"}}],
                          "buttonShapeId":"dfea222e628641d08cd23d2a059904b0"}],
                      "buttonShapeId":"2ca195aeb8ce4cc0a4a78d970cbd5a06"},
{
                      "id":"f2dbf0d77e1a45029afaa11b1f1974e8",
                      "label":"",
                      "type":"imageBox",
                      "styleType":"imageBox",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b93f165acd5944bea7de0c10aeb70828",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
}},
                            "location":{
                              "x":6,
                              "y":6},
                            "size":{
                              "width":9,
                              "height":9}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/项目办证阶段管理/u6.png",
                        "selected~":"images/项目办证阶段管理/u6_selected.png"}},
{
                      "id":"6cd1d1334072443394944ddcac595cd7",
                      "label":"",
                      "type":"treeNodeObject",
                      "styleType":"treeNodeObject",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":158,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e6b87d42e86d49f6bdec673af9d9a689",
                          "label":"",
                          "isContained":true,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":158,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"2b746754c7fc4335abe1c520e7d3feaf",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":80},
                                "size":{
                                  "width":158,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"90c5fcfc291447b099cd4be36a13eff9",
                          "label":"",
                          "type":"treeNodeObject",
                          "styleType":"treeNodeObject",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":106,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"88094b5aea1843a19b4508152fcc999c",
                              "label":"",
                              "isContained":true,
                              "type":"buttonShape",
                              "styleType":"buttonShape",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":20},
                                "size":{
                                  "width":106,
                                  "height":20}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"73430d3f6b254134ac7f0edc7f295673",
                                  "label":"",
                                  "isContained":true,
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "location":{
                                      "x":20,
                                      "y":20},
                                    "size":{
                                      "width":106,
                                      "height":20}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"resources/images/transparent.gif"}}],
                          "buttonShapeId":"88094b5aea1843a19b4508152fcc999c"},
{
                          "id":"9ca5e0dc7ada4adf9a1425ece3bf054a",
                          "label":"",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "selected":{
}},
                            "location":{
                              "x":6,
                              "y":6},
                            "size":{
                              "width":9,
                              "height":9}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d8b181715ca34b55809d6b126fa31a78",
                              "label":"",
                              "isContained":true,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "selected":{
}},
                                "location":{
                                  "x":6,
                                  "y":6},
                                "size":{
                                  "width":9,
                                  "height":9}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/项目办证阶段管理/u6.png",
                            "selected~":"images/项目办证阶段管理/u6_selected.png"}},
{
                          "id":"40ddae01c5db4639919ac7dda755fd40",
                          "label":"",
                          "type":"treeNodeObject",
                          "styleType":"treeNodeObject",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"25ce99967d024640b0b3d1c579778538",
                              "label":"",
                              "isContained":true,
                              "type":"buttonShape",
                              "styleType":"buttonShape",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":40},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"ae313385c091485795562474353fa85a",
                                  "label":"",
                                  "isContained":true,
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "location":{
                                      "x":20,
                                      "y":40},
                                    "size":{
                                      "width":80,
                                      "height":20}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"resources/images/transparent.gif"}}],
                          "buttonShapeId":"25ce99967d024640b0b3d1c579778538"},
{
                          "id":"1742557d99bd43b5be2251035ceac42a",
                          "label":"",
                          "type":"treeNodeObject",
                          "styleType":"treeNodeObject",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"11c36d6d37894045a646fd132118dad7",
                              "label":"",
                              "isContained":true,
                              "type":"buttonShape",
                              "styleType":"buttonShape",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":60},
                                "size":{
                                  "width":80,
                                  "height":20}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"9eb7f1eda29849059262cdaee3e88d87",
                                  "label":"",
                                  "isContained":true,
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "location":{
                                      "x":20,
                                      "y":60},
                                    "size":{
                                      "width":80,
                                      "height":20}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"resources/images/transparent.gif"}}],
                          "buttonShapeId":"11c36d6d37894045a646fd132118dad7"},
{
                          "id":"f9f4735534ff43cca0d5f69ef6f1ee41",
                          "label":"",
                          "type":"treeNodeObject",
                          "styleType":"treeNodeObject",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":105,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"befdf2a9ad634472946b656025668c7c",
                              "label":"",
                              "isContained":true,
                              "type":"buttonShape",
                              "styleType":"buttonShape",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":80},
                                "size":{
                                  "width":105,
                                  "height":20}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"833e471d80eb4801aeb99996cb3d5e09",
                                  "label":"",
                                  "isContained":true,
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "location":{
                                      "x":20,
                                      "y":80},
                                    "size":{
                                      "width":105,
                                      "height":20}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"resources/images/transparent.gif"}}],
                          "buttonShapeId":"befdf2a9ad634472946b656025668c7c"}],
                      "buttonShapeId":"e6b87d42e86d49f6bdec673af9d9a689"}],
                  "buttonShapeId":"84b00f2ef96a408aa2f681845b061292"}],
              "buttonShapeId":"4658112788d148c98ca0eedc9b52be73"}]},
{
          "id":"9bd6337f54f74e7bb293ec3a021ed549",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":56},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"295d1d3027e2405cb1a358d735682993",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":344,
              "y":58},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c73e1df2e52c48189d9e094fa09e0df1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":344,
                  "y":58},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc1c727e4b6c42769312cf25397f2499",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":726,
              "y":53},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5285d39eaf63487db9c09657e67e0638",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":680,
              "y":56},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0307785306e741888895bf4d5c7a7a83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":680,
                  "y":56},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a443091a19c044a580c500402fed1a46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":319,
              "y":96},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b040e5b3ae045c09ede436aca7b4403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":319,
                  "y":96},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ec7a2cacc514a72bca1c6e305cf3ff0",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":125},
            "size":{
              "width":531,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"678dc75edbf5455d976b3da9fe20a8eb",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":96},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c683936c9ce41fea31ba16c8f8ac475",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":395,
                  "y":96},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a47e1aa7d8084816935058be96eda1c1",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":96},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e040d48fcbd44bcb4ae719cab056cee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":96},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c3ca8e7fb9454f99a8ee646cbf1c6039",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":404},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6872d6b452d6478a96d17738c61a3e74",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":612,
              "y":404},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"81ed5118be06474fae2b81c1e49e10a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":379},
            "size":{
              "width":710,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/项目办证阶段管理/u166_line.png"}},
{
          "id":"c010d84649b04c94bf0bf95dea4643e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":345,
              "y":158},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f25a5d2f64e14d729b070e76e2854b79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":345,
                  "y":158},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f2eb3ad1a423483ab5fc96fc4b2685e7":{
      "scriptId":"u0"},
    "0ccb77e3df3d4e8b963c462e26c2ff3a":{
      "scriptId":"u1"},
    "49606c34aa2946379377a435c7bada49":{
      "scriptId":"u2"},
    "e4e552c5452e444c81aabebbbebee38c":{
      "scriptId":"u3"},
    "3a6aef4730674ef0a116ad1e25d0d3d2":{
      "scriptId":"u4"},
    "8a421b9267784956801d47d8b896a4eb":{
      "scriptId":"u5"},
    "5854723a69f84786b5a600197f46c5ef":{
      "scriptId":"u6"},
    "fa5c54e9ec554e8a973dd9b777ef7341":{
      "scriptId":"u7"},
    "4658112788d148c98ca0eedc9b52be73":{
      "scriptId":"u8"},
    "893c8909d4724c6cbafe851b2653f5d7":{
      "scriptId":"u9"},
    "60a29eec59bd41369c8c522b0cf8fc8f":{
      "scriptId":"u10"},
    "520095d0b503444faac9b307463283a3":{
      "scriptId":"u11"},
    "180406cf70ac4f39b7c86ee83ff1e43b":{
      "scriptId":"u12"},
    "9f14e84c6741475784a3df5fac28cc98":{
      "scriptId":"u13"},
    "fa25acfc63ba40f4b7d7a63a9281faf5":{
      "scriptId":"u14"},
    "e14f280067e64a60a3e5d199142a1910":{
      "scriptId":"u15"},
    "22b790d24ace4da99ee2a88b5417a394":{
      "scriptId":"u16"},
    "c4e350b430214a9593008fc64ef5384b":{
      "scriptId":"u17"},
    "4b53d89dfd0b4143a6ff1e84ee87d6d6":{
      "scriptId":"u18"},
    "fc1ded76b7354f309fed5317737f8457":{
      "scriptId":"u19"},
    "10c196eb4ee94dbe965281d045a3e32d":{
      "scriptId":"u20"},
    "8a4b37860ed04b45aa8e2f7e3e3cbe0b":{
      "scriptId":"u21"},
    "5da091f6c3f748c5acc2a0e7037de88c":{
      "scriptId":"u22"},
    "fe335fd25eb24dfabef25f65fb9515c3":{
      "scriptId":"u23"},
    "03c5d31df3574c52915e69004ebfdf7b":{
      "scriptId":"u24"},
    "a66fb975b1084c2f89fa361244a8657e":{
      "scriptId":"u25"},
    "e663439443a449dbaee4c82e89ad539c":{
      "scriptId":"u26"},
    "951b9a9a45a441f2911f3650355e056c":{
      "scriptId":"u27"},
    "7f3d2eb4282e43eab5caa5bee8ed7166":{
      "scriptId":"u28"},
    "7d59d3375c104c8faded8fba41d83525":{
      "scriptId":"u29"},
    "9348c22f3609456babc5dc33b10395aa":{
      "scriptId":"u30"},
    "0c436c1d40a4435ba76ee0323177f7c6":{
      "scriptId":"u31"},
    "61d9125c46be47a38a4d36f6e9908d3e":{
      "scriptId":"u32"},
    "0d1b2d21bc1c433bad68b803c223371b":{
      "scriptId":"u33"},
    "08f02b1677a742fb807c69f23259911b":{
      "scriptId":"u34"},
    "b59b7d2dff374fc18b8b2520359c62cc":{
      "scriptId":"u35"},
    "75d9294fc41d4a20a8504d2233f1f400":{
      "scriptId":"u36"},
    "fb9ad2f5dda34f929cf0658a3e09761d":{
      "scriptId":"u37"},
    "894b5b05cb1d4946bb9e82c80264106a":{
      "scriptId":"u38"},
    "e01a4979567a41e386782f1cc0bf2b81":{
      "scriptId":"u39"},
    "6b800d23f9904f008b39d7072d0ba646":{
      "scriptId":"u40"},
    "3de31cdc300a48fdadb8f7db48155869":{
      "scriptId":"u41"},
    "49ec3fb913994e68bbab6c898b2ae454":{
      "scriptId":"u42"},
    "806092def80f4f14b10bfc59bb82e6b0":{
      "scriptId":"u43"},
    "ac8c4a0a42a5422e8f30834afb44490f":{
      "scriptId":"u44"},
    "1eafb94a1fab421ba2f0c9393daf993c":{
      "scriptId":"u45"},
    "a5504cc8ad4e4dd29c50f1649bd08aa5":{
      "scriptId":"u46"},
    "6b37c1cf178740f7b34dc9857d4af37b":{
      "scriptId":"u47"},
    "f90b5dc1a8a7494eb32d32d817d71c18":{
      "scriptId":"u48"},
    "f7e7ccc16a884f9f895e5f7a6ccfaca3":{
      "scriptId":"u49"},
    "aa633bf16bce4b12806831ee602dfc35":{
      "scriptId":"u50"},
    "861a00d331704c9f83d69b9875ee1b8c":{
      "scriptId":"u51"},
    "de0dd869ae4e4f07b27fcb35c96083bb":{
      "scriptId":"u52"},
    "09e638f11c404865815ea2d4b7fc8b73":{
      "scriptId":"u53"},
    "d9a64a7be9924eadaa26d06801b20308":{
      "scriptId":"u54"},
    "6f490827b7be49ffa3c0dc6a15d95287":{
      "scriptId":"u55"},
    "f5ab15b22744430eb4b8b12b5314c2ed":{
      "scriptId":"u56"},
    "c1739560ac4249c08cdda55cba395524":{
      "scriptId":"u57"},
    "d03eb803576c42d0979a0dad53e63891":{
      "scriptId":"u58"},
    "3f57683fa8384de387e6e72507c58a3f":{
      "scriptId":"u59"},
    "c2cb913b659d4f02abc5d7fe457665ea":{
      "scriptId":"u60"},
    "ef3afdc61a2542b799fcca5031db295e":{
      "scriptId":"u61"},
    "ac18e230546c40cd83c849920ca47b7d":{
      "scriptId":"u62"},
    "867255a418d14de2bf37930da7d3c6bd":{
      "scriptId":"u63"},
    "68b43424b2424a88a48d2e606f5bdf4d":{
      "scriptId":"u64"},
    "8d9162c51ba6430283ce840dd213b6a0":{
      "scriptId":"u65"},
    "f2dbf0d77e1a45029afaa11b1f1974e8":{
      "scriptId":"u66"},
    "b93f165acd5944bea7de0c10aeb70828":{
      "scriptId":"u67"},
    "84b00f2ef96a408aa2f681845b061292":{
      "scriptId":"u68"},
    "233df677c2c648fea959561210039dd9":{
      "scriptId":"u69"},
    "ddbe3f2d4ed947049fa92805bba689cf":{
      "scriptId":"u70"},
    "39b4243d3fea4f289d62a1cb4b4524ed":{
      "scriptId":"u71"},
    "07489b5c847142449307709afb24132f":{
      "scriptId":"u72"},
    "2ca195aeb8ce4cc0a4a78d970cbd5a06":{
      "scriptId":"u73"},
    "992b6a846fba4a11a4cdb37725394d83":{
      "scriptId":"u74"},
    "95b58217c4624820ad9b03dde519b734":{
      "scriptId":"u75"},
    "cdac4aec05214d5a93bc179ae2c9323b":{
      "scriptId":"u76"},
    "36dd4826f3cd40e188515e89d1ffe31f":{
      "scriptId":"u77"},
    "2a3cacfa432f4e97b59b9fbffb95f748":{
      "scriptId":"u78"},
    "dfea222e628641d08cd23d2a059904b0":{
      "scriptId":"u79"},
    "cada31b14cc345948e0ce10e62629e9f":{
      "scriptId":"u80"},
    "6cd1d1334072443394944ddcac595cd7":{
      "scriptId":"u81"},
    "9ca5e0dc7ada4adf9a1425ece3bf054a":{
      "scriptId":"u82"},
    "d8b181715ca34b55809d6b126fa31a78":{
      "scriptId":"u83"},
    "e6b87d42e86d49f6bdec673af9d9a689":{
      "scriptId":"u84"},
    "2b746754c7fc4335abe1c520e7d3feaf":{
      "scriptId":"u85"},
    "90c5fcfc291447b099cd4be36a13eff9":{
      "scriptId":"u86"},
    "88094b5aea1843a19b4508152fcc999c":{
      "scriptId":"u87"},
    "73430d3f6b254134ac7f0edc7f295673":{
      "scriptId":"u88"},
    "40ddae01c5db4639919ac7dda755fd40":{
      "scriptId":"u89"},
    "25ce99967d024640b0b3d1c579778538":{
      "scriptId":"u90"},
    "ae313385c091485795562474353fa85a":{
      "scriptId":"u91"},
    "1742557d99bd43b5be2251035ceac42a":{
      "scriptId":"u92"},
    "11c36d6d37894045a646fd132118dad7":{
      "scriptId":"u93"},
    "9eb7f1eda29849059262cdaee3e88d87":{
      "scriptId":"u94"},
    "f9f4735534ff43cca0d5f69ef6f1ee41":{
      "scriptId":"u95"},
    "befdf2a9ad634472946b656025668c7c":{
      "scriptId":"u96"},
    "833e471d80eb4801aeb99996cb3d5e09":{
      "scriptId":"u97"},
    "9bd6337f54f74e7bb293ec3a021ed549":{
      "scriptId":"u98"},
    "295d1d3027e2405cb1a358d735682993":{
      "scriptId":"u99"},
    "c73e1df2e52c48189d9e094fa09e0df1":{
      "scriptId":"u100"},
    "dc1c727e4b6c42769312cf25397f2499":{
      "scriptId":"u101"},
    "5285d39eaf63487db9c09657e67e0638":{
      "scriptId":"u102"},
    "0307785306e741888895bf4d5c7a7a83":{
      "scriptId":"u103"},
    "a443091a19c044a580c500402fed1a46":{
      "scriptId":"u104"},
    "5b040e5b3ae045c09ede436aca7b4403":{
      "scriptId":"u105"},
    "0ec7a2cacc514a72bca1c6e305cf3ff0":{
      "scriptId":"u106"},
    "678dc75edbf5455d976b3da9fe20a8eb":{
      "scriptId":"u107"},
    "0c683936c9ce41fea31ba16c8f8ac475":{
      "scriptId":"u108"},
    "a47e1aa7d8084816935058be96eda1c1":{
      "scriptId":"u109"},
    "7e040d48fcbd44bcb4ae719cab056cee":{
      "scriptId":"u110"},
    "c3ca8e7fb9454f99a8ee646cbf1c6039":{
      "scriptId":"u111"},
    "6872d6b452d6478a96d17738c61a3e74":{
      "scriptId":"u112"},
    "81ed5118be06474fae2b81c1e49e10a8":{
      "scriptId":"u113"},
    "c010d84649b04c94bf0bf95dea4643e9":{
      "scriptId":"u114"},
    "f25a5d2f64e14d729b070e76e2854b79":{
      "scriptId":"u115"}}});