var _menus = {"menus":[
    {"menuid":"1","icon":"icon-sys","menuname":"项目信息查询",
        "menus":[
//            {"menuid":"13","menuname":"报建项目查询","icon":"icon-users","url":"mainPage/main.do"},
            {"menuid":"13","menuname":"报建项目查询","icon":"icon-users","url":"mainPage/mainTest.do"},
            {"menuid":"14","menuname":"在建项目查询","icon":"icon-role","url":"mainPage/mainTest2.do"},
            {"menuid":"15","menuname":"完工未验项目查询","icon":"icon-set","url":"demo.html"},
            {"menuid":"16","menuname":"六无工地查询","icon":"icon-log","url":"demo1.html"}
        ]
    },
    {"menuid":"1","icon":"icon-sys","menuname":"建设工程监管",
        "menus":[
            {"menuid":"13","menuname":"履行监管职责情况","icon":"icon-users","url":"demo2.html"},
            {"menuid":"14","menuname":"监管联动绩效考评","icon":"icon-role","url":"demo2.html"},
            {"menuid":"15","menuname":"监管情况阶段通报","icon":"icon-set","url":"demo.html"},
            {"menuid":"16","menuname":"监管人员动态分布图","icon":"icon-log","url":"demo1.html"},
            {"menuid":"16","menuname":"监管人员监管情况","icon":"icon-log","url":"demo1.html"},
            {"menuid":"16","menuname":"待办事项","icon":"icon-log","url":"demo1.html"}
        ]
    },
    {"menuid":"8","icon":"icon-sys","menuname":"应急处置信息",
        "menus":[
            {"menuid":"21","menuname":"信息发布","icon":"icon-nav","url":"demo.html"},
            {"menuid":"22","menuname":"信息反馈情况","icon":"icon-nav","url":"demo1.html"},
            {"menuid":"22","menuname":"事故情况报告","icon":"icon-nav","url":"demo1.html"},
            {"menuid":"22","menuname":"阶段事故情况汇总","icon":"icon-nav","url":"demo1.html"}
        ]
    },
    {"menuid":"56","icon":"icon-sys","menuname":"统计报表分析",
        "menus":[
            {"menuid":"31","menuname":"监管问题汇总","icon":"icon-nav","url":"demo1.html"},
            {"menuid":"32","menuname":"存在突出问题项目","icon":"icon-nav","url":"demo2.html"}
        ]
    },
    {"menuid":"28","icon":"icon-sys","menuname":"项目信息维护",
        "menus":[
            {"menuid":"41","menuname":"项目属地调整","icon":"icon-nav","url":"demo.html"},
            {"menuid":"42","menuname":"项目分类调整","icon":"icon-nav","url":"demo1.html"},
            {"menuid":"43","menuname":"形象进度调整","icon":"icon-nav","url":"demo2.html"},
            {"menuid":"43","menuname":"项目关注度调整","icon":"icon-nav","url":"demo2.html"},
            {"menuid":"43","menuname":"地图标注","icon":"icon-nav","url":"demo2.html"},
            {"menuid":"43","menuname":"信息录入管理","icon":"icon-nav","url":"demo2.html"},
            {"menuid":"43","menuname":"信息录入类型管理","icon":"icon-nav","url":"demo2.html"}
        ]
    },
    {"menuid":"1","icon":"icon-sys","menuname":"系统管理",
        "menus":[
            {"menuid":"14","menuname":"系统字典设置","icon":"icon-role","url":"demo2.html"},
            {"menuid":"14","menuname":"巡查问题字典设置","icon":"icon-role","url":"demo2.html"},
            {"menuid":"14","menuname":"部门管理","icon":"icon-role","url":"demo2.html"},
            {"menuid":"13","menuname":"用户管理","icon":"icon-users","url":"demo2.html"},
            {"menuid":"14","menuname":"角色管理","icon":"icon-role","url":"demo2.html"},
            {"menuid":"15","menuname":"菜单管理","icon":"icon-set","url":"demo.html"},
            {"menuid":"16","menuname":"系统日志","icon":"icon-log","url":"demo1.html"}
        ]
    }
]};