$axure.loadCurrentPage({
  "url":"申请编辑页面.html",
  "generationDate":new Date(1434534636805.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7060648e91184c8d937c5ec92586bf32",
    "type":"Axure:Page",
    "name":"申请编辑页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"612215baa44f4aa38200dc8047adbfd7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":40},
            "size":{
              "width":742,
              "height":460}},
          "adaptiveStyles":{
}},
{
          "id":"e404aec98759495ca7590b0d2c0996f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":40},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6218fcb716f4e8a8617dc834976440b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":40},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0265dce55ce143a5988f5991fd294ba9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":314},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58ea630877b0484ba26e14c829dfd622",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":314},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d87a0dcd52443ce86b12257dc91d836",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":86},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ab5265b4a33b4ffbb8078b5e6fb86bf9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":86},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ad7610362eb84925b6a4121cdf7077fd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":85.5},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a666eb9aa3974bd4b74cb08115243518",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":86},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5ad1cb4206694c07921948d66a4215f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":90},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cff0e5b40d9244eaac1128cac5b1455b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":90},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78d7e05c1c9a47518648847bd05aa473",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":130},
            "size":{
              "width":742,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2c53a50e29e43c0bec398b79d3860c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd1f59d543cf418baee128d76d96d4e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u12.png"}},
{
              "id":"3dc94961430f447fb038dc761949e640",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3a7fed9abe8433b9ef120828600bf04",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u22.png"}},
{
              "id":"b755a2d35ae24f90a3b40a17f0246b02",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71fcc77111824d47b340623b213245c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u22.png"}},
{
              "id":"09be15356fbb4fcebebe90968863af93",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":342,
                  "y":0},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"23b177b00a0e4b95bf88981b6592da4a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":342,
                      "y":0},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u16.png"}},
{
              "id":"9d572a25ad904604b288c736acbc0fb6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":30},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57a2740e211749b5908b263cf50eb882",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":30},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u26.png"}},
{
              "id":"4f041ab8cbc4462491afcb227c03ca81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":60},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc3c301ad0784b17a58735bebab6158b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":60},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u26.png"}},
{
              "id":"18451414291f4e008ae145e8b71f3f0f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":589,
                  "y":0},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f12efa863d7b4b22948bcfb19e0b4dc7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":589,
                      "y":0},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u20.png"}},
{
              "id":"b792872fd2784438b0aa04eabb91e597",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":589,
                  "y":30},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bacfa80c55384202a2c7ad49aab2dab0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":589,
                      "y":30},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u30.png"}},
{
              "id":"c1fa1c4fdd4b4f188e71b32caa055305",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":589,
                  "y":60},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3ad91e6bada248099724a32c7c5e73ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":589,
                      "y":60},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u30.png"}},
{
              "id":"51c2174d9f234fb58a40aa3ed140df2b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"84752e87c0e44e59803b0b5f809434cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u42.png"}},
{
              "id":"d0bd033a79834cf4b4a3f79570e01fde",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":90},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"38066c49654441428128f40133869cd7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":90},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u46.png"}},
{
              "id":"6000a6d048404e3aafd507bb623513a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":589,
                  "y":90},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6e5087076cf343da8d35b313575ccafc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":589,
                      "y":90},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u50.png"}},
{
              "id":"034c9a7343914e05a8aadbda1f54a789",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":209,
                  "y":0},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32b46240a27a4578aa86f3aed122bb09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":209,
                      "y":0},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u14.png"}},
{
              "id":"6dde1e721ad74c0ea08681b9172caef8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":30},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d986efdb778f49058ecf939ced0f565f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":30},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u24.png"}},
{
              "id":"031f4c77704346a2ac04d2848d8e1750",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":60},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6de8d71105b47ecac2888d12c3be83b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":60},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u24.png"}},
{
              "id":"3c32f0ae4ba64e6896a8d392e78559ef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":90},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"177773e4525e43f6aeec81dc2024d013",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":90},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u44.png"}},
{
              "id":"39f20825d25a4bb98c948843154be750",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":453,
                  "y":0},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"366535e4689a41f0bb027a81893dec9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":453,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u18.png"}},
{
              "id":"b485a2fcf9c64d8286436b36db50fe8e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":453,
                  "y":30},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a7f4a96cc1ea4756a1d8d6b868d8bb2e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":453,
                      "y":30},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u28.png"}},
{
              "id":"977b92796e0546c4981863a8bfac071f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":453,
                  "y":60},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a488b2a397543bea7acb9c13656cbdd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":453,
                      "y":60},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u28.png"}},
{
              "id":"2d670dcdf02e4ec098445f4b2fe97785",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":453,
                  "y":90},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff50612f0eb34d36a2d6f933eff2bbef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":453,
                      "y":90},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u48.png"}}]},
{
          "id":"ffd5d40a3b3b4a7fa2c2994de5e1bcb1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":310},
            "size":{
              "width":390,
              "height":120}},
          "adaptiveStyles":{
}},
{
          "id":"86776ae42b914c89a88d1625c0cd3f1a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":133},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"958adb5b89dd47dabca948b8c5548432",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":460},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0f28e4bb5a0a44abade28b30f0f609cc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":460},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4ad56b01783247808a6bee59dc1a58e6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":460},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b93722ecb7fc4e73bc3c468f60e35ecd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":163},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8445a198f1f246c89d355b67c2ed8b36",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":193},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6085d6953d8b47a8801f127b5b30ccfe",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":250},
            "size":{
              "width":742,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ab62649cec44fd6950666532736ed9e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e41270bc3c5340c880ac33f62f93750e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u42.png"}},
{
              "id":"21983a98b8064497abaf66a6010f1e09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":0},
                "size":{
                  "width":533,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9a0d4878fe13400aa6c4f84b450ee64b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":0},
                    "size":{
                      "width":533,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u62.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "612215baa44f4aa38200dc8047adbfd7":{
      "scriptId":"u0"},
    "e404aec98759495ca7590b0d2c0996f0":{
      "scriptId":"u1"},
    "d6218fcb716f4e8a8617dc834976440b":{
      "scriptId":"u2"},
    "0265dce55ce143a5988f5991fd294ba9":{
      "scriptId":"u3"},
    "58ea630877b0484ba26e14c829dfd622":{
      "scriptId":"u4"},
    "4d87a0dcd52443ce86b12257dc91d836":{
      "scriptId":"u5"},
    "ab5265b4a33b4ffbb8078b5e6fb86bf9":{
      "scriptId":"u6"},
    "ad7610362eb84925b6a4121cdf7077fd":{
      "scriptId":"u7"},
    "a666eb9aa3974bd4b74cb08115243518":{
      "scriptId":"u8"},
    "5ad1cb4206694c07921948d66a4215f4":{
      "scriptId":"u9"},
    "cff0e5b40d9244eaac1128cac5b1455b":{
      "scriptId":"u10"},
    "78d7e05c1c9a47518648847bd05aa473":{
      "scriptId":"u11"},
    "d2c53a50e29e43c0bec398b79d3860c3":{
      "scriptId":"u12"},
    "dd1f59d543cf418baee128d76d96d4e7":{
      "scriptId":"u13"},
    "034c9a7343914e05a8aadbda1f54a789":{
      "scriptId":"u14"},
    "32b46240a27a4578aa86f3aed122bb09":{
      "scriptId":"u15"},
    "09be15356fbb4fcebebe90968863af93":{
      "scriptId":"u16"},
    "23b177b00a0e4b95bf88981b6592da4a":{
      "scriptId":"u17"},
    "39f20825d25a4bb98c948843154be750":{
      "scriptId":"u18"},
    "366535e4689a41f0bb027a81893dec9b":{
      "scriptId":"u19"},
    "18451414291f4e008ae145e8b71f3f0f":{
      "scriptId":"u20"},
    "f12efa863d7b4b22948bcfb19e0b4dc7":{
      "scriptId":"u21"},
    "3dc94961430f447fb038dc761949e640":{
      "scriptId":"u22"},
    "e3a7fed9abe8433b9ef120828600bf04":{
      "scriptId":"u23"},
    "6dde1e721ad74c0ea08681b9172caef8":{
      "scriptId":"u24"},
    "d986efdb778f49058ecf939ced0f565f":{
      "scriptId":"u25"},
    "9d572a25ad904604b288c736acbc0fb6":{
      "scriptId":"u26"},
    "57a2740e211749b5908b263cf50eb882":{
      "scriptId":"u27"},
    "b485a2fcf9c64d8286436b36db50fe8e":{
      "scriptId":"u28"},
    "a7f4a96cc1ea4756a1d8d6b868d8bb2e":{
      "scriptId":"u29"},
    "b792872fd2784438b0aa04eabb91e597":{
      "scriptId":"u30"},
    "bacfa80c55384202a2c7ad49aab2dab0":{
      "scriptId":"u31"},
    "b755a2d35ae24f90a3b40a17f0246b02":{
      "scriptId":"u32"},
    "71fcc77111824d47b340623b213245c6":{
      "scriptId":"u33"},
    "031f4c77704346a2ac04d2848d8e1750":{
      "scriptId":"u34"},
    "c6de8d71105b47ecac2888d12c3be83b":{
      "scriptId":"u35"},
    "4f041ab8cbc4462491afcb227c03ca81":{
      "scriptId":"u36"},
    "cc3c301ad0784b17a58735bebab6158b":{
      "scriptId":"u37"},
    "977b92796e0546c4981863a8bfac071f":{
      "scriptId":"u38"},
    "3a488b2a397543bea7acb9c13656cbdd":{
      "scriptId":"u39"},
    "c1fa1c4fdd4b4f188e71b32caa055305":{
      "scriptId":"u40"},
    "3ad91e6bada248099724a32c7c5e73ea":{
      "scriptId":"u41"},
    "51c2174d9f234fb58a40aa3ed140df2b":{
      "scriptId":"u42"},
    "84752e87c0e44e59803b0b5f809434cd":{
      "scriptId":"u43"},
    "3c32f0ae4ba64e6896a8d392e78559ef":{
      "scriptId":"u44"},
    "177773e4525e43f6aeec81dc2024d013":{
      "scriptId":"u45"},
    "d0bd033a79834cf4b4a3f79570e01fde":{
      "scriptId":"u46"},
    "38066c49654441428128f40133869cd7":{
      "scriptId":"u47"},
    "2d670dcdf02e4ec098445f4b2fe97785":{
      "scriptId":"u48"},
    "ff50612f0eb34d36a2d6f933eff2bbef":{
      "scriptId":"u49"},
    "6000a6d048404e3aafd507bb623513a8":{
      "scriptId":"u50"},
    "6e5087076cf343da8d35b313575ccafc":{
      "scriptId":"u51"},
    "ffd5d40a3b3b4a7fa2c2994de5e1bcb1":{
      "scriptId":"u52"},
    "86776ae42b914c89a88d1625c0cd3f1a":{
      "scriptId":"u53"},
    "958adb5b89dd47dabca948b8c5548432":{
      "scriptId":"u54"},
    "0f28e4bb5a0a44abade28b30f0f609cc":{
      "scriptId":"u55"},
    "4ad56b01783247808a6bee59dc1a58e6":{
      "scriptId":"u56"},
    "b93722ecb7fc4e73bc3c468f60e35ecd":{
      "scriptId":"u57"},
    "8445a198f1f246c89d355b67c2ed8b36":{
      "scriptId":"u58"},
    "6085d6953d8b47a8801f127b5b30ccfe":{
      "scriptId":"u59"},
    "0ab62649cec44fd6950666532736ed9e":{
      "scriptId":"u60"},
    "e41270bc3c5340c880ac33f62f93750e":{
      "scriptId":"u61"},
    "21983a98b8064497abaf66a6010f1e09":{
      "scriptId":"u62"},
    "9a0d4878fe13400aa6c4f84b450ee64b":{
      "scriptId":"u63"}}});