$axure.loadCurrentPage({
  "url":"编辑页面.html",
  "generationDate":new Date(1434534636733.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3fa00ba499394f91ba4f408a921d970d",
    "type":"Axure:Page",
    "name":"编辑页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"84c392b31eac487f9f8d95b1229c9405",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":254},
            "size":{
              "width":432,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab3efeb8f747457f9d701e07198d60a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":128,
                  "y":254},
                "size":{
                  "width":432,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c4764e6dee249f78c7157761887b9e9",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":50},
            "size":{
              "width":938,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00e947a54c934348bf313826269f5789",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "size":{
                  "width":327,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"31f745998d484f0f883ad50c85f44025",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "size":{
                      "width":327,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u1.png"}},
{
              "id":"cd83bac432c24401be853f47c6113e52",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":35},
                "size":{
                  "width":327,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"be2da328658c45b3b676047bb490a1dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":35},
                    "size":{
                      "width":327,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u11.png"}},
{
              "id":"d72801eef9884297aa2b429bf9269bfd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":65},
                "size":{
                  "width":327,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75a58537678e4abaad99beb61aa12b99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":65},
                    "size":{
                      "width":327,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u11.png"}},
{
              "id":"8156e6996a0f49b990eb175fd65656aa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":611,
                  "y":0},
                "size":{
                  "width":172,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab09fd53cc2e4163acf028f8d52cc4fe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":611,
                      "y":0},
                    "size":{
                      "width":172,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u7.png"}},
{
              "id":"93d39f67de824cd3ac42415e680577ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":611,
                  "y":35},
                "size":{
                  "width":172,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b4ff302eb964cac92aa5b4be657d54a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":611,
                      "y":35},
                    "size":{
                      "width":172,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u17.png"}},
{
              "id":"064c904b9513493a84561fa45745dcb5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":611,
                  "y":65},
                "size":{
                  "width":172,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"475b06dbabc74466a4520876bd2793e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":611,
                      "y":65},
                    "size":{
                      "width":172,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u17.png"}},
{
              "id":"ec1e39a319a34d24acb9a4b80881a1b1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":783,
                  "y":0},
                "size":{
                  "width":155,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d949113fbbb54272bc942f2af13b7d79",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":783,
                      "y":0},
                    "size":{
                      "width":155,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u9.png"}},
{
              "id":"b7eb1f7b56b141df802c1dc407aafc41",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":35},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3b12465cc7b472f9d2d14feef4e7a19",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":783,
                      "y":35},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u19.png"}},
{
              "id":"eb2f27a358d147bc8b8e669a824f43fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":65},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0d603117c3d546828ffb73b9137b72cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":783,
                      "y":65},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u19.png"}},
{
              "id":"d81bbca6129e49e0a7e9fea8f2e53eb7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":327,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fdf37f8bdd2640a18cd8d8cf05f84d49",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":95},
                    "size":{
                      "width":327,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u11.png"}},
{
              "id":"6d13edfeea4745a7973835f3347ec733",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":611,
                  "y":95},
                "size":{
                  "width":172,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7675373991045a088780e3ba3d4991a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":611,
                      "y":95},
                    "size":{
                      "width":172,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u17.png"}},
{
              "id":"24b739ebe1274805a7f920c1695d993b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":95},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"928a852d62fe47aab312e09fd9261e44",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":783,
                      "y":95},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u19.png"}},
{
              "id":"5ff1545088ec4ef69805ad83786a096e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":125},
                "size":{
                  "width":327,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ccd81ba93a44900b7f1e3f96ffd5533",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":125},
                    "size":{
                      "width":327,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u41.png"}},
{
              "id":"a0f073182c4d4062975a639a38788c8d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":611,
                  "y":125},
                "size":{
                  "width":172,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"916f8b3fc5894ddeb67d467185d03e92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":611,
                      "y":125},
                    "size":{
                      "width":172,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u47.png"}},
{
              "id":"392ab2972777477481f85fc3c193c7be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":125},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61155c3a72ee40d9aeec46c2437dec71",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":783,
                      "y":125},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u49.png"}},
{
              "id":"6419e2cf99ec48c8819f3d0e91ed353f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":327,
                  "y":0},
                "size":{
                  "width":149,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85dc2d7719364e67b68b9fbed20b08e1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":327,
                      "y":0},
                    "size":{
                      "width":149,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u3.png"}},
{
              "id":"78978bf37fe04b5a967d48d862a51ef8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":327,
                  "y":35},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a8c233bb8134102a026186fe1113507",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":327,
                      "y":35},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u13.png"}},
{
              "id":"49e9687a688a4e09a2ecbd4bf5b02054",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":327,
                  "y":65},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8776bfdaee934ea2ab6be7808acfbf24",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":327,
                      "y":65},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u13.png"}},
{
              "id":"2dd292fa28774204b3943403bf49ef9f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":327,
                  "y":95},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0edcd04ea8a94f2f874304c2c0a0827a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":327,
                      "y":95},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u13.png"}},
{
              "id":"c205fe51ebbd4ccaa2dcb46f1a1961bb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":327,
                  "y":125},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"26ec74febba04b659df9a08e97340c93",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":327,
                      "y":125},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u43.png"}},
{
              "id":"745f34a197e540c4a4040728c544abcc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":476,
                  "y":0},
                "size":{
                  "width":135,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9a2738d48530428fa7cbf5a6e1e8b6b6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":476,
                      "y":0},
                    "size":{
                      "width":135,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/办公用品库/u5.png"}},
{
              "id":"9242fea0a9ba492681cd74692a46c4a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":35},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"071f50232ef248d2be85d15ba76aa78b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":35},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u23.png"}},
{
              "id":"0e158087f82b4ec19a28b417d5a9ffe2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":65},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ec2509c3c914868a8588dd57f335d84",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":65},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u23.png"}},
{
              "id":"25485a193f404276bbe5a3129638d37f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":95},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"26383d09c5c943b2bf904f245ad04f1c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":95},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u23.png"}},
{
              "id":"66eb073cd0b64724a6e85f1e4b6da0de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":125},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1d0ca36a69641f8a6b6f46bcdcdf9b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":125},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u103.png"}}]},
{
          "id":"3a74454efdec48249b7f02f1dcb0cb3d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":15},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b07032fcd71d436ba243e2cd646f161b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":55},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d9a2eedf32154f368a3fa1245c972e67",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":90},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e66bc7c791294ff08d281502b032b08b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":119},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7739dd23037149a7ad7df8c66d0d6eb6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":149},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"598f33b324664cd78aaf4e711b7e5e37",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":178},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "84c392b31eac487f9f8d95b1229c9405":{
      "scriptId":"u0"},
    "ab3efeb8f747457f9d701e07198d60a4":{
      "scriptId":"u1"},
    "1c4764e6dee249f78c7157761887b9e9":{
      "scriptId":"u2"},
    "00e947a54c934348bf313826269f5789":{
      "scriptId":"u3"},
    "31f745998d484f0f883ad50c85f44025":{
      "scriptId":"u4"},
    "6419e2cf99ec48c8819f3d0e91ed353f":{
      "scriptId":"u5"},
    "85dc2d7719364e67b68b9fbed20b08e1":{
      "scriptId":"u6"},
    "745f34a197e540c4a4040728c544abcc":{
      "scriptId":"u7"},
    "9a2738d48530428fa7cbf5a6e1e8b6b6":{
      "scriptId":"u8"},
    "8156e6996a0f49b990eb175fd65656aa":{
      "scriptId":"u9"},
    "ab09fd53cc2e4163acf028f8d52cc4fe":{
      "scriptId":"u10"},
    "ec1e39a319a34d24acb9a4b80881a1b1":{
      "scriptId":"u11"},
    "d949113fbbb54272bc942f2af13b7d79":{
      "scriptId":"u12"},
    "cd83bac432c24401be853f47c6113e52":{
      "scriptId":"u13"},
    "be2da328658c45b3b676047bb490a1dc":{
      "scriptId":"u14"},
    "78978bf37fe04b5a967d48d862a51ef8":{
      "scriptId":"u15"},
    "0a8c233bb8134102a026186fe1113507":{
      "scriptId":"u16"},
    "9242fea0a9ba492681cd74692a46c4a2":{
      "scriptId":"u17"},
    "071f50232ef248d2be85d15ba76aa78b":{
      "scriptId":"u18"},
    "93d39f67de824cd3ac42415e680577ee":{
      "scriptId":"u19"},
    "3b4ff302eb964cac92aa5b4be657d54a":{
      "scriptId":"u20"},
    "b7eb1f7b56b141df802c1dc407aafc41":{
      "scriptId":"u21"},
    "e3b12465cc7b472f9d2d14feef4e7a19":{
      "scriptId":"u22"},
    "d72801eef9884297aa2b429bf9269bfd":{
      "scriptId":"u23"},
    "75a58537678e4abaad99beb61aa12b99":{
      "scriptId":"u24"},
    "49e9687a688a4e09a2ecbd4bf5b02054":{
      "scriptId":"u25"},
    "8776bfdaee934ea2ab6be7808acfbf24":{
      "scriptId":"u26"},
    "0e158087f82b4ec19a28b417d5a9ffe2":{
      "scriptId":"u27"},
    "9ec2509c3c914868a8588dd57f335d84":{
      "scriptId":"u28"},
    "064c904b9513493a84561fa45745dcb5":{
      "scriptId":"u29"},
    "475b06dbabc74466a4520876bd2793e2":{
      "scriptId":"u30"},
    "eb2f27a358d147bc8b8e669a824f43fe":{
      "scriptId":"u31"},
    "0d603117c3d546828ffb73b9137b72cd":{
      "scriptId":"u32"},
    "d81bbca6129e49e0a7e9fea8f2e53eb7":{
      "scriptId":"u33"},
    "fdf37f8bdd2640a18cd8d8cf05f84d49":{
      "scriptId":"u34"},
    "2dd292fa28774204b3943403bf49ef9f":{
      "scriptId":"u35"},
    "0edcd04ea8a94f2f874304c2c0a0827a":{
      "scriptId":"u36"},
    "25485a193f404276bbe5a3129638d37f":{
      "scriptId":"u37"},
    "26383d09c5c943b2bf904f245ad04f1c":{
      "scriptId":"u38"},
    "6d13edfeea4745a7973835f3347ec733":{
      "scriptId":"u39"},
    "c7675373991045a088780e3ba3d4991a":{
      "scriptId":"u40"},
    "24b739ebe1274805a7f920c1695d993b":{
      "scriptId":"u41"},
    "928a852d62fe47aab312e09fd9261e44":{
      "scriptId":"u42"},
    "5ff1545088ec4ef69805ad83786a096e":{
      "scriptId":"u43"},
    "2ccd81ba93a44900b7f1e3f96ffd5533":{
      "scriptId":"u44"},
    "c205fe51ebbd4ccaa2dcb46f1a1961bb":{
      "scriptId":"u45"},
    "26ec74febba04b659df9a08e97340c93":{
      "scriptId":"u46"},
    "66eb073cd0b64724a6e85f1e4b6da0de":{
      "scriptId":"u47"},
    "b1d0ca36a69641f8a6b6f46bcdcdf9b7":{
      "scriptId":"u48"},
    "a0f073182c4d4062975a639a38788c8d":{
      "scriptId":"u49"},
    "916f8b3fc5894ddeb67d467185d03e92":{
      "scriptId":"u50"},
    "392ab2972777477481f85fc3c193c7be":{
      "scriptId":"u51"},
    "61155c3a72ee40d9aeec46c2437dec71":{
      "scriptId":"u52"},
    "3a74454efdec48249b7f02f1dcb0cb3d":{
      "scriptId":"u53"},
    "b07032fcd71d436ba243e2cd646f161b":{
      "scriptId":"u54"},
    "d9a2eedf32154f368a3fa1245c972e67":{
      "scriptId":"u55"},
    "e66bc7c791294ff08d281502b032b08b":{
      "scriptId":"u56"},
    "7739dd23037149a7ad7df8c66d0d6eb6":{
      "scriptId":"u57"},
    "598f33b324664cd78aaf4e711b7e5e37":{
      "scriptId":"u58"}}});