$axure.loadCurrentPage({
  "url":"回帖.html",
  "generationDate":new Date(1434534637495.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e72e4959519b43b7973a5ed8196fcab0",
    "type":"Axure:Page",
    "name":"回帖",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"19c9ae74f07843aa837921bb229ab12a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":80},
            "size":{
              "width":860,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/回帖/u0_line.png"}},
{
          "id":"0e6100256733497b84d8d83b3d16ba8c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":474,
              "y":28},
            "size":{
              "width":20,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"56cd11ee61ed4d7d90c8da2b17a77e0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333399,
              "opacity":1},
            "location":{
              "x":146,
              "y":28},
            "size":{
              "width":490,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2509d736f9240baacdf88fd97a01734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333399,
                  "opacity":1},
                "location":{
                  "x":146,
                  "y":28},
                "size":{
                  "width":490,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66f2571734f1439aae41d37c316033d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":28},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f0c385a0239474aaae8732933535eec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":28},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/回帖/u4.png"}},
{
          "id":"0d7c47be59af4bc2a0c546f0c1c99260",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":152,
              "y":57},
            "size":{
              "width":358,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"970b42e54d214d9a9f82869607b94f57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":57},
                "size":{
                  "width":358,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49647a07c2194db8b3231b2a3a4140d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":802,
              "y":31},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fde6c9e509c04b41b1eac9b432ef8745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":802,
                  "y":31},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98510d1723cc40c4aa6e0fbc1d5d2b72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":831,
              "y":57},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39c077b1c2124d88af124c8c49bfbe7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":831,
                  "y":57},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c029bdc949d347c58704cf95eb345206",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":140},
            "size":{
              "width":860,
              "height":270}},
          "adaptiveStyles":{
}},
{
          "id":"8f908c17e6a74cf7bc9e969574d93fe8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":114},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c8447cce54b48fab112cbbe796e07ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":114},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62d35397738b4992bf523069eb0ef9d7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":440},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d1570cc3b2ad4876a45522d785a92966",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":366,
              "y":440},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "19c9ae74f07843aa837921bb229ab12a":{
      "scriptId":"u0"},
    "0e6100256733497b84d8d83b3d16ba8c":{
      "scriptId":"u1"},
    "56cd11ee61ed4d7d90c8da2b17a77e0b":{
      "scriptId":"u2"},
    "d2509d736f9240baacdf88fd97a01734":{
      "scriptId":"u3"},
    "66f2571734f1439aae41d37c316033d4":{
      "scriptId":"u4"},
    "6f0c385a0239474aaae8732933535eec":{
      "scriptId":"u5"},
    "0d7c47be59af4bc2a0c546f0c1c99260":{
      "scriptId":"u6"},
    "970b42e54d214d9a9f82869607b94f57":{
      "scriptId":"u7"},
    "49647a07c2194db8b3231b2a3a4140d5":{
      "scriptId":"u8"},
    "fde6c9e509c04b41b1eac9b432ef8745":{
      "scriptId":"u9"},
    "98510d1723cc40c4aa6e0fbc1d5d2b72":{
      "scriptId":"u10"},
    "39c077b1c2124d88af124c8c49bfbe7e":{
      "scriptId":"u11"},
    "c029bdc949d347c58704cf95eb345206":{
      "scriptId":"u12"},
    "8f908c17e6a74cf7bc9e969574d93fe8":{
      "scriptId":"u13"},
    "4c8447cce54b48fab112cbbe796e07ea":{
      "scriptId":"u14"},
    "62d35397738b4992bf523069eb0ef9d7":{
      "scriptId":"u15"},
    "d1570cc3b2ad4876a45522d785a92966":{
      "scriptId":"u16"}}});