package com.justonetech.biz.utils.webService.jdrwsWebService.bean;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-06-20T09:07:45.733+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", name = "JdrwsService")
@XmlSeeAlso({ObjectFactory.class})
public interface JdrwsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJdrwsBhByLastTime", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsBhByLastTime")
    @WebMethod
    @ResponseWrapper(localName = "getJdrwsBhByLastTimeResponse", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsBhByLastTimeResponse")
    public java.util.List<java.lang.String> getJdrwsBhByLastTime(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJdrwsBhByLastId", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsBhByLastId")
    @WebMethod
    @ResponseWrapper(localName = "getJdrwsBhByLastIdResponse", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsBhByLastIdResponse")
    public java.util.List<java.lang.String> getJdrwsBhByLastId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJdrwsCountByLastTime", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsCountByLastTime")
    @WebMethod
    @ResponseWrapper(localName = "getJdrwsCountByLastTimeResponse", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsCountByLastTimeResponse")
    public int getJdrwsCountByLastTime(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJdrwsByBjbh", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsByBjbh")
    @WebMethod
    @ResponseWrapper(localName = "getJdrwsByBjbhResponse", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsByBjbhResponse")
    public java.util.List<com.justonetech.biz.utils.webService.jdrwsWebService.bean.Jdrws> getJdrwsByBjbh(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJdrwsCountByLastId", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsCountByLastId")
    @WebMethod
    @ResponseWrapper(localName = "getJdrwsCountByLastIdResponse", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsCountByLastIdResponse")
    public int getJdrwsCountByLastId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJdrwsByJdrwsbh", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsByJdrwsbh")
    @WebMethod
    @ResponseWrapper(localName = "getJdrwsByJdrwsbhResponse", targetNamespace = "http://jdrwsWebService.webService.utils.biz.justonetech.com/", className = "com.justonetech.biz.utils.webService.jdrwsWebService.bean.GetJdrwsByJdrwsbhResponse")
    public com.justonetech.biz.utils.webService.jdrwsWebService.bean.Jdrws getJdrwsByJdrwsbh(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
