/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.oa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DeptWork service. Represents a row in the &quot;oa_DeptWork&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.justonetech.oa.model.impl.DeptWorkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.justonetech.oa.model.impl.DeptWorkImpl}.
 * </p>
 *
 * @author justonetech
 * @see DeptWork
 * @see com.justonetech.oa.model.impl.DeptWorkImpl
 * @see com.justonetech.oa.model.impl.DeptWorkModelImpl
 * @generated
 */
public interface DeptWorkModel extends BaseModel<DeptWork> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dept work model instance should use the {@link DeptWork} interface instead.
	 */

	/**
	 * Returns the primary key of this dept work.
	 *
	 * @return the primary key of this dept work
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dept work.
	 *
	 * @param primaryKey the primary key of this dept work
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dept work ID of this dept work.
	 *
	 * @return the dept work ID of this dept work
	 */
	public long getDeptWorkId();

	/**
	 * Sets the dept work ID of this dept work.
	 *
	 * @param deptWorkId the dept work ID of this dept work
	 */
	public void setDeptWorkId(long deptWorkId);

	/**
	 * Returns the group ID of this dept work.
	 *
	 * @return the group ID of this dept work
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dept work.
	 *
	 * @param groupId the group ID of this dept work
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dept work.
	 *
	 * @return the company ID of this dept work
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dept work.
	 *
	 * @param companyId the company ID of this dept work
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dept work.
	 *
	 * @return the user ID of this dept work
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dept work.
	 *
	 * @param userId the user ID of this dept work
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dept work.
	 *
	 * @return the user uuid of this dept work
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dept work.
	 *
	 * @param userUuid the user uuid of this dept work
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dept work.
	 *
	 * @return the user name of this dept work
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this dept work.
	 *
	 * @param userName the user name of this dept work
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create time of this dept work.
	 *
	 * @return the create time of this dept work
	 */
	public Date getCreateTime();

	/**
	 * Sets the create time of this dept work.
	 *
	 * @param createTime the create time of this dept work
	 */
	public void setCreateTime(Date createTime);

	/**
	 * Returns the modified time of this dept work.
	 *
	 * @return the modified time of this dept work
	 */
	public Date getModifiedTime();

	/**
	 * Sets the modified time of this dept work.
	 *
	 * @param modifiedTime the modified time of this dept work
	 */
	public void setModifiedTime(Date modifiedTime);

	/**
	 * Returns the dept ID of this dept work.
	 *
	 * @return the dept ID of this dept work
	 */
	public long getDeptId();

	/**
	 * Sets the dept ID of this dept work.
	 *
	 * @param deptId the dept ID of this dept work
	 */
	public void setDeptId(long deptId);

	/**
	 * Returns the dept name of this dept work.
	 *
	 * @return the dept name of this dept work
	 */
	@AutoEscape
	public String getDeptName();

	/**
	 * Sets the dept name of this dept work.
	 *
	 * @param deptName the dept name of this dept work
	 */
	public void setDeptName(String deptName);

	/**
	 * Returns the start date of this dept work.
	 *
	 * @return the start date of this dept work
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this dept work.
	 *
	 * @param startDate the start date of this dept work
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this dept work.
	 *
	 * @return the end date of this dept work
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this dept work.
	 *
	 * @param endDate the end date of this dept work
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the status of this dept work.
	 *
	 * @return the status of this dept work
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this dept work.
	 *
	 * @param status the status of this dept work
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.justonetech.oa.model.DeptWork deptWork);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.justonetech.oa.model.DeptWork> toCacheModel();

	@Override
	public com.justonetech.oa.model.DeptWork toEscapedModel();

	@Override
	public com.justonetech.oa.model.DeptWork toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}