/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.oa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the OfficeSupplyApplicationItem service. Represents a row in the &quot;oa_OfficeSupplyApplicationItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.justonetech.oa.model.impl.OfficeSupplyApplicationItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.justonetech.oa.model.impl.OfficeSupplyApplicationItemImpl}.
 * </p>
 *
 * @author justonetech
 * @see OfficeSupplyApplicationItem
 * @see com.justonetech.oa.model.impl.OfficeSupplyApplicationItemImpl
 * @see com.justonetech.oa.model.impl.OfficeSupplyApplicationItemModelImpl
 * @generated
 */
public interface OfficeSupplyApplicationItemModel extends BaseModel<OfficeSupplyApplicationItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a office supply application item model instance should use the {@link OfficeSupplyApplicationItem} interface instead.
	 */

	/**
	 * Returns the primary key of this office supply application item.
	 *
	 * @return the primary key of this office supply application item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this office supply application item.
	 *
	 * @param primaryKey the primary key of this office supply application item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the office supply application item ID of this office supply application item.
	 *
	 * @return the office supply application item ID of this office supply application item
	 */
	public long getOfficeSupplyApplicationItemId();

	/**
	 * Sets the office supply application item ID of this office supply application item.
	 *
	 * @param officeSupplyApplicationItemId the office supply application item ID of this office supply application item
	 */
	public void setOfficeSupplyApplicationItemId(
		long officeSupplyApplicationItemId);

	/**
	 * Returns the name of this office supply application item.
	 *
	 * @return the name of this office supply application item
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this office supply application item.
	 *
	 * @param name the name of this office supply application item
	 */
	public void setName(String name);

	/**
	 * Returns the model of this office supply application item.
	 *
	 * @return the model of this office supply application item
	 */
	@AutoEscape
	public String getModel();

	/**
	 * Sets the model of this office supply application item.
	 *
	 * @param model the model of this office supply application item
	 */
	public void setModel(String model);

	/**
	 * Returns the unit of this office supply application item.
	 *
	 * @return the unit of this office supply application item
	 */
	@AutoEscape
	public String getUnit();

	/**
	 * Sets the unit of this office supply application item.
	 *
	 * @param unit the unit of this office supply application item
	 */
	public void setUnit(String unit);

	/**
	 * Returns the unit price of this office supply application item.
	 *
	 * @return the unit price of this office supply application item
	 */
	public double getUnitPrice();

	/**
	 * Sets the unit price of this office supply application item.
	 *
	 * @param unitPrice the unit price of this office supply application item
	 */
	public void setUnitPrice(double unitPrice);

	/**
	 * Returns the quantity of this office supply application item.
	 *
	 * @return the quantity of this office supply application item
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this office supply application item.
	 *
	 * @param quantity the quantity of this office supply application item
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the office supply application ID of this office supply application item.
	 *
	 * @return the office supply application ID of this office supply application item
	 */
	public long getOfficeSupplyApplicationId();

	/**
	 * Sets the office supply application ID of this office supply application item.
	 *
	 * @param officeSupplyApplicationId the office supply application ID of this office supply application item
	 */
	public void setOfficeSupplyApplicationId(long officeSupplyApplicationId);

	/**
	 * Returns the office supply ID of this office supply application item.
	 *
	 * @return the office supply ID of this office supply application item
	 */
	public long getOfficeSupplyId();

	/**
	 * Sets the office supply ID of this office supply application item.
	 *
	 * @param officeSupplyId the office supply ID of this office supply application item
	 */
	public void setOfficeSupplyId(long officeSupplyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.justonetech.oa.model.OfficeSupplyApplicationItem officeSupplyApplicationItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.justonetech.oa.model.OfficeSupplyApplicationItem> toCacheModel();

	@Override
	public com.justonetech.oa.model.OfficeSupplyApplicationItem toEscapedModel();

	@Override
	public com.justonetech.oa.model.OfficeSupplyApplicationItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}