/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.oa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OfficeSupplyApplication service. Represents a row in the &quot;oa_OfficeSupplyApplication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.justonetech.oa.model.impl.OfficeSupplyApplicationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.justonetech.oa.model.impl.OfficeSupplyApplicationImpl}.
 * </p>
 *
 * @author justonetech
 * @see OfficeSupplyApplication
 * @see com.justonetech.oa.model.impl.OfficeSupplyApplicationImpl
 * @see com.justonetech.oa.model.impl.OfficeSupplyApplicationModelImpl
 * @generated
 */
public interface OfficeSupplyApplicationModel extends BaseModel<OfficeSupplyApplication>,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a office supply application model instance should use the {@link OfficeSupplyApplication} interface instead.
	 */

	/**
	 * Returns the primary key of this office supply application.
	 *
	 * @return the primary key of this office supply application
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this office supply application.
	 *
	 * @param primaryKey the primary key of this office supply application
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the office supply application ID of this office supply application.
	 *
	 * @return the office supply application ID of this office supply application
	 */
	public long getOfficeSupplyApplicationId();

	/**
	 * Sets the office supply application ID of this office supply application.
	 *
	 * @param officeSupplyApplicationId the office supply application ID of this office supply application
	 */
	public void setOfficeSupplyApplicationId(long officeSupplyApplicationId);

	/**
	 * Returns the group ID of this office supply application.
	 *
	 * @return the group ID of this office supply application
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this office supply application.
	 *
	 * @param groupId the group ID of this office supply application
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this office supply application.
	 *
	 * @return the company ID of this office supply application
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this office supply application.
	 *
	 * @param companyId the company ID of this office supply application
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this office supply application.
	 *
	 * @return the user ID of this office supply application
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this office supply application.
	 *
	 * @param userId the user ID of this office supply application
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this office supply application.
	 *
	 * @return the user uuid of this office supply application
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this office supply application.
	 *
	 * @param userUuid the user uuid of this office supply application
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this office supply application.
	 *
	 * @return the user name of this office supply application
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this office supply application.
	 *
	 * @param userName the user name of this office supply application
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create time of this office supply application.
	 *
	 * @return the create time of this office supply application
	 */
	public Date getCreateTime();

	/**
	 * Sets the create time of this office supply application.
	 *
	 * @param createTime the create time of this office supply application
	 */
	public void setCreateTime(Date createTime);

	/**
	 * Returns the modified time of this office supply application.
	 *
	 * @return the modified time of this office supply application
	 */
	public Date getModifiedTime();

	/**
	 * Sets the modified time of this office supply application.
	 *
	 * @param modifiedTime the modified time of this office supply application
	 */
	public void setModifiedTime(Date modifiedTime);

	/**
	 * Returns the dept ID of this office supply application.
	 *
	 * @return the dept ID of this office supply application
	 */
	public long getDeptId();

	/**
	 * Sets the dept ID of this office supply application.
	 *
	 * @param deptId the dept ID of this office supply application
	 */
	public void setDeptId(long deptId);

	/**
	 * Returns the dept name of this office supply application.
	 *
	 * @return the dept name of this office supply application
	 */
	@AutoEscape
	public String getDeptName();

	/**
	 * Sets the dept name of this office supply application.
	 *
	 * @param deptName the dept name of this office supply application
	 */
	public void setDeptName(String deptName);

	/**
	 * Returns the introductions of this office supply application.
	 *
	 * @return the introductions of this office supply application
	 */
	@AutoEscape
	public String getIntroductions();

	/**
	 * Sets the introductions of this office supply application.
	 *
	 * @param introductions the introductions of this office supply application
	 */
	public void setIntroductions(String introductions);

	/**
	 * Returns the perpose clerk of this office supply application.
	 *
	 * @return the perpose clerk of this office supply application
	 */
	@AutoEscape
	public String getPerposeClerk();

	/**
	 * Sets the perpose clerk of this office supply application.
	 *
	 * @param perposeClerk the perpose clerk of this office supply application
	 */
	public void setPerposeClerk(String perposeClerk);

	/**
	 * Returns the title of this office supply application.
	 *
	 * @return the title of this office supply application
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this office supply application.
	 *
	 * @param title the title of this office supply application
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this office supply application.
	 *
	 * @return the content of this office supply application
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this office supply application.
	 *
	 * @param content the content of this office supply application
	 */
	public void setContent(String content);

	/**
	 * Returns the status of this office supply application.
	 *
	 * @return the status of this office supply application
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this office supply application.
	 *
	 * @param status the status of this office supply application
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this office supply application.
	 *
	 * @return the status by user ID of this office supply application
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this office supply application.
	 *
	 * @param statusByUserId the status by user ID of this office supply application
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this office supply application.
	 *
	 * @return the status by user uuid of this office supply application
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this office supply application.
	 *
	 * @param statusByUserUuid the status by user uuid of this office supply application
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this office supply application.
	 *
	 * @return the status by user name of this office supply application
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this office supply application.
	 *
	 * @param statusByUserName the status by user name of this office supply application
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this office supply application.
	 *
	 * @return the status date of this office supply application
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this office supply application.
	 *
	 * @param statusDate the status date of this office supply application
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this office supply application is approved.
	 *
	 * @return <code>true</code> if this office supply application is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this office supply application is denied.
	 *
	 * @return <code>true</code> if this office supply application is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this office supply application is a draft.
	 *
	 * @return <code>true</code> if this office supply application is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this office supply application is expired.
	 *
	 * @return <code>true</code> if this office supply application is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this office supply application is inactive.
	 *
	 * @return <code>true</code> if this office supply application is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this office supply application is incomplete.
	 *
	 * @return <code>true</code> if this office supply application is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this office supply application is pending.
	 *
	 * @return <code>true</code> if this office supply application is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this office supply application is scheduled.
	 *
	 * @return <code>true</code> if this office supply application is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.justonetech.oa.model.OfficeSupplyApplication officeSupplyApplication);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.justonetech.oa.model.OfficeSupplyApplication> toCacheModel();

	@Override
	public com.justonetech.oa.model.OfficeSupplyApplication toEscapedModel();

	@Override
	public com.justonetech.oa.model.OfficeSupplyApplication toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}