/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.cp.permit.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ApplyMaterial service. Represents a row in the &quot;cp_ApplyMaterial&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.justonetech.cp.permit.model.impl.ApplyMaterialModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.justonetech.cp.permit.model.impl.ApplyMaterialImpl}.
 * </p>
 *
 * @author fanqi
 * @see ApplyMaterial
 * @see com.justonetech.cp.permit.model.impl.ApplyMaterialImpl
 * @see com.justonetech.cp.permit.model.impl.ApplyMaterialModelImpl
 * @generated
 */
public interface ApplyMaterialModel extends BaseModel<ApplyMaterial> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a apply material model instance should use the {@link ApplyMaterial} interface instead.
	 */

	/**
	 * Returns the primary key of this apply material.
	 *
	 * @return the primary key of this apply material
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this apply material.
	 *
	 * @param primaryKey the primary key of this apply material
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the material ID of this apply material.
	 *
	 * @return the material ID of this apply material
	 */
	public long getMaterialId();

	/**
	 * Sets the material ID of this apply material.
	 *
	 * @param materialId the material ID of this apply material
	 */
	public void setMaterialId(long materialId);

	/**
	 * Returns the permit ID of this apply material.
	 *
	 * @return the permit ID of this apply material
	 */
	public long getPermitId();

	/**
	 * Sets the permit ID of this apply material.
	 *
	 * @param permitId the permit ID of this apply material
	 */
	public void setPermitId(long permitId);

	/**
	 * Returns the xh of this apply material.
	 *
	 * @return the xh of this apply material
	 */
	@AutoEscape
	public String getXh();

	/**
	 * Sets the xh of this apply material.
	 *
	 * @param xh the xh of this apply material
	 */
	public void setXh(String xh);

	/**
	 * Returns the clmc of this apply material.
	 *
	 * @return the clmc of this apply material
	 */
	@AutoEscape
	public String getClmc();

	/**
	 * Sets the clmc of this apply material.
	 *
	 * @param clmc the clmc of this apply material
	 */
	public void setClmc(String clmc);

	/**
	 * Returns the yjfs of this apply material.
	 *
	 * @return the yjfs of this apply material
	 */
	public int getYjfs();

	/**
	 * Sets the yjfs of this apply material.
	 *
	 * @param yjfs the yjfs of this apply material
	 */
	public void setYjfs(int yjfs);

	/**
	 * Returns the sjfs of this apply material.
	 *
	 * @return the sjfs of this apply material
	 */
	public int getSjfs();

	/**
	 * Sets the sjfs of this apply material.
	 *
	 * @param sjfs the sjfs of this apply material
	 */
	public void setSjfs(int sjfs);

	/**
	 * Returns the file entry IDs of this apply material.
	 *
	 * @return the file entry IDs of this apply material
	 */
	@AutoEscape
	public String getFileEntryIds();

	/**
	 * Sets the file entry IDs of this apply material.
	 *
	 * @param fileEntryIds the file entry IDs of this apply material
	 */
	public void setFileEntryIds(String fileEntryIds);

	/**
	 * Returns the bzcl IDs of this apply material.
	 *
	 * @return the bzcl IDs of this apply material
	 */
	@AutoEscape
	public String getBzclIds();

	/**
	 * Sets the bzcl IDs of this apply material.
	 *
	 * @param bzclIds the bzcl IDs of this apply material
	 */
	public void setBzclIds(String bzclIds);

	/**
	 * Returns the wjscbzcl IDs of this apply material.
	 *
	 * @return the wjscbzcl IDs of this apply material
	 */
	@AutoEscape
	public String getWjscbzclIds();

	/**
	 * Sets the wjscbzcl IDs of this apply material.
	 *
	 * @param wjscbzclIds the wjscbzcl IDs of this apply material
	 */
	public void setWjscbzclIds(String wjscbzclIds);

	/**
	 * Returns the shyq of this apply material.
	 *
	 * @return the shyq of this apply material
	 */
	@AutoEscape
	public String getShyq();

	/**
	 * Sets the shyq of this apply material.
	 *
	 * @param shyq the shyq of this apply material
	 */
	public void setShyq(String shyq);

	/**
	 * Returns the csyj of this apply material.
	 *
	 * @return the csyj of this apply material
	 */
	@AutoEscape
	public String getCsyj();

	/**
	 * Sets the csyj of this apply material.
	 *
	 * @param csyj the csyj of this apply material
	 */
	public void setCsyj(String csyj);

	/**
	 * Returns the fhyj of this apply material.
	 *
	 * @return the fhyj of this apply material
	 */
	@AutoEscape
	public String getFhyj();

	/**
	 * Sets the fhyj of this apply material.
	 *
	 * @param fhyj the fhyj of this apply material
	 */
	public void setFhyj(String fhyj);

	/**
	 * Returns the shyj of this apply material.
	 *
	 * @return the shyj of this apply material
	 */
	@AutoEscape
	public String getShyj();

	/**
	 * Sets the shyj of this apply material.
	 *
	 * @param shyj the shyj of this apply material
	 */
	public void setShyj(String shyj);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.justonetech.cp.permit.model.ApplyMaterial applyMaterial);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.justonetech.cp.permit.model.ApplyMaterial> toCacheModel();

	@Override
	public com.justonetech.cp.permit.model.ApplyMaterial toEscapedModel();

	@Override
	public com.justonetech.cp.permit.model.ApplyMaterial toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}