/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.cp.complete.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Complete service. Represents a row in the &quot;cp_Complete&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.justonetech.cp.complete.model.impl.CompleteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.justonetech.cp.complete.model.impl.CompleteImpl}.
 * </p>
 *
 * @author fanqi
 * @see Complete
 * @see com.justonetech.cp.complete.model.impl.CompleteImpl
 * @see com.justonetech.cp.complete.model.impl.CompleteModelImpl
 * @generated
 */
public interface CompleteModel extends BaseModel<Complete>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a complete model instance should use the {@link Complete} interface instead.
	 */

	/**
	 * Returns the primary key of this complete.
	 *
	 * @return the primary key of this complete
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this complete.
	 *
	 * @param primaryKey the primary key of this complete
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the complete ID of this complete.
	 *
	 * @return the complete ID of this complete
	 */
	public long getCompleteId();

	/**
	 * Sets the complete ID of this complete.
	 *
	 * @param completeId the complete ID of this complete
	 */
	public void setCompleteId(long completeId);

	/**
	 * Returns the group ID of this complete.
	 *
	 * @return the group ID of this complete
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this complete.
	 *
	 * @param groupId the group ID of this complete
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this complete.
	 *
	 * @return the company ID of this complete
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this complete.
	 *
	 * @param companyId the company ID of this complete
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this complete.
	 *
	 * @return the user ID of this complete
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this complete.
	 *
	 * @param userId the user ID of this complete
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this complete.
	 *
	 * @return the user uuid of this complete
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this complete.
	 *
	 * @param userUuid the user uuid of this complete
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this complete.
	 *
	 * @return the user name of this complete
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this complete.
	 *
	 * @param userName the user name of this complete
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this complete.
	 *
	 * @return the create date of this complete
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this complete.
	 *
	 * @param createDate the create date of this complete
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this complete.
	 *
	 * @return the modified date of this complete
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this complete.
	 *
	 * @param modifiedDate the modified date of this complete
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the zzjgdm of this complete.
	 *
	 * @return the zzjgdm of this complete
	 */
	@AutoEscape
	public String getZzjgdm();

	/**
	 * Sets the zzjgdm of this complete.
	 *
	 * @param zzjgdm the zzjgdm of this complete
	 */
	public void setZzjgdm(String zzjgdm);

	/**
	 * Returns the bjbh of this complete.
	 *
	 * @return the bjbh of this complete
	 */
	@AutoEscape
	public String getBjbh();

	/**
	 * Sets the bjbh of this complete.
	 *
	 * @param bjbh the bjbh of this complete
	 */
	public void setBjbh(String bjbh);

	/**
	 * Returns the sqbz of this complete.
	 *
	 * @return the sqbz of this complete
	 */
	public int getSqbz();

	/**
	 * Sets the sqbz of this complete.
	 *
	 * @param sqbz the sqbz of this complete
	 */
	public void setSqbz(int sqbz);

	/**
	 * Returns the status of this complete.
	 *
	 * @return the status of this complete
	 */
	public int getStatus();

	/**
	 * Sets the status of this complete.
	 *
	 * @param status the status of this complete
	 */
	public void setStatus(int status);

	/**
	 * Returns the babh of this complete.
	 *
	 * @return the babh of this complete
	 */
	@AutoEscape
	public String getBabh();

	/**
	 * Sets the babh of this complete.
	 *
	 * @param babh the babh of this complete
	 */
	public void setBabh(String babh);

	/**
	 * Returns the wssqbh of this complete.
	 *
	 * @return the wssqbh of this complete
	 */
	@AutoEscape
	public String getWssqbh();

	/**
	 * Sets the wssqbh of this complete.
	 *
	 * @param wssqbh the wssqbh of this complete
	 */
	public void setWssqbh(String wssqbh);

	/**
	 * Returns the sbrq of this complete.
	 *
	 * @return the sbrq of this complete
	 */
	public Date getSbrq();

	/**
	 * Sets the sbrq of this complete.
	 *
	 * @param sbrq the sbrq of this complete
	 */
	public void setSbrq(Date sbrq);

	/**
	 * Returns the shyj of this complete.
	 *
	 * @return the shyj of this complete
	 */
	@AutoEscape
	public String getShyj();

	/**
	 * Sets the shyj of this complete.
	 *
	 * @param shyj the shyj of this complete
	 */
	public void setShyj(String shyj);

	/**
	 * Returns the shr of this complete.
	 *
	 * @return the shr of this complete
	 */
	@AutoEscape
	public String getShr();

	/**
	 * Sets the shr of this complete.
	 *
	 * @param shr the shr of this complete
	 */
	public void setShr(String shr);

	/**
	 * Returns the shrq of this complete.
	 *
	 * @return the shrq of this complete
	 */
	public Date getShrq();

	/**
	 * Sets the shrq of this complete.
	 *
	 * @param shrq the shrq of this complete
	 */
	public void setShrq(Date shrq);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.justonetech.cp.complete.model.Complete complete);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.justonetech.cp.complete.model.Complete> toCacheModel();

	@Override
	public com.justonetech.cp.complete.model.Complete toEscapedModel();

	@Override
	public com.justonetech.cp.complete.model.Complete toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}