$axure.loadCurrentPage({
  "url":"打印页面.html",
  "generationDate":new Date(1434534636296.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9da9cb6ddb8540039b32140ffb4832fc",
    "type":"Axure:Page",
    "name":"打印页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"650021d1ac5643fabbe6d1feaa7386e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":-40},
            "size":{
              "width":470,
              "height":622}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efda18fd28164f54a437787f51bb2c83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":-40},
                "size":{
                  "width":470,
                  "height":622}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打印页面/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "650021d1ac5643fabbe6d1feaa7386e2":{
      "scriptId":"u0"},
    "efda18fd28164f54a437787f51bb2c83":{
      "scriptId":"u1"}}});