/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.cp.permit.model.impl;

import com.justonetech.cp.permit.model.ProjectProfile;
import com.justonetech.cp.permit.model.ProjectProfileModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ProjectProfile service. Represents a row in the &quot;cp_ProjectProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.justonetech.cp.permit.model.ProjectProfileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectProfileImpl}.
 * </p>
 *
 * @author fanqi
 * @see ProjectProfileImpl
 * @see com.justonetech.cp.permit.model.ProjectProfile
 * @see com.justonetech.cp.permit.model.ProjectProfileModel
 * @generated
 */
public class ProjectProfileModelImpl extends BaseModelImpl<ProjectProfile>
	implements ProjectProfileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project profile model instance should use the {@link com.justonetech.cp.permit.model.ProjectProfile} interface instead.
	 */
	public static final String TABLE_NAME = "cp_ProjectProfile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "permitId", Types.BIGINT },
			{ "bjbh", Types.VARCHAR },
			{ "jsdwmc", Types.VARCHAR },
			{ "jsdwxz", Types.VARCHAR },
			{ "jsdwdz", Types.VARCHAR },
			{ "gcmc", Types.VARCHAR },
			{ "jsdd", Types.VARCHAR },
			{ "jsgcgm", Types.VARCHAR },
			{ "fwjzmj", Types.VARCHAR },
			{ "htjg", Types.VARCHAR },
			{ "htgq", Types.INTEGER },
			{ "fddbr", Types.VARCHAR },
			{ "jsdwlxdh", Types.VARCHAR },
			{ "jsdwlxr", Types.VARCHAR },
			{ "jsdwsjh", Types.VARCHAR },
			{ "jsgcghxkzbh", Types.VARCHAR },
			{ "xckgqk", Types.VARCHAR },
			{ "xmlx", Types.BIGINT },
			{ "lxjb", Types.VARCHAR },
			{ "xmxz", Types.BIGINT },
			{ "ssqx", Types.VARCHAR },
			{ "ywbm", Types.VARCHAR },
			{ "jsddssqx", Types.BIGINT },
			{ "jsgclb", Types.VARCHAR },
			{ "jsgcsx", Types.BIGINT },
			{ "gyzjbz", Types.VARCHAR },
			{ "zbjg", Types.VARCHAR },
			{ "xmtzgs", Types.VARCHAR },
			{ "jhkg", Types.TIMESTAMP },
			{ "jhjg", Types.TIMESTAMP },
			{ "sfzftzl", Types.BOOLEAN },
			{ "yzzpl1", Types.VARCHAR },
			{ "yzzpl2", Types.VARCHAR },
			{ "yzzpl3", Types.VARCHAR },
			{ "yzzpl4", Types.VARCHAR },
			{ "tjsj", Types.TIMESTAMP },
			{ "gcnr", Types.VARCHAR },
			{ "sgxkzsbz", Types.VARCHAR },
			{ "tzly", Types.VARCHAR },
			{ "gkpzhhzjghwh", Types.VARCHAR },
			{ "pfhhzrq", Types.TIMESTAMP },
			{ "cbsjpzjghwh", Types.VARCHAR },
			{ "pfrq", Types.TIMESTAMP },
			{ "pfgq", Types.INTEGER },
			{ "pzjghwh", Types.VARCHAR },
			{ "xmdw", Types.VARCHAR },
			{ "xmfzr", Types.VARCHAR },
			{ "xmfzrlxdh", Types.VARCHAR },
			{ "zysjdw", Types.VARCHAR },
			{ "sj_zbfs", Types.VARCHAR },
			{ "sj_zbj", Types.VARCHAR },
			{ "sj_zzdj", Types.VARCHAR },
			{ "sj_zzdjzsbh", Types.VARCHAR },
			{ "sj_xmfzr", Types.VARCHAR },
			{ "sj_xmfzrzsbh", Types.VARCHAR },
			{ "zyjldw", Types.VARCHAR },
			{ "jl_zbfs", Types.VARCHAR },
			{ "jl_zbj", Types.VARCHAR },
			{ "jl_zzdj", Types.VARCHAR },
			{ "jl_zzdjzsbh", Types.VARCHAR },
			{ "jl_zj", Types.VARCHAR },
			{ "jl_zjzsbh", Types.VARCHAR },
			{ "zysgdw", Types.VARCHAR },
			{ "sg_zbfs", Types.VARCHAR },
			{ "sg_zbj", Types.VARCHAR },
			{ "sg_zzdj", Types.VARCHAR },
			{ "sg_zzdjzsbh", Types.VARCHAR },
			{ "sg_xmjl", Types.VARCHAR },
			{ "sg_xmjlzsbh", Types.VARCHAR },
			{ "jszjjhlsqk", Types.VARCHAR },
			{ "dcqwcqk", Types.VARCHAR },
			{ "sgzbqk", Types.VARCHAR },
			{ "sytdxgwj", Types.VARCHAR },
			{ "gczljddjqk", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table cp_ProjectProfile (permitId LONG not null primary key,bjbh VARCHAR(75) null,jsdwmc VARCHAR(300) null,jsdwxz VARCHAR(75) null,jsdwdz VARCHAR(300) null,gcmc VARCHAR(300) null,jsdd VARCHAR(300) null,jsgcgm VARCHAR(500) null,fwjzmj VARCHAR(75) null,htjg VARCHAR(75) null,htgq INTEGER,fddbr VARCHAR(75) null,jsdwlxdh VARCHAR(75) null,jsdwlxr VARCHAR(75) null,jsdwsjh VARCHAR(75) null,jsgcghxkzbh VARCHAR(75) null,xckgqk VARCHAR(75) null,xmlx LONG,lxjb VARCHAR(75) null,xmxz LONG,ssqx VARCHAR(75) null,ywbm VARCHAR(75) null,jsddssqx LONG,jsgclb VARCHAR(75) null,jsgcsx LONG,gyzjbz VARCHAR(75) null,zbjg VARCHAR(75) null,xmtzgs VARCHAR(75) null,jhkg DATE null,jhjg DATE null,sfzftzl BOOLEAN,yzzpl1 VARCHAR(75) null,yzzpl2 VARCHAR(75) null,yzzpl3 VARCHAR(75) null,yzzpl4 VARCHAR(75) null,tjsj DATE null,gcnr VARCHAR(100) null,sgxkzsbz VARCHAR(75) null,tzly VARCHAR(75) null,gkpzhhzjghwh VARCHAR(75) null,pfhhzrq DATE null,cbsjpzjghwh VARCHAR(75) null,pfrq DATE null,pfgq INTEGER,pzjghwh VARCHAR(75) null,xmdw VARCHAR(75) null,xmfzr VARCHAR(75) null,xmfzrlxdh VARCHAR(75) null,zysjdw VARCHAR(300) null,sj_zbfs VARCHAR(75) null,sj_zbj VARCHAR(75) null,sj_zzdj VARCHAR(75) null,sj_zzdjzsbh VARCHAR(75) null,sj_xmfzr VARCHAR(75) null,sj_xmfzrzsbh VARCHAR(75) null,zyjldw VARCHAR(300) null,jl_zbfs VARCHAR(75) null,jl_zbj VARCHAR(75) null,jl_zzdj VARCHAR(75) null,jl_zzdjzsbh VARCHAR(75) null,jl_zj VARCHAR(75) null,jl_zjzsbh VARCHAR(75) null,zysgdw VARCHAR(300) null,sg_zbfs VARCHAR(75) null,sg_zbj VARCHAR(75) null,sg_zzdj VARCHAR(75) null,sg_zzdjzsbh VARCHAR(75) null,sg_xmjl VARCHAR(75) null,sg_xmjlzsbh VARCHAR(75) null,jszjjhlsqk VARCHAR(200) null,dcqwcqk VARCHAR(200) null,sgzbqk VARCHAR(200) null,sytdxgwj VARCHAR(200) null,gczljddjqk VARCHAR(200) null)";
	public static final String TABLE_SQL_DROP = "drop table cp_ProjectProfile";
	public static final String ORDER_BY_JPQL = " ORDER BY projectProfile.permitId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY cp_ProjectProfile.permitId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.justonetech.cp.permit.model.ProjectProfile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.justonetech.cp.permit.model.ProjectProfile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.justonetech.cp.permit.model.ProjectProfile"));

	public ProjectProfileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _permitId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPermitId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _permitId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProjectProfile.class;
	}

	@Override
	public String getModelClassName() {
		return ProjectProfile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("permitId", getPermitId());
		attributes.put("bjbh", getBjbh());
		attributes.put("jsdwmc", getJsdwmc());
		attributes.put("jsdwxz", getJsdwxz());
		attributes.put("jsdwdz", getJsdwdz());
		attributes.put("gcmc", getGcmc());
		attributes.put("jsdd", getJsdd());
		attributes.put("jsgcgm", getJsgcgm());
		attributes.put("fwjzmj", getFwjzmj());
		attributes.put("htjg", getHtjg());
		attributes.put("htgq", getHtgq());
		attributes.put("fddbr", getFddbr());
		attributes.put("jsdwlxdh", getJsdwlxdh());
		attributes.put("jsdwlxr", getJsdwlxr());
		attributes.put("jsdwsjh", getJsdwsjh());
		attributes.put("jsgcghxkzbh", getJsgcghxkzbh());
		attributes.put("xckgqk", getXckgqk());
		attributes.put("xmlx", getXmlx());
		attributes.put("lxjb", getLxjb());
		attributes.put("xmxz", getXmxz());
		attributes.put("ssqx", getSsqx());
		attributes.put("ywbm", getYwbm());
		attributes.put("jsddssqx", getJsddssqx());
		attributes.put("jsgclb", getJsgclb());
		attributes.put("jsgcsx", getJsgcsx());
		attributes.put("gyzjbz", getGyzjbz());
		attributes.put("zbjg", getZbjg());
		attributes.put("xmtzgs", getXmtzgs());
		attributes.put("jhkg", getJhkg());
		attributes.put("jhjg", getJhjg());
		attributes.put("sfzftzl", getSfzftzl());
		attributes.put("yzzpl1", getYzzpl1());
		attributes.put("yzzpl2", getYzzpl2());
		attributes.put("yzzpl3", getYzzpl3());
		attributes.put("yzzpl4", getYzzpl4());
		attributes.put("tjsj", getTjsj());
		attributes.put("gcnr", getGcnr());
		attributes.put("sgxkzsbz", getSgxkzsbz());
		attributes.put("tzly", getTzly());
		attributes.put("gkpzhhzjghwh", getGkpzhhzjghwh());
		attributes.put("pfhhzrq", getPfhhzrq());
		attributes.put("cbsjpzjghwh", getCbsjpzjghwh());
		attributes.put("pfrq", getPfrq());
		attributes.put("pfgq", getPfgq());
		attributes.put("pzjghwh", getPzjghwh());
		attributes.put("xmdw", getXmdw());
		attributes.put("xmfzr", getXmfzr());
		attributes.put("xmfzrlxdh", getXmfzrlxdh());
		attributes.put("zysjdw", getZysjdw());
		attributes.put("sj_zbfs", getSj_zbfs());
		attributes.put("sj_zbj", getSj_zbj());
		attributes.put("sj_zzdj", getSj_zzdj());
		attributes.put("sj_zzdjzsbh", getSj_zzdjzsbh());
		attributes.put("sj_xmfzr", getSj_xmfzr());
		attributes.put("sj_xmfzrzsbh", getSj_xmfzrzsbh());
		attributes.put("zyjldw", getZyjldw());
		attributes.put("jl_zbfs", getJl_zbfs());
		attributes.put("jl_zbj", getJl_zbj());
		attributes.put("jl_zzdj", getJl_zzdj());
		attributes.put("jl_zzdjzsbh", getJl_zzdjzsbh());
		attributes.put("jl_zj", getJl_zj());
		attributes.put("jl_zjzsbh", getJl_zjzsbh());
		attributes.put("zysgdw", getZysgdw());
		attributes.put("sg_zbfs", getSg_zbfs());
		attributes.put("sg_zbj", getSg_zbj());
		attributes.put("sg_zzdj", getSg_zzdj());
		attributes.put("sg_zzdjzsbh", getSg_zzdjzsbh());
		attributes.put("sg_xmjl", getSg_xmjl());
		attributes.put("sg_xmjlzsbh", getSg_xmjlzsbh());
		attributes.put("jszjjhlsqk", getJszjjhlsqk());
		attributes.put("dcqwcqk", getDcqwcqk());
		attributes.put("sgzbqk", getSgzbqk());
		attributes.put("sytdxgwj", getSytdxgwj());
		attributes.put("gczljddjqk", getGczljddjqk());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long permitId = (Long)attributes.get("permitId");

		if (permitId != null) {
			setPermitId(permitId);
		}

		String bjbh = (String)attributes.get("bjbh");

		if (bjbh != null) {
			setBjbh(bjbh);
		}

		String jsdwmc = (String)attributes.get("jsdwmc");

		if (jsdwmc != null) {
			setJsdwmc(jsdwmc);
		}

		String jsdwxz = (String)attributes.get("jsdwxz");

		if (jsdwxz != null) {
			setJsdwxz(jsdwxz);
		}

		String jsdwdz = (String)attributes.get("jsdwdz");

		if (jsdwdz != null) {
			setJsdwdz(jsdwdz);
		}

		String gcmc = (String)attributes.get("gcmc");

		if (gcmc != null) {
			setGcmc(gcmc);
		}

		String jsdd = (String)attributes.get("jsdd");

		if (jsdd != null) {
			setJsdd(jsdd);
		}

		String jsgcgm = (String)attributes.get("jsgcgm");

		if (jsgcgm != null) {
			setJsgcgm(jsgcgm);
		}

		String fwjzmj = (String)attributes.get("fwjzmj");

		if (fwjzmj != null) {
			setFwjzmj(fwjzmj);
		}

		String htjg = (String)attributes.get("htjg");

		if (htjg != null) {
			setHtjg(htjg);
		}

		Integer htgq = (Integer)attributes.get("htgq");

		if (htgq != null) {
			setHtgq(htgq);
		}

		String fddbr = (String)attributes.get("fddbr");

		if (fddbr != null) {
			setFddbr(fddbr);
		}

		String jsdwlxdh = (String)attributes.get("jsdwlxdh");

		if (jsdwlxdh != null) {
			setJsdwlxdh(jsdwlxdh);
		}

		String jsdwlxr = (String)attributes.get("jsdwlxr");

		if (jsdwlxr != null) {
			setJsdwlxr(jsdwlxr);
		}

		String jsdwsjh = (String)attributes.get("jsdwsjh");

		if (jsdwsjh != null) {
			setJsdwsjh(jsdwsjh);
		}

		String jsgcghxkzbh = (String)attributes.get("jsgcghxkzbh");

		if (jsgcghxkzbh != null) {
			setJsgcghxkzbh(jsgcghxkzbh);
		}

		String xckgqk = (String)attributes.get("xckgqk");

		if (xckgqk != null) {
			setXckgqk(xckgqk);
		}

		Long xmlx = (Long)attributes.get("xmlx");

		if (xmlx != null) {
			setXmlx(xmlx);
		}

		String lxjb = (String)attributes.get("lxjb");

		if (lxjb != null) {
			setLxjb(lxjb);
		}

		Long xmxz = (Long)attributes.get("xmxz");

		if (xmxz != null) {
			setXmxz(xmxz);
		}

		String ssqx = (String)attributes.get("ssqx");

		if (ssqx != null) {
			setSsqx(ssqx);
		}

		String ywbm = (String)attributes.get("ywbm");

		if (ywbm != null) {
			setYwbm(ywbm);
		}

		Long jsddssqx = (Long)attributes.get("jsddssqx");

		if (jsddssqx != null) {
			setJsddssqx(jsddssqx);
		}

		String jsgclb = (String)attributes.get("jsgclb");

		if (jsgclb != null) {
			setJsgclb(jsgclb);
		}

		Long jsgcsx = (Long)attributes.get("jsgcsx");

		if (jsgcsx != null) {
			setJsgcsx(jsgcsx);
		}

		String gyzjbz = (String)attributes.get("gyzjbz");

		if (gyzjbz != null) {
			setGyzjbz(gyzjbz);
		}

		String zbjg = (String)attributes.get("zbjg");

		if (zbjg != null) {
			setZbjg(zbjg);
		}

		String xmtzgs = (String)attributes.get("xmtzgs");

		if (xmtzgs != null) {
			setXmtzgs(xmtzgs);
		}

		Date jhkg = (Date)attributes.get("jhkg");

		if (jhkg != null) {
			setJhkg(jhkg);
		}

		Date jhjg = (Date)attributes.get("jhjg");

		if (jhjg != null) {
			setJhjg(jhjg);
		}

		Boolean sfzftzl = (Boolean)attributes.get("sfzftzl");

		if (sfzftzl != null) {
			setSfzftzl(sfzftzl);
		}

		String yzzpl1 = (String)attributes.get("yzzpl1");

		if (yzzpl1 != null) {
			setYzzpl1(yzzpl1);
		}

		String yzzpl2 = (String)attributes.get("yzzpl2");

		if (yzzpl2 != null) {
			setYzzpl2(yzzpl2);
		}

		String yzzpl3 = (String)attributes.get("yzzpl3");

		if (yzzpl3 != null) {
			setYzzpl3(yzzpl3);
		}

		String yzzpl4 = (String)attributes.get("yzzpl4");

		if (yzzpl4 != null) {
			setYzzpl4(yzzpl4);
		}

		Date tjsj = (Date)attributes.get("tjsj");

		if (tjsj != null) {
			setTjsj(tjsj);
		}

		String gcnr = (String)attributes.get("gcnr");

		if (gcnr != null) {
			setGcnr(gcnr);
		}

		String sgxkzsbz = (String)attributes.get("sgxkzsbz");

		if (sgxkzsbz != null) {
			setSgxkzsbz(sgxkzsbz);
		}

		String tzly = (String)attributes.get("tzly");

		if (tzly != null) {
			setTzly(tzly);
		}

		String gkpzhhzjghwh = (String)attributes.get("gkpzhhzjghwh");

		if (gkpzhhzjghwh != null) {
			setGkpzhhzjghwh(gkpzhhzjghwh);
		}

		Date pfhhzrq = (Date)attributes.get("pfhhzrq");

		if (pfhhzrq != null) {
			setPfhhzrq(pfhhzrq);
		}

		String cbsjpzjghwh = (String)attributes.get("cbsjpzjghwh");

		if (cbsjpzjghwh != null) {
			setCbsjpzjghwh(cbsjpzjghwh);
		}

		Date pfrq = (Date)attributes.get("pfrq");

		if (pfrq != null) {
			setPfrq(pfrq);
		}

		Integer pfgq = (Integer)attributes.get("pfgq");

		if (pfgq != null) {
			setPfgq(pfgq);
		}

		String pzjghwh = (String)attributes.get("pzjghwh");

		if (pzjghwh != null) {
			setPzjghwh(pzjghwh);
		}

		String xmdw = (String)attributes.get("xmdw");

		if (xmdw != null) {
			setXmdw(xmdw);
		}

		String xmfzr = (String)attributes.get("xmfzr");

		if (xmfzr != null) {
			setXmfzr(xmfzr);
		}

		String xmfzrlxdh = (String)attributes.get("xmfzrlxdh");

		if (xmfzrlxdh != null) {
			setXmfzrlxdh(xmfzrlxdh);
		}

		String zysjdw = (String)attributes.get("zysjdw");

		if (zysjdw != null) {
			setZysjdw(zysjdw);
		}

		String sj_zbfs = (String)attributes.get("sj_zbfs");

		if (sj_zbfs != null) {
			setSj_zbfs(sj_zbfs);
		}

		String sj_zbj = (String)attributes.get("sj_zbj");

		if (sj_zbj != null) {
			setSj_zbj(sj_zbj);
		}

		String sj_zzdj = (String)attributes.get("sj_zzdj");

		if (sj_zzdj != null) {
			setSj_zzdj(sj_zzdj);
		}

		String sj_zzdjzsbh = (String)attributes.get("sj_zzdjzsbh");

		if (sj_zzdjzsbh != null) {
			setSj_zzdjzsbh(sj_zzdjzsbh);
		}

		String sj_xmfzr = (String)attributes.get("sj_xmfzr");

		if (sj_xmfzr != null) {
			setSj_xmfzr(sj_xmfzr);
		}

		String sj_xmfzrzsbh = (String)attributes.get("sj_xmfzrzsbh");

		if (sj_xmfzrzsbh != null) {
			setSj_xmfzrzsbh(sj_xmfzrzsbh);
		}

		String zyjldw = (String)attributes.get("zyjldw");

		if (zyjldw != null) {
			setZyjldw(zyjldw);
		}

		String jl_zbfs = (String)attributes.get("jl_zbfs");

		if (jl_zbfs != null) {
			setJl_zbfs(jl_zbfs);
		}

		String jl_zbj = (String)attributes.get("jl_zbj");

		if (jl_zbj != null) {
			setJl_zbj(jl_zbj);
		}

		String jl_zzdj = (String)attributes.get("jl_zzdj");

		if (jl_zzdj != null) {
			setJl_zzdj(jl_zzdj);
		}

		String jl_zzdjzsbh = (String)attributes.get("jl_zzdjzsbh");

		if (jl_zzdjzsbh != null) {
			setJl_zzdjzsbh(jl_zzdjzsbh);
		}

		String jl_zj = (String)attributes.get("jl_zj");

		if (jl_zj != null) {
			setJl_zj(jl_zj);
		}

		String jl_zjzsbh = (String)attributes.get("jl_zjzsbh");

		if (jl_zjzsbh != null) {
			setJl_zjzsbh(jl_zjzsbh);
		}

		String zysgdw = (String)attributes.get("zysgdw");

		if (zysgdw != null) {
			setZysgdw(zysgdw);
		}

		String sg_zbfs = (String)attributes.get("sg_zbfs");

		if (sg_zbfs != null) {
			setSg_zbfs(sg_zbfs);
		}

		String sg_zbj = (String)attributes.get("sg_zbj");

		if (sg_zbj != null) {
			setSg_zbj(sg_zbj);
		}

		String sg_zzdj = (String)attributes.get("sg_zzdj");

		if (sg_zzdj != null) {
			setSg_zzdj(sg_zzdj);
		}

		String sg_zzdjzsbh = (String)attributes.get("sg_zzdjzsbh");

		if (sg_zzdjzsbh != null) {
			setSg_zzdjzsbh(sg_zzdjzsbh);
		}

		String sg_xmjl = (String)attributes.get("sg_xmjl");

		if (sg_xmjl != null) {
			setSg_xmjl(sg_xmjl);
		}

		String sg_xmjlzsbh = (String)attributes.get("sg_xmjlzsbh");

		if (sg_xmjlzsbh != null) {
			setSg_xmjlzsbh(sg_xmjlzsbh);
		}

		String jszjjhlsqk = (String)attributes.get("jszjjhlsqk");

		if (jszjjhlsqk != null) {
			setJszjjhlsqk(jszjjhlsqk);
		}

		String dcqwcqk = (String)attributes.get("dcqwcqk");

		if (dcqwcqk != null) {
			setDcqwcqk(dcqwcqk);
		}

		String sgzbqk = (String)attributes.get("sgzbqk");

		if (sgzbqk != null) {
			setSgzbqk(sgzbqk);
		}

		String sytdxgwj = (String)attributes.get("sytdxgwj");

		if (sytdxgwj != null) {
			setSytdxgwj(sytdxgwj);
		}

		String gczljddjqk = (String)attributes.get("gczljddjqk");

		if (gczljddjqk != null) {
			setGczljddjqk(gczljddjqk);
		}
	}

	@Override
	public long getPermitId() {
		return _permitId;
	}

	@Override
	public void setPermitId(long permitId) {
		_permitId = permitId;
	}

	@Override
	public String getBjbh() {
		if (_bjbh == null) {
			return StringPool.BLANK;
		}
		else {
			return _bjbh;
		}
	}

	@Override
	public void setBjbh(String bjbh) {
		_bjbh = bjbh;
	}

	@Override
	public String getJsdwmc() {
		if (_jsdwmc == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsdwmc;
		}
	}

	@Override
	public void setJsdwmc(String jsdwmc) {
		_jsdwmc = jsdwmc;
	}

	@Override
	public String getJsdwxz() {
		if (_jsdwxz == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsdwxz;
		}
	}

	@Override
	public void setJsdwxz(String jsdwxz) {
		_jsdwxz = jsdwxz;
	}

	@Override
	public String getJsdwdz() {
		if (_jsdwdz == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsdwdz;
		}
	}

	@Override
	public void setJsdwdz(String jsdwdz) {
		_jsdwdz = jsdwdz;
	}

	@Override
	public String getGcmc() {
		if (_gcmc == null) {
			return StringPool.BLANK;
		}
		else {
			return _gcmc;
		}
	}

	@Override
	public void setGcmc(String gcmc) {
		_gcmc = gcmc;
	}

	@Override
	public String getJsdd() {
		if (_jsdd == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsdd;
		}
	}

	@Override
	public void setJsdd(String jsdd) {
		_jsdd = jsdd;
	}

	@Override
	public String getJsgcgm() {
		if (_jsgcgm == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsgcgm;
		}
	}

	@Override
	public void setJsgcgm(String jsgcgm) {
		_jsgcgm = jsgcgm;
	}

	@Override
	public String getFwjzmj() {
		if (_fwjzmj == null) {
			return StringPool.BLANK;
		}
		else {
			return _fwjzmj;
		}
	}

	@Override
	public void setFwjzmj(String fwjzmj) {
		_fwjzmj = fwjzmj;
	}

	@Override
	public String getHtjg() {
		if (_htjg == null) {
			return StringPool.BLANK;
		}
		else {
			return _htjg;
		}
	}

	@Override
	public void setHtjg(String htjg) {
		_htjg = htjg;
	}

	@Override
	public int getHtgq() {
		return _htgq;
	}

	@Override
	public void setHtgq(int htgq) {
		_htgq = htgq;
	}

	@Override
	public String getFddbr() {
		if (_fddbr == null) {
			return StringPool.BLANK;
		}
		else {
			return _fddbr;
		}
	}

	@Override
	public void setFddbr(String fddbr) {
		_fddbr = fddbr;
	}

	@Override
	public String getJsdwlxdh() {
		if (_jsdwlxdh == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsdwlxdh;
		}
	}

	@Override
	public void setJsdwlxdh(String jsdwlxdh) {
		_jsdwlxdh = jsdwlxdh;
	}

	@Override
	public String getJsdwlxr() {
		if (_jsdwlxr == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsdwlxr;
		}
	}

	@Override
	public void setJsdwlxr(String jsdwlxr) {
		_jsdwlxr = jsdwlxr;
	}

	@Override
	public String getJsdwsjh() {
		if (_jsdwsjh == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsdwsjh;
		}
	}

	@Override
	public void setJsdwsjh(String jsdwsjh) {
		_jsdwsjh = jsdwsjh;
	}

	@Override
	public String getJsgcghxkzbh() {
		if (_jsgcghxkzbh == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsgcghxkzbh;
		}
	}

	@Override
	public void setJsgcghxkzbh(String jsgcghxkzbh) {
		_jsgcghxkzbh = jsgcghxkzbh;
	}

	@Override
	public String getXckgqk() {
		if (_xckgqk == null) {
			return StringPool.BLANK;
		}
		else {
			return _xckgqk;
		}
	}

	@Override
	public void setXckgqk(String xckgqk) {
		_xckgqk = xckgqk;
	}

	@Override
	public long getXmlx() {
		return _xmlx;
	}

	@Override
	public void setXmlx(long xmlx) {
		_xmlx = xmlx;
	}

	@Override
	public String getLxjb() {
		if (_lxjb == null) {
			return StringPool.BLANK;
		}
		else {
			return _lxjb;
		}
	}

	@Override
	public void setLxjb(String lxjb) {
		_lxjb = lxjb;
	}

	@Override
	public long getXmxz() {
		return _xmxz;
	}

	@Override
	public void setXmxz(long xmxz) {
		_xmxz = xmxz;
	}

	@Override
	public String getSsqx() {
		if (_ssqx == null) {
			return StringPool.BLANK;
		}
		else {
			return _ssqx;
		}
	}

	@Override
	public void setSsqx(String ssqx) {
		_ssqx = ssqx;
	}

	@Override
	public String getYwbm() {
		if (_ywbm == null) {
			return StringPool.BLANK;
		}
		else {
			return _ywbm;
		}
	}

	@Override
	public void setYwbm(String ywbm) {
		_ywbm = ywbm;
	}

	@Override
	public long getJsddssqx() {
		return _jsddssqx;
	}

	@Override
	public void setJsddssqx(long jsddssqx) {
		_jsddssqx = jsddssqx;
	}

	@Override
	public String getJsgclb() {
		if (_jsgclb == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsgclb;
		}
	}

	@Override
	public void setJsgclb(String jsgclb) {
		_jsgclb = jsgclb;
	}

	@Override
	public long getJsgcsx() {
		return _jsgcsx;
	}

	@Override
	public void setJsgcsx(long jsgcsx) {
		_jsgcsx = jsgcsx;
	}

	@Override
	public String getGyzjbz() {
		if (_gyzjbz == null) {
			return StringPool.BLANK;
		}
		else {
			return _gyzjbz;
		}
	}

	@Override
	public void setGyzjbz(String gyzjbz) {
		_gyzjbz = gyzjbz;
	}

	@Override
	public String getZbjg() {
		if (_zbjg == null) {
			return StringPool.BLANK;
		}
		else {
			return _zbjg;
		}
	}

	@Override
	public void setZbjg(String zbjg) {
		_zbjg = zbjg;
	}

	@Override
	public String getXmtzgs() {
		if (_xmtzgs == null) {
			return StringPool.BLANK;
		}
		else {
			return _xmtzgs;
		}
	}

	@Override
	public void setXmtzgs(String xmtzgs) {
		_xmtzgs = xmtzgs;
	}

	@Override
	public Date getJhkg() {
		return _jhkg;
	}

	@Override
	public void setJhkg(Date jhkg) {
		_jhkg = jhkg;
	}

	@Override
	public Date getJhjg() {
		return _jhjg;
	}

	@Override
	public void setJhjg(Date jhjg) {
		_jhjg = jhjg;
	}

	@Override
	public boolean getSfzftzl() {
		return _sfzftzl;
	}

	@Override
	public boolean isSfzftzl() {
		return _sfzftzl;
	}

	@Override
	public void setSfzftzl(boolean sfzftzl) {
		_sfzftzl = sfzftzl;
	}

	@Override
	public String getYzzpl1() {
		if (_yzzpl1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _yzzpl1;
		}
	}

	@Override
	public void setYzzpl1(String yzzpl1) {
		_yzzpl1 = yzzpl1;
	}

	@Override
	public String getYzzpl2() {
		if (_yzzpl2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _yzzpl2;
		}
	}

	@Override
	public void setYzzpl2(String yzzpl2) {
		_yzzpl2 = yzzpl2;
	}

	@Override
	public String getYzzpl3() {
		if (_yzzpl3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _yzzpl3;
		}
	}

	@Override
	public void setYzzpl3(String yzzpl3) {
		_yzzpl3 = yzzpl3;
	}

	@Override
	public String getYzzpl4() {
		if (_yzzpl4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _yzzpl4;
		}
	}

	@Override
	public void setYzzpl4(String yzzpl4) {
		_yzzpl4 = yzzpl4;
	}

	@Override
	public Date getTjsj() {
		return _tjsj;
	}

	@Override
	public void setTjsj(Date tjsj) {
		_tjsj = tjsj;
	}

	@Override
	public String getGcnr() {
		if (_gcnr == null) {
			return StringPool.BLANK;
		}
		else {
			return _gcnr;
		}
	}

	@Override
	public void setGcnr(String gcnr) {
		_gcnr = gcnr;
	}

	@Override
	public String getSgxkzsbz() {
		if (_sgxkzsbz == null) {
			return StringPool.BLANK;
		}
		else {
			return _sgxkzsbz;
		}
	}

	@Override
	public void setSgxkzsbz(String sgxkzsbz) {
		_sgxkzsbz = sgxkzsbz;
	}

	@Override
	public String getTzly() {
		if (_tzly == null) {
			return StringPool.BLANK;
		}
		else {
			return _tzly;
		}
	}

	@Override
	public void setTzly(String tzly) {
		_tzly = tzly;
	}

	@Override
	public String getGkpzhhzjghwh() {
		if (_gkpzhhzjghwh == null) {
			return StringPool.BLANK;
		}
		else {
			return _gkpzhhzjghwh;
		}
	}

	@Override
	public void setGkpzhhzjghwh(String gkpzhhzjghwh) {
		_gkpzhhzjghwh = gkpzhhzjghwh;
	}

	@Override
	public Date getPfhhzrq() {
		return _pfhhzrq;
	}

	@Override
	public void setPfhhzrq(Date pfhhzrq) {
		_pfhhzrq = pfhhzrq;
	}

	@Override
	public String getCbsjpzjghwh() {
		if (_cbsjpzjghwh == null) {
			return StringPool.BLANK;
		}
		else {
			return _cbsjpzjghwh;
		}
	}

	@Override
	public void setCbsjpzjghwh(String cbsjpzjghwh) {
		_cbsjpzjghwh = cbsjpzjghwh;
	}

	@Override
	public Date getPfrq() {
		return _pfrq;
	}

	@Override
	public void setPfrq(Date pfrq) {
		_pfrq = pfrq;
	}

	@Override
	public int getPfgq() {
		return _pfgq;
	}

	@Override
	public void setPfgq(int pfgq) {
		_pfgq = pfgq;
	}

	@Override
	public String getPzjghwh() {
		if (_pzjghwh == null) {
			return StringPool.BLANK;
		}
		else {
			return _pzjghwh;
		}
	}

	@Override
	public void setPzjghwh(String pzjghwh) {
		_pzjghwh = pzjghwh;
	}

	@Override
	public String getXmdw() {
		if (_xmdw == null) {
			return StringPool.BLANK;
		}
		else {
			return _xmdw;
		}
	}

	@Override
	public void setXmdw(String xmdw) {
		_xmdw = xmdw;
	}

	@Override
	public String getXmfzr() {
		if (_xmfzr == null) {
			return StringPool.BLANK;
		}
		else {
			return _xmfzr;
		}
	}

	@Override
	public void setXmfzr(String xmfzr) {
		_xmfzr = xmfzr;
	}

	@Override
	public String getXmfzrlxdh() {
		if (_xmfzrlxdh == null) {
			return StringPool.BLANK;
		}
		else {
			return _xmfzrlxdh;
		}
	}

	@Override
	public void setXmfzrlxdh(String xmfzrlxdh) {
		_xmfzrlxdh = xmfzrlxdh;
	}

	@Override
	public String getZysjdw() {
		if (_zysjdw == null) {
			return StringPool.BLANK;
		}
		else {
			return _zysjdw;
		}
	}

	@Override
	public void setZysjdw(String zysjdw) {
		_zysjdw = zysjdw;
	}

	@Override
	public String getSj_zbfs() {
		if (_sj_zbfs == null) {
			return StringPool.BLANK;
		}
		else {
			return _sj_zbfs;
		}
	}

	@Override
	public void setSj_zbfs(String sj_zbfs) {
		_sj_zbfs = sj_zbfs;
	}

	@Override
	public String getSj_zbj() {
		if (_sj_zbj == null) {
			return StringPool.BLANK;
		}
		else {
			return _sj_zbj;
		}
	}

	@Override
	public void setSj_zbj(String sj_zbj) {
		_sj_zbj = sj_zbj;
	}

	@Override
	public String getSj_zzdj() {
		if (_sj_zzdj == null) {
			return StringPool.BLANK;
		}
		else {
			return _sj_zzdj;
		}
	}

	@Override
	public void setSj_zzdj(String sj_zzdj) {
		_sj_zzdj = sj_zzdj;
	}

	@Override
	public String getSj_zzdjzsbh() {
		if (_sj_zzdjzsbh == null) {
			return StringPool.BLANK;
		}
		else {
			return _sj_zzdjzsbh;
		}
	}

	@Override
	public void setSj_zzdjzsbh(String sj_zzdjzsbh) {
		_sj_zzdjzsbh = sj_zzdjzsbh;
	}

	@Override
	public String getSj_xmfzr() {
		if (_sj_xmfzr == null) {
			return StringPool.BLANK;
		}
		else {
			return _sj_xmfzr;
		}
	}

	@Override
	public void setSj_xmfzr(String sj_xmfzr) {
		_sj_xmfzr = sj_xmfzr;
	}

	@Override
	public String getSj_xmfzrzsbh() {
		if (_sj_xmfzrzsbh == null) {
			return StringPool.BLANK;
		}
		else {
			return _sj_xmfzrzsbh;
		}
	}

	@Override
	public void setSj_xmfzrzsbh(String sj_xmfzrzsbh) {
		_sj_xmfzrzsbh = sj_xmfzrzsbh;
	}

	@Override
	public String getZyjldw() {
		if (_zyjldw == null) {
			return StringPool.BLANK;
		}
		else {
			return _zyjldw;
		}
	}

	@Override
	public void setZyjldw(String zyjldw) {
		_zyjldw = zyjldw;
	}

	@Override
	public String getJl_zbfs() {
		if (_jl_zbfs == null) {
			return StringPool.BLANK;
		}
		else {
			return _jl_zbfs;
		}
	}

	@Override
	public void setJl_zbfs(String jl_zbfs) {
		_jl_zbfs = jl_zbfs;
	}

	@Override
	public String getJl_zbj() {
		if (_jl_zbj == null) {
			return StringPool.BLANK;
		}
		else {
			return _jl_zbj;
		}
	}

	@Override
	public void setJl_zbj(String jl_zbj) {
		_jl_zbj = jl_zbj;
	}

	@Override
	public String getJl_zzdj() {
		if (_jl_zzdj == null) {
			return StringPool.BLANK;
		}
		else {
			return _jl_zzdj;
		}
	}

	@Override
	public void setJl_zzdj(String jl_zzdj) {
		_jl_zzdj = jl_zzdj;
	}

	@Override
	public String getJl_zzdjzsbh() {
		if (_jl_zzdjzsbh == null) {
			return StringPool.BLANK;
		}
		else {
			return _jl_zzdjzsbh;
		}
	}

	@Override
	public void setJl_zzdjzsbh(String jl_zzdjzsbh) {
		_jl_zzdjzsbh = jl_zzdjzsbh;
	}

	@Override
	public String getJl_zj() {
		if (_jl_zj == null) {
			return StringPool.BLANK;
		}
		else {
			return _jl_zj;
		}
	}

	@Override
	public void setJl_zj(String jl_zj) {
		_jl_zj = jl_zj;
	}

	@Override
	public String getJl_zjzsbh() {
		if (_jl_zjzsbh == null) {
			return StringPool.BLANK;
		}
		else {
			return _jl_zjzsbh;
		}
	}

	@Override
	public void setJl_zjzsbh(String jl_zjzsbh) {
		_jl_zjzsbh = jl_zjzsbh;
	}

	@Override
	public String getZysgdw() {
		if (_zysgdw == null) {
			return StringPool.BLANK;
		}
		else {
			return _zysgdw;
		}
	}

	@Override
	public void setZysgdw(String zysgdw) {
		_zysgdw = zysgdw;
	}

	@Override
	public String getSg_zbfs() {
		if (_sg_zbfs == null) {
			return StringPool.BLANK;
		}
		else {
			return _sg_zbfs;
		}
	}

	@Override
	public void setSg_zbfs(String sg_zbfs) {
		_sg_zbfs = sg_zbfs;
	}

	@Override
	public String getSg_zbj() {
		if (_sg_zbj == null) {
			return StringPool.BLANK;
		}
		else {
			return _sg_zbj;
		}
	}

	@Override
	public void setSg_zbj(String sg_zbj) {
		_sg_zbj = sg_zbj;
	}

	@Override
	public String getSg_zzdj() {
		if (_sg_zzdj == null) {
			return StringPool.BLANK;
		}
		else {
			return _sg_zzdj;
		}
	}

	@Override
	public void setSg_zzdj(String sg_zzdj) {
		_sg_zzdj = sg_zzdj;
	}

	@Override
	public String getSg_zzdjzsbh() {
		if (_sg_zzdjzsbh == null) {
			return StringPool.BLANK;
		}
		else {
			return _sg_zzdjzsbh;
		}
	}

	@Override
	public void setSg_zzdjzsbh(String sg_zzdjzsbh) {
		_sg_zzdjzsbh = sg_zzdjzsbh;
	}

	@Override
	public String getSg_xmjl() {
		if (_sg_xmjl == null) {
			return StringPool.BLANK;
		}
		else {
			return _sg_xmjl;
		}
	}

	@Override
	public void setSg_xmjl(String sg_xmjl) {
		_sg_xmjl = sg_xmjl;
	}

	@Override
	public String getSg_xmjlzsbh() {
		if (_sg_xmjlzsbh == null) {
			return StringPool.BLANK;
		}
		else {
			return _sg_xmjlzsbh;
		}
	}

	@Override
	public void setSg_xmjlzsbh(String sg_xmjlzsbh) {
		_sg_xmjlzsbh = sg_xmjlzsbh;
	}

	@Override
	public String getJszjjhlsqk() {
		if (_jszjjhlsqk == null) {
			return StringPool.BLANK;
		}
		else {
			return _jszjjhlsqk;
		}
	}

	@Override
	public void setJszjjhlsqk(String jszjjhlsqk) {
		_jszjjhlsqk = jszjjhlsqk;
	}

	@Override
	public String getDcqwcqk() {
		if (_dcqwcqk == null) {
			return StringPool.BLANK;
		}
		else {
			return _dcqwcqk;
		}
	}

	@Override
	public void setDcqwcqk(String dcqwcqk) {
		_dcqwcqk = dcqwcqk;
	}

	@Override
	public String getSgzbqk() {
		if (_sgzbqk == null) {
			return StringPool.BLANK;
		}
		else {
			return _sgzbqk;
		}
	}

	@Override
	public void setSgzbqk(String sgzbqk) {
		_sgzbqk = sgzbqk;
	}

	@Override
	public String getSytdxgwj() {
		if (_sytdxgwj == null) {
			return StringPool.BLANK;
		}
		else {
			return _sytdxgwj;
		}
	}

	@Override
	public void setSytdxgwj(String sytdxgwj) {
		_sytdxgwj = sytdxgwj;
	}

	@Override
	public String getGczljddjqk() {
		if (_gczljddjqk == null) {
			return StringPool.BLANK;
		}
		else {
			return _gczljddjqk;
		}
	}

	@Override
	public void setGczljddjqk(String gczljddjqk) {
		_gczljddjqk = gczljddjqk;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ProjectProfile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProjectProfile toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ProjectProfile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectProfileImpl projectProfileImpl = new ProjectProfileImpl();

		projectProfileImpl.setPermitId(getPermitId());
		projectProfileImpl.setBjbh(getBjbh());
		projectProfileImpl.setJsdwmc(getJsdwmc());
		projectProfileImpl.setJsdwxz(getJsdwxz());
		projectProfileImpl.setJsdwdz(getJsdwdz());
		projectProfileImpl.setGcmc(getGcmc());
		projectProfileImpl.setJsdd(getJsdd());
		projectProfileImpl.setJsgcgm(getJsgcgm());
		projectProfileImpl.setFwjzmj(getFwjzmj());
		projectProfileImpl.setHtjg(getHtjg());
		projectProfileImpl.setHtgq(getHtgq());
		projectProfileImpl.setFddbr(getFddbr());
		projectProfileImpl.setJsdwlxdh(getJsdwlxdh());
		projectProfileImpl.setJsdwlxr(getJsdwlxr());
		projectProfileImpl.setJsdwsjh(getJsdwsjh());
		projectProfileImpl.setJsgcghxkzbh(getJsgcghxkzbh());
		projectProfileImpl.setXckgqk(getXckgqk());
		projectProfileImpl.setXmlx(getXmlx());
		projectProfileImpl.setLxjb(getLxjb());
		projectProfileImpl.setXmxz(getXmxz());
		projectProfileImpl.setSsqx(getSsqx());
		projectProfileImpl.setYwbm(getYwbm());
		projectProfileImpl.setJsddssqx(getJsddssqx());
		projectProfileImpl.setJsgclb(getJsgclb());
		projectProfileImpl.setJsgcsx(getJsgcsx());
		projectProfileImpl.setGyzjbz(getGyzjbz());
		projectProfileImpl.setZbjg(getZbjg());
		projectProfileImpl.setXmtzgs(getXmtzgs());
		projectProfileImpl.setJhkg(getJhkg());
		projectProfileImpl.setJhjg(getJhjg());
		projectProfileImpl.setSfzftzl(getSfzftzl());
		projectProfileImpl.setYzzpl1(getYzzpl1());
		projectProfileImpl.setYzzpl2(getYzzpl2());
		projectProfileImpl.setYzzpl3(getYzzpl3());
		projectProfileImpl.setYzzpl4(getYzzpl4());
		projectProfileImpl.setTjsj(getTjsj());
		projectProfileImpl.setGcnr(getGcnr());
		projectProfileImpl.setSgxkzsbz(getSgxkzsbz());
		projectProfileImpl.setTzly(getTzly());
		projectProfileImpl.setGkpzhhzjghwh(getGkpzhhzjghwh());
		projectProfileImpl.setPfhhzrq(getPfhhzrq());
		projectProfileImpl.setCbsjpzjghwh(getCbsjpzjghwh());
		projectProfileImpl.setPfrq(getPfrq());
		projectProfileImpl.setPfgq(getPfgq());
		projectProfileImpl.setPzjghwh(getPzjghwh());
		projectProfileImpl.setXmdw(getXmdw());
		projectProfileImpl.setXmfzr(getXmfzr());
		projectProfileImpl.setXmfzrlxdh(getXmfzrlxdh());
		projectProfileImpl.setZysjdw(getZysjdw());
		projectProfileImpl.setSj_zbfs(getSj_zbfs());
		projectProfileImpl.setSj_zbj(getSj_zbj());
		projectProfileImpl.setSj_zzdj(getSj_zzdj());
		projectProfileImpl.setSj_zzdjzsbh(getSj_zzdjzsbh());
		projectProfileImpl.setSj_xmfzr(getSj_xmfzr());
		projectProfileImpl.setSj_xmfzrzsbh(getSj_xmfzrzsbh());
		projectProfileImpl.setZyjldw(getZyjldw());
		projectProfileImpl.setJl_zbfs(getJl_zbfs());
		projectProfileImpl.setJl_zbj(getJl_zbj());
		projectProfileImpl.setJl_zzdj(getJl_zzdj());
		projectProfileImpl.setJl_zzdjzsbh(getJl_zzdjzsbh());
		projectProfileImpl.setJl_zj(getJl_zj());
		projectProfileImpl.setJl_zjzsbh(getJl_zjzsbh());
		projectProfileImpl.setZysgdw(getZysgdw());
		projectProfileImpl.setSg_zbfs(getSg_zbfs());
		projectProfileImpl.setSg_zbj(getSg_zbj());
		projectProfileImpl.setSg_zzdj(getSg_zzdj());
		projectProfileImpl.setSg_zzdjzsbh(getSg_zzdjzsbh());
		projectProfileImpl.setSg_xmjl(getSg_xmjl());
		projectProfileImpl.setSg_xmjlzsbh(getSg_xmjlzsbh());
		projectProfileImpl.setJszjjhlsqk(getJszjjhlsqk());
		projectProfileImpl.setDcqwcqk(getDcqwcqk());
		projectProfileImpl.setSgzbqk(getSgzbqk());
		projectProfileImpl.setSytdxgwj(getSytdxgwj());
		projectProfileImpl.setGczljddjqk(getGczljddjqk());

		projectProfileImpl.resetOriginalValues();

		return projectProfileImpl;
	}

	@Override
	public int compareTo(ProjectProfile projectProfile) {
		long primaryKey = projectProfile.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ProjectProfile)) {
			return false;
		}

		ProjectProfile projectProfile = (ProjectProfile)obj;

		long primaryKey = projectProfile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ProjectProfile> toCacheModel() {
		ProjectProfileCacheModel projectProfileCacheModel = new ProjectProfileCacheModel();

		projectProfileCacheModel.permitId = getPermitId();

		projectProfileCacheModel.bjbh = getBjbh();

		String bjbh = projectProfileCacheModel.bjbh;

		if ((bjbh != null) && (bjbh.length() == 0)) {
			projectProfileCacheModel.bjbh = null;
		}

		projectProfileCacheModel.jsdwmc = getJsdwmc();

		String jsdwmc = projectProfileCacheModel.jsdwmc;

		if ((jsdwmc != null) && (jsdwmc.length() == 0)) {
			projectProfileCacheModel.jsdwmc = null;
		}

		projectProfileCacheModel.jsdwxz = getJsdwxz();

		String jsdwxz = projectProfileCacheModel.jsdwxz;

		if ((jsdwxz != null) && (jsdwxz.length() == 0)) {
			projectProfileCacheModel.jsdwxz = null;
		}

		projectProfileCacheModel.jsdwdz = getJsdwdz();

		String jsdwdz = projectProfileCacheModel.jsdwdz;

		if ((jsdwdz != null) && (jsdwdz.length() == 0)) {
			projectProfileCacheModel.jsdwdz = null;
		}

		projectProfileCacheModel.gcmc = getGcmc();

		String gcmc = projectProfileCacheModel.gcmc;

		if ((gcmc != null) && (gcmc.length() == 0)) {
			projectProfileCacheModel.gcmc = null;
		}

		projectProfileCacheModel.jsdd = getJsdd();

		String jsdd = projectProfileCacheModel.jsdd;

		if ((jsdd != null) && (jsdd.length() == 0)) {
			projectProfileCacheModel.jsdd = null;
		}

		projectProfileCacheModel.jsgcgm = getJsgcgm();

		String jsgcgm = projectProfileCacheModel.jsgcgm;

		if ((jsgcgm != null) && (jsgcgm.length() == 0)) {
			projectProfileCacheModel.jsgcgm = null;
		}

		projectProfileCacheModel.fwjzmj = getFwjzmj();

		String fwjzmj = projectProfileCacheModel.fwjzmj;

		if ((fwjzmj != null) && (fwjzmj.length() == 0)) {
			projectProfileCacheModel.fwjzmj = null;
		}

		projectProfileCacheModel.htjg = getHtjg();

		String htjg = projectProfileCacheModel.htjg;

		if ((htjg != null) && (htjg.length() == 0)) {
			projectProfileCacheModel.htjg = null;
		}

		projectProfileCacheModel.htgq = getHtgq();

		projectProfileCacheModel.fddbr = getFddbr();

		String fddbr = projectProfileCacheModel.fddbr;

		if ((fddbr != null) && (fddbr.length() == 0)) {
			projectProfileCacheModel.fddbr = null;
		}

		projectProfileCacheModel.jsdwlxdh = getJsdwlxdh();

		String jsdwlxdh = projectProfileCacheModel.jsdwlxdh;

		if ((jsdwlxdh != null) && (jsdwlxdh.length() == 0)) {
			projectProfileCacheModel.jsdwlxdh = null;
		}

		projectProfileCacheModel.jsdwlxr = getJsdwlxr();

		String jsdwlxr = projectProfileCacheModel.jsdwlxr;

		if ((jsdwlxr != null) && (jsdwlxr.length() == 0)) {
			projectProfileCacheModel.jsdwlxr = null;
		}

		projectProfileCacheModel.jsdwsjh = getJsdwsjh();

		String jsdwsjh = projectProfileCacheModel.jsdwsjh;

		if ((jsdwsjh != null) && (jsdwsjh.length() == 0)) {
			projectProfileCacheModel.jsdwsjh = null;
		}

		projectProfileCacheModel.jsgcghxkzbh = getJsgcghxkzbh();

		String jsgcghxkzbh = projectProfileCacheModel.jsgcghxkzbh;

		if ((jsgcghxkzbh != null) && (jsgcghxkzbh.length() == 0)) {
			projectProfileCacheModel.jsgcghxkzbh = null;
		}

		projectProfileCacheModel.xckgqk = getXckgqk();

		String xckgqk = projectProfileCacheModel.xckgqk;

		if ((xckgqk != null) && (xckgqk.length() == 0)) {
			projectProfileCacheModel.xckgqk = null;
		}

		projectProfileCacheModel.xmlx = getXmlx();

		projectProfileCacheModel.lxjb = getLxjb();

		String lxjb = projectProfileCacheModel.lxjb;

		if ((lxjb != null) && (lxjb.length() == 0)) {
			projectProfileCacheModel.lxjb = null;
		}

		projectProfileCacheModel.xmxz = getXmxz();

		projectProfileCacheModel.ssqx = getSsqx();

		String ssqx = projectProfileCacheModel.ssqx;

		if ((ssqx != null) && (ssqx.length() == 0)) {
			projectProfileCacheModel.ssqx = null;
		}

		projectProfileCacheModel.ywbm = getYwbm();

		String ywbm = projectProfileCacheModel.ywbm;

		if ((ywbm != null) && (ywbm.length() == 0)) {
			projectProfileCacheModel.ywbm = null;
		}

		projectProfileCacheModel.jsddssqx = getJsddssqx();

		projectProfileCacheModel.jsgclb = getJsgclb();

		String jsgclb = projectProfileCacheModel.jsgclb;

		if ((jsgclb != null) && (jsgclb.length() == 0)) {
			projectProfileCacheModel.jsgclb = null;
		}

		projectProfileCacheModel.jsgcsx = getJsgcsx();

		projectProfileCacheModel.gyzjbz = getGyzjbz();

		String gyzjbz = projectProfileCacheModel.gyzjbz;

		if ((gyzjbz != null) && (gyzjbz.length() == 0)) {
			projectProfileCacheModel.gyzjbz = null;
		}

		projectProfileCacheModel.zbjg = getZbjg();

		String zbjg = projectProfileCacheModel.zbjg;

		if ((zbjg != null) && (zbjg.length() == 0)) {
			projectProfileCacheModel.zbjg = null;
		}

		projectProfileCacheModel.xmtzgs = getXmtzgs();

		String xmtzgs = projectProfileCacheModel.xmtzgs;

		if ((xmtzgs != null) && (xmtzgs.length() == 0)) {
			projectProfileCacheModel.xmtzgs = null;
		}

		Date jhkg = getJhkg();

		if (jhkg != null) {
			projectProfileCacheModel.jhkg = jhkg.getTime();
		}
		else {
			projectProfileCacheModel.jhkg = Long.MIN_VALUE;
		}

		Date jhjg = getJhjg();

		if (jhjg != null) {
			projectProfileCacheModel.jhjg = jhjg.getTime();
		}
		else {
			projectProfileCacheModel.jhjg = Long.MIN_VALUE;
		}

		projectProfileCacheModel.sfzftzl = getSfzftzl();

		projectProfileCacheModel.yzzpl1 = getYzzpl1();

		String yzzpl1 = projectProfileCacheModel.yzzpl1;

		if ((yzzpl1 != null) && (yzzpl1.length() == 0)) {
			projectProfileCacheModel.yzzpl1 = null;
		}

		projectProfileCacheModel.yzzpl2 = getYzzpl2();

		String yzzpl2 = projectProfileCacheModel.yzzpl2;

		if ((yzzpl2 != null) && (yzzpl2.length() == 0)) {
			projectProfileCacheModel.yzzpl2 = null;
		}

		projectProfileCacheModel.yzzpl3 = getYzzpl3();

		String yzzpl3 = projectProfileCacheModel.yzzpl3;

		if ((yzzpl3 != null) && (yzzpl3.length() == 0)) {
			projectProfileCacheModel.yzzpl3 = null;
		}

		projectProfileCacheModel.yzzpl4 = getYzzpl4();

		String yzzpl4 = projectProfileCacheModel.yzzpl4;

		if ((yzzpl4 != null) && (yzzpl4.length() == 0)) {
			projectProfileCacheModel.yzzpl4 = null;
		}

		Date tjsj = getTjsj();

		if (tjsj != null) {
			projectProfileCacheModel.tjsj = tjsj.getTime();
		}
		else {
			projectProfileCacheModel.tjsj = Long.MIN_VALUE;
		}

		projectProfileCacheModel.gcnr = getGcnr();

		String gcnr = projectProfileCacheModel.gcnr;

		if ((gcnr != null) && (gcnr.length() == 0)) {
			projectProfileCacheModel.gcnr = null;
		}

		projectProfileCacheModel.sgxkzsbz = getSgxkzsbz();

		String sgxkzsbz = projectProfileCacheModel.sgxkzsbz;

		if ((sgxkzsbz != null) && (sgxkzsbz.length() == 0)) {
			projectProfileCacheModel.sgxkzsbz = null;
		}

		projectProfileCacheModel.tzly = getTzly();

		String tzly = projectProfileCacheModel.tzly;

		if ((tzly != null) && (tzly.length() == 0)) {
			projectProfileCacheModel.tzly = null;
		}

		projectProfileCacheModel.gkpzhhzjghwh = getGkpzhhzjghwh();

		String gkpzhhzjghwh = projectProfileCacheModel.gkpzhhzjghwh;

		if ((gkpzhhzjghwh != null) && (gkpzhhzjghwh.length() == 0)) {
			projectProfileCacheModel.gkpzhhzjghwh = null;
		}

		Date pfhhzrq = getPfhhzrq();

		if (pfhhzrq != null) {
			projectProfileCacheModel.pfhhzrq = pfhhzrq.getTime();
		}
		else {
			projectProfileCacheModel.pfhhzrq = Long.MIN_VALUE;
		}

		projectProfileCacheModel.cbsjpzjghwh = getCbsjpzjghwh();

		String cbsjpzjghwh = projectProfileCacheModel.cbsjpzjghwh;

		if ((cbsjpzjghwh != null) && (cbsjpzjghwh.length() == 0)) {
			projectProfileCacheModel.cbsjpzjghwh = null;
		}

		Date pfrq = getPfrq();

		if (pfrq != null) {
			projectProfileCacheModel.pfrq = pfrq.getTime();
		}
		else {
			projectProfileCacheModel.pfrq = Long.MIN_VALUE;
		}

		projectProfileCacheModel.pfgq = getPfgq();

		projectProfileCacheModel.pzjghwh = getPzjghwh();

		String pzjghwh = projectProfileCacheModel.pzjghwh;

		if ((pzjghwh != null) && (pzjghwh.length() == 0)) {
			projectProfileCacheModel.pzjghwh = null;
		}

		projectProfileCacheModel.xmdw = getXmdw();

		String xmdw = projectProfileCacheModel.xmdw;

		if ((xmdw != null) && (xmdw.length() == 0)) {
			projectProfileCacheModel.xmdw = null;
		}

		projectProfileCacheModel.xmfzr = getXmfzr();

		String xmfzr = projectProfileCacheModel.xmfzr;

		if ((xmfzr != null) && (xmfzr.length() == 0)) {
			projectProfileCacheModel.xmfzr = null;
		}

		projectProfileCacheModel.xmfzrlxdh = getXmfzrlxdh();

		String xmfzrlxdh = projectProfileCacheModel.xmfzrlxdh;

		if ((xmfzrlxdh != null) && (xmfzrlxdh.length() == 0)) {
			projectProfileCacheModel.xmfzrlxdh = null;
		}

		projectProfileCacheModel.zysjdw = getZysjdw();

		String zysjdw = projectProfileCacheModel.zysjdw;

		if ((zysjdw != null) && (zysjdw.length() == 0)) {
			projectProfileCacheModel.zysjdw = null;
		}

		projectProfileCacheModel.sj_zbfs = getSj_zbfs();

		String sj_zbfs = projectProfileCacheModel.sj_zbfs;

		if ((sj_zbfs != null) && (sj_zbfs.length() == 0)) {
			projectProfileCacheModel.sj_zbfs = null;
		}

		projectProfileCacheModel.sj_zbj = getSj_zbj();

		String sj_zbj = projectProfileCacheModel.sj_zbj;

		if ((sj_zbj != null) && (sj_zbj.length() == 0)) {
			projectProfileCacheModel.sj_zbj = null;
		}

		projectProfileCacheModel.sj_zzdj = getSj_zzdj();

		String sj_zzdj = projectProfileCacheModel.sj_zzdj;

		if ((sj_zzdj != null) && (sj_zzdj.length() == 0)) {
			projectProfileCacheModel.sj_zzdj = null;
		}

		projectProfileCacheModel.sj_zzdjzsbh = getSj_zzdjzsbh();

		String sj_zzdjzsbh = projectProfileCacheModel.sj_zzdjzsbh;

		if ((sj_zzdjzsbh != null) && (sj_zzdjzsbh.length() == 0)) {
			projectProfileCacheModel.sj_zzdjzsbh = null;
		}

		projectProfileCacheModel.sj_xmfzr = getSj_xmfzr();

		String sj_xmfzr = projectProfileCacheModel.sj_xmfzr;

		if ((sj_xmfzr != null) && (sj_xmfzr.length() == 0)) {
			projectProfileCacheModel.sj_xmfzr = null;
		}

		projectProfileCacheModel.sj_xmfzrzsbh = getSj_xmfzrzsbh();

		String sj_xmfzrzsbh = projectProfileCacheModel.sj_xmfzrzsbh;

		if ((sj_xmfzrzsbh != null) && (sj_xmfzrzsbh.length() == 0)) {
			projectProfileCacheModel.sj_xmfzrzsbh = null;
		}

		projectProfileCacheModel.zyjldw = getZyjldw();

		String zyjldw = projectProfileCacheModel.zyjldw;

		if ((zyjldw != null) && (zyjldw.length() == 0)) {
			projectProfileCacheModel.zyjldw = null;
		}

		projectProfileCacheModel.jl_zbfs = getJl_zbfs();

		String jl_zbfs = projectProfileCacheModel.jl_zbfs;

		if ((jl_zbfs != null) && (jl_zbfs.length() == 0)) {
			projectProfileCacheModel.jl_zbfs = null;
		}

		projectProfileCacheModel.jl_zbj = getJl_zbj();

		String jl_zbj = projectProfileCacheModel.jl_zbj;

		if ((jl_zbj != null) && (jl_zbj.length() == 0)) {
			projectProfileCacheModel.jl_zbj = null;
		}

		projectProfileCacheModel.jl_zzdj = getJl_zzdj();

		String jl_zzdj = projectProfileCacheModel.jl_zzdj;

		if ((jl_zzdj != null) && (jl_zzdj.length() == 0)) {
			projectProfileCacheModel.jl_zzdj = null;
		}

		projectProfileCacheModel.jl_zzdjzsbh = getJl_zzdjzsbh();

		String jl_zzdjzsbh = projectProfileCacheModel.jl_zzdjzsbh;

		if ((jl_zzdjzsbh != null) && (jl_zzdjzsbh.length() == 0)) {
			projectProfileCacheModel.jl_zzdjzsbh = null;
		}

		projectProfileCacheModel.jl_zj = getJl_zj();

		String jl_zj = projectProfileCacheModel.jl_zj;

		if ((jl_zj != null) && (jl_zj.length() == 0)) {
			projectProfileCacheModel.jl_zj = null;
		}

		projectProfileCacheModel.jl_zjzsbh = getJl_zjzsbh();

		String jl_zjzsbh = projectProfileCacheModel.jl_zjzsbh;

		if ((jl_zjzsbh != null) && (jl_zjzsbh.length() == 0)) {
			projectProfileCacheModel.jl_zjzsbh = null;
		}

		projectProfileCacheModel.zysgdw = getZysgdw();

		String zysgdw = projectProfileCacheModel.zysgdw;

		if ((zysgdw != null) && (zysgdw.length() == 0)) {
			projectProfileCacheModel.zysgdw = null;
		}

		projectProfileCacheModel.sg_zbfs = getSg_zbfs();

		String sg_zbfs = projectProfileCacheModel.sg_zbfs;

		if ((sg_zbfs != null) && (sg_zbfs.length() == 0)) {
			projectProfileCacheModel.sg_zbfs = null;
		}

		projectProfileCacheModel.sg_zbj = getSg_zbj();

		String sg_zbj = projectProfileCacheModel.sg_zbj;

		if ((sg_zbj != null) && (sg_zbj.length() == 0)) {
			projectProfileCacheModel.sg_zbj = null;
		}

		projectProfileCacheModel.sg_zzdj = getSg_zzdj();

		String sg_zzdj = projectProfileCacheModel.sg_zzdj;

		if ((sg_zzdj != null) && (sg_zzdj.length() == 0)) {
			projectProfileCacheModel.sg_zzdj = null;
		}

		projectProfileCacheModel.sg_zzdjzsbh = getSg_zzdjzsbh();

		String sg_zzdjzsbh = projectProfileCacheModel.sg_zzdjzsbh;

		if ((sg_zzdjzsbh != null) && (sg_zzdjzsbh.length() == 0)) {
			projectProfileCacheModel.sg_zzdjzsbh = null;
		}

		projectProfileCacheModel.sg_xmjl = getSg_xmjl();

		String sg_xmjl = projectProfileCacheModel.sg_xmjl;

		if ((sg_xmjl != null) && (sg_xmjl.length() == 0)) {
			projectProfileCacheModel.sg_xmjl = null;
		}

		projectProfileCacheModel.sg_xmjlzsbh = getSg_xmjlzsbh();

		String sg_xmjlzsbh = projectProfileCacheModel.sg_xmjlzsbh;

		if ((sg_xmjlzsbh != null) && (sg_xmjlzsbh.length() == 0)) {
			projectProfileCacheModel.sg_xmjlzsbh = null;
		}

		projectProfileCacheModel.jszjjhlsqk = getJszjjhlsqk();

		String jszjjhlsqk = projectProfileCacheModel.jszjjhlsqk;

		if ((jszjjhlsqk != null) && (jszjjhlsqk.length() == 0)) {
			projectProfileCacheModel.jszjjhlsqk = null;
		}

		projectProfileCacheModel.dcqwcqk = getDcqwcqk();

		String dcqwcqk = projectProfileCacheModel.dcqwcqk;

		if ((dcqwcqk != null) && (dcqwcqk.length() == 0)) {
			projectProfileCacheModel.dcqwcqk = null;
		}

		projectProfileCacheModel.sgzbqk = getSgzbqk();

		String sgzbqk = projectProfileCacheModel.sgzbqk;

		if ((sgzbqk != null) && (sgzbqk.length() == 0)) {
			projectProfileCacheModel.sgzbqk = null;
		}

		projectProfileCacheModel.sytdxgwj = getSytdxgwj();

		String sytdxgwj = projectProfileCacheModel.sytdxgwj;

		if ((sytdxgwj != null) && (sytdxgwj.length() == 0)) {
			projectProfileCacheModel.sytdxgwj = null;
		}

		projectProfileCacheModel.gczljddjqk = getGczljddjqk();

		String gczljddjqk = projectProfileCacheModel.gczljddjqk;

		if ((gczljddjqk != null) && (gczljddjqk.length() == 0)) {
			projectProfileCacheModel.gczljddjqk = null;
		}

		return projectProfileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(149);

		sb.append("{permitId=");
		sb.append(getPermitId());
		sb.append(", bjbh=");
		sb.append(getBjbh());
		sb.append(", jsdwmc=");
		sb.append(getJsdwmc());
		sb.append(", jsdwxz=");
		sb.append(getJsdwxz());
		sb.append(", jsdwdz=");
		sb.append(getJsdwdz());
		sb.append(", gcmc=");
		sb.append(getGcmc());
		sb.append(", jsdd=");
		sb.append(getJsdd());
		sb.append(", jsgcgm=");
		sb.append(getJsgcgm());
		sb.append(", fwjzmj=");
		sb.append(getFwjzmj());
		sb.append(", htjg=");
		sb.append(getHtjg());
		sb.append(", htgq=");
		sb.append(getHtgq());
		sb.append(", fddbr=");
		sb.append(getFddbr());
		sb.append(", jsdwlxdh=");
		sb.append(getJsdwlxdh());
		sb.append(", jsdwlxr=");
		sb.append(getJsdwlxr());
		sb.append(", jsdwsjh=");
		sb.append(getJsdwsjh());
		sb.append(", jsgcghxkzbh=");
		sb.append(getJsgcghxkzbh());
		sb.append(", xckgqk=");
		sb.append(getXckgqk());
		sb.append(", xmlx=");
		sb.append(getXmlx());
		sb.append(", lxjb=");
		sb.append(getLxjb());
		sb.append(", xmxz=");
		sb.append(getXmxz());
		sb.append(", ssqx=");
		sb.append(getSsqx());
		sb.append(", ywbm=");
		sb.append(getYwbm());
		sb.append(", jsddssqx=");
		sb.append(getJsddssqx());
		sb.append(", jsgclb=");
		sb.append(getJsgclb());
		sb.append(", jsgcsx=");
		sb.append(getJsgcsx());
		sb.append(", gyzjbz=");
		sb.append(getGyzjbz());
		sb.append(", zbjg=");
		sb.append(getZbjg());
		sb.append(", xmtzgs=");
		sb.append(getXmtzgs());
		sb.append(", jhkg=");
		sb.append(getJhkg());
		sb.append(", jhjg=");
		sb.append(getJhjg());
		sb.append(", sfzftzl=");
		sb.append(getSfzftzl());
		sb.append(", yzzpl1=");
		sb.append(getYzzpl1());
		sb.append(", yzzpl2=");
		sb.append(getYzzpl2());
		sb.append(", yzzpl3=");
		sb.append(getYzzpl3());
		sb.append(", yzzpl4=");
		sb.append(getYzzpl4());
		sb.append(", tjsj=");
		sb.append(getTjsj());
		sb.append(", gcnr=");
		sb.append(getGcnr());
		sb.append(", sgxkzsbz=");
		sb.append(getSgxkzsbz());
		sb.append(", tzly=");
		sb.append(getTzly());
		sb.append(", gkpzhhzjghwh=");
		sb.append(getGkpzhhzjghwh());
		sb.append(", pfhhzrq=");
		sb.append(getPfhhzrq());
		sb.append(", cbsjpzjghwh=");
		sb.append(getCbsjpzjghwh());
		sb.append(", pfrq=");
		sb.append(getPfrq());
		sb.append(", pfgq=");
		sb.append(getPfgq());
		sb.append(", pzjghwh=");
		sb.append(getPzjghwh());
		sb.append(", xmdw=");
		sb.append(getXmdw());
		sb.append(", xmfzr=");
		sb.append(getXmfzr());
		sb.append(", xmfzrlxdh=");
		sb.append(getXmfzrlxdh());
		sb.append(", zysjdw=");
		sb.append(getZysjdw());
		sb.append(", sj_zbfs=");
		sb.append(getSj_zbfs());
		sb.append(", sj_zbj=");
		sb.append(getSj_zbj());
		sb.append(", sj_zzdj=");
		sb.append(getSj_zzdj());
		sb.append(", sj_zzdjzsbh=");
		sb.append(getSj_zzdjzsbh());
		sb.append(", sj_xmfzr=");
		sb.append(getSj_xmfzr());
		sb.append(", sj_xmfzrzsbh=");
		sb.append(getSj_xmfzrzsbh());
		sb.append(", zyjldw=");
		sb.append(getZyjldw());
		sb.append(", jl_zbfs=");
		sb.append(getJl_zbfs());
		sb.append(", jl_zbj=");
		sb.append(getJl_zbj());
		sb.append(", jl_zzdj=");
		sb.append(getJl_zzdj());
		sb.append(", jl_zzdjzsbh=");
		sb.append(getJl_zzdjzsbh());
		sb.append(", jl_zj=");
		sb.append(getJl_zj());
		sb.append(", jl_zjzsbh=");
		sb.append(getJl_zjzsbh());
		sb.append(", zysgdw=");
		sb.append(getZysgdw());
		sb.append(", sg_zbfs=");
		sb.append(getSg_zbfs());
		sb.append(", sg_zbj=");
		sb.append(getSg_zbj());
		sb.append(", sg_zzdj=");
		sb.append(getSg_zzdj());
		sb.append(", sg_zzdjzsbh=");
		sb.append(getSg_zzdjzsbh());
		sb.append(", sg_xmjl=");
		sb.append(getSg_xmjl());
		sb.append(", sg_xmjlzsbh=");
		sb.append(getSg_xmjlzsbh());
		sb.append(", jszjjhlsqk=");
		sb.append(getJszjjhlsqk());
		sb.append(", dcqwcqk=");
		sb.append(getDcqwcqk());
		sb.append(", sgzbqk=");
		sb.append(getSgzbqk());
		sb.append(", sytdxgwj=");
		sb.append(getSytdxgwj());
		sb.append(", gczljddjqk=");
		sb.append(getGczljddjqk());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(226);

		sb.append("<model><model-name>");
		sb.append("com.justonetech.cp.permit.model.ProjectProfile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>permitId</column-name><column-value><![CDATA[");
		sb.append(getPermitId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bjbh</column-name><column-value><![CDATA[");
		sb.append(getBjbh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsdwmc</column-name><column-value><![CDATA[");
		sb.append(getJsdwmc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsdwxz</column-name><column-value><![CDATA[");
		sb.append(getJsdwxz());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsdwdz</column-name><column-value><![CDATA[");
		sb.append(getJsdwdz());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gcmc</column-name><column-value><![CDATA[");
		sb.append(getGcmc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsdd</column-name><column-value><![CDATA[");
		sb.append(getJsdd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsgcgm</column-name><column-value><![CDATA[");
		sb.append(getJsgcgm());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fwjzmj</column-name><column-value><![CDATA[");
		sb.append(getFwjzmj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>htjg</column-name><column-value><![CDATA[");
		sb.append(getHtjg());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>htgq</column-name><column-value><![CDATA[");
		sb.append(getHtgq());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fddbr</column-name><column-value><![CDATA[");
		sb.append(getFddbr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsdwlxdh</column-name><column-value><![CDATA[");
		sb.append(getJsdwlxdh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsdwlxr</column-name><column-value><![CDATA[");
		sb.append(getJsdwlxr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsdwsjh</column-name><column-value><![CDATA[");
		sb.append(getJsdwsjh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsgcghxkzbh</column-name><column-value><![CDATA[");
		sb.append(getJsgcghxkzbh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xckgqk</column-name><column-value><![CDATA[");
		sb.append(getXckgqk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xmlx</column-name><column-value><![CDATA[");
		sb.append(getXmlx());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lxjb</column-name><column-value><![CDATA[");
		sb.append(getLxjb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xmxz</column-name><column-value><![CDATA[");
		sb.append(getXmxz());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ssqx</column-name><column-value><![CDATA[");
		sb.append(getSsqx());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ywbm</column-name><column-value><![CDATA[");
		sb.append(getYwbm());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsddssqx</column-name><column-value><![CDATA[");
		sb.append(getJsddssqx());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsgclb</column-name><column-value><![CDATA[");
		sb.append(getJsgclb());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsgcsx</column-name><column-value><![CDATA[");
		sb.append(getJsgcsx());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gyzjbz</column-name><column-value><![CDATA[");
		sb.append(getGyzjbz());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zbjg</column-name><column-value><![CDATA[");
		sb.append(getZbjg());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xmtzgs</column-name><column-value><![CDATA[");
		sb.append(getXmtzgs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jhkg</column-name><column-value><![CDATA[");
		sb.append(getJhkg());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jhjg</column-name><column-value><![CDATA[");
		sb.append(getJhjg());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sfzftzl</column-name><column-value><![CDATA[");
		sb.append(getSfzftzl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yzzpl1</column-name><column-value><![CDATA[");
		sb.append(getYzzpl1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yzzpl2</column-name><column-value><![CDATA[");
		sb.append(getYzzpl2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yzzpl3</column-name><column-value><![CDATA[");
		sb.append(getYzzpl3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yzzpl4</column-name><column-value><![CDATA[");
		sb.append(getYzzpl4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tjsj</column-name><column-value><![CDATA[");
		sb.append(getTjsj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gcnr</column-name><column-value><![CDATA[");
		sb.append(getGcnr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sgxkzsbz</column-name><column-value><![CDATA[");
		sb.append(getSgxkzsbz());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tzly</column-name><column-value><![CDATA[");
		sb.append(getTzly());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gkpzhhzjghwh</column-name><column-value><![CDATA[");
		sb.append(getGkpzhhzjghwh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pfhhzrq</column-name><column-value><![CDATA[");
		sb.append(getPfhhzrq());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cbsjpzjghwh</column-name><column-value><![CDATA[");
		sb.append(getCbsjpzjghwh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pfrq</column-name><column-value><![CDATA[");
		sb.append(getPfrq());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pfgq</column-name><column-value><![CDATA[");
		sb.append(getPfgq());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pzjghwh</column-name><column-value><![CDATA[");
		sb.append(getPzjghwh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xmdw</column-name><column-value><![CDATA[");
		sb.append(getXmdw());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xmfzr</column-name><column-value><![CDATA[");
		sb.append(getXmfzr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xmfzrlxdh</column-name><column-value><![CDATA[");
		sb.append(getXmfzrlxdh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zysjdw</column-name><column-value><![CDATA[");
		sb.append(getZysjdw());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sj_zbfs</column-name><column-value><![CDATA[");
		sb.append(getSj_zbfs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sj_zbj</column-name><column-value><![CDATA[");
		sb.append(getSj_zbj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sj_zzdj</column-name><column-value><![CDATA[");
		sb.append(getSj_zzdj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sj_zzdjzsbh</column-name><column-value><![CDATA[");
		sb.append(getSj_zzdjzsbh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sj_xmfzr</column-name><column-value><![CDATA[");
		sb.append(getSj_xmfzr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sj_xmfzrzsbh</column-name><column-value><![CDATA[");
		sb.append(getSj_xmfzrzsbh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zyjldw</column-name><column-value><![CDATA[");
		sb.append(getZyjldw());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jl_zbfs</column-name><column-value><![CDATA[");
		sb.append(getJl_zbfs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jl_zbj</column-name><column-value><![CDATA[");
		sb.append(getJl_zbj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jl_zzdj</column-name><column-value><![CDATA[");
		sb.append(getJl_zzdj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jl_zzdjzsbh</column-name><column-value><![CDATA[");
		sb.append(getJl_zzdjzsbh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jl_zj</column-name><column-value><![CDATA[");
		sb.append(getJl_zj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jl_zjzsbh</column-name><column-value><![CDATA[");
		sb.append(getJl_zjzsbh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zysgdw</column-name><column-value><![CDATA[");
		sb.append(getZysgdw());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sg_zbfs</column-name><column-value><![CDATA[");
		sb.append(getSg_zbfs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sg_zbj</column-name><column-value><![CDATA[");
		sb.append(getSg_zbj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sg_zzdj</column-name><column-value><![CDATA[");
		sb.append(getSg_zzdj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sg_zzdjzsbh</column-name><column-value><![CDATA[");
		sb.append(getSg_zzdjzsbh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sg_xmjl</column-name><column-value><![CDATA[");
		sb.append(getSg_xmjl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sg_xmjlzsbh</column-name><column-value><![CDATA[");
		sb.append(getSg_xmjlzsbh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jszjjhlsqk</column-name><column-value><![CDATA[");
		sb.append(getJszjjhlsqk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dcqwcqk</column-name><column-value><![CDATA[");
		sb.append(getDcqwcqk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sgzbqk</column-name><column-value><![CDATA[");
		sb.append(getSgzbqk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sytdxgwj</column-name><column-value><![CDATA[");
		sb.append(getSytdxgwj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gczljddjqk</column-name><column-value><![CDATA[");
		sb.append(getGczljddjqk());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ProjectProfile.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ProjectProfile.class
		};
	private long _permitId;
	private String _bjbh;
	private String _jsdwmc;
	private String _jsdwxz;
	private String _jsdwdz;
	private String _gcmc;
	private String _jsdd;
	private String _jsgcgm;
	private String _fwjzmj;
	private String _htjg;
	private int _htgq;
	private String _fddbr;
	private String _jsdwlxdh;
	private String _jsdwlxr;
	private String _jsdwsjh;
	private String _jsgcghxkzbh;
	private String _xckgqk;
	private long _xmlx;
	private String _lxjb;
	private long _xmxz;
	private String _ssqx;
	private String _ywbm;
	private long _jsddssqx;
	private String _jsgclb;
	private long _jsgcsx;
	private String _gyzjbz;
	private String _zbjg;
	private String _xmtzgs;
	private Date _jhkg;
	private Date _jhjg;
	private boolean _sfzftzl;
	private String _yzzpl1;
	private String _yzzpl2;
	private String _yzzpl3;
	private String _yzzpl4;
	private Date _tjsj;
	private String _gcnr;
	private String _sgxkzsbz;
	private String _tzly;
	private String _gkpzhhzjghwh;
	private Date _pfhhzrq;
	private String _cbsjpzjghwh;
	private Date _pfrq;
	private int _pfgq;
	private String _pzjghwh;
	private String _xmdw;
	private String _xmfzr;
	private String _xmfzrlxdh;
	private String _zysjdw;
	private String _sj_zbfs;
	private String _sj_zbj;
	private String _sj_zzdj;
	private String _sj_zzdjzsbh;
	private String _sj_xmfzr;
	private String _sj_xmfzrzsbh;
	private String _zyjldw;
	private String _jl_zbfs;
	private String _jl_zbj;
	private String _jl_zzdj;
	private String _jl_zzdjzsbh;
	private String _jl_zj;
	private String _jl_zjzsbh;
	private String _zysgdw;
	private String _sg_zbfs;
	private String _sg_zbj;
	private String _sg_zzdj;
	private String _sg_zzdjzsbh;
	private String _sg_xmjl;
	private String _sg_xmjlzsbh;
	private String _jszjjhlsqk;
	private String _dcqwcqk;
	private String _sgzbqk;
	private String _sytdxgwj;
	private String _gczljddjqk;
	private ProjectProfile _escapedModel;
}