$axure.loadCurrentPage({
  "url":"办公室主任审核.html",
  "generationDate":new Date(1434534636942.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"334ba9d7753f49f384baf0bc523a443b",
    "type":"Axure:Page",
    "name":"办公室主任审核",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b864e7de64db41a5ab60e2376ea6eb57",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":30},
            "size":{
              "width":760,
              "height":830}},
          "adaptiveStyles":{
}},
{
          "id":"ff8db74d147248dda8cee0d506cc03af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":30},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d847490059048ea80fd5e3c8695eaae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":30},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d63f2158ac140ac8ec6fc67f2c709ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":510},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b41aca0af38a45918098da86562ca478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":510},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f47951baf234eed9da32a241686943d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":503},
            "size":{
              "width":410,
              "height":57}},
          "adaptiveStyles":{
}},
{
          "id":"33d00ca8c2dd4a9e84aac6007737df23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":604},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4381e0df30c64c828d7d5aca91f56fa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":604},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d61baceedc494e66ae981a6669284724",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":56},
            "size":{
              "width":742,
              "height":414}},
          "adaptiveStyles":{
}},
{
          "id":"1f13b6dc1dab440aa628650fb53114d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":56},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb470474763149b6ac28950925987136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":56},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27e9a27d8ccf479e809a9a865650dcea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":330},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e777fa98d464b37b2dc7a08b1644666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":330},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35e34beec77c48798634d0f130b29c44",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":102},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"aca0b06ee84742f08ade1ff52fd36918",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":102},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b689af57a008456fafddfba1d4cba906",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":102},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a8fb0a3cb18b4476a020e0c52fcdfbc1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":102},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e51cbd9db910475c865aaca811ee7af3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":106},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96aeff978a104d2e885872ecfa664935",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":106},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83b65dcdb45740fe86a554e54f2a41d3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":146},
            "size":{
              "width":742,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de60404c49564a3dbcd672f13b162b6a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6cdcae1055d42b3a38898e4b14268b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u12.png"}},
{
              "id":"f7b6dd888873401d8b104008ec87ec4a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aef0625041ec45ca8f6a4ba264d5c98e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u22.png"}},
{
              "id":"0437af5313884c61b19192ef899e461a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5fd0a26c86364049af0ff37b3bc1add5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u22.png"}},
{
              "id":"55010c00d54c4a018650e8583a3ef0f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":342,
                  "y":0},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2d31fdeeb904bedac3a2ec18feda934",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":342,
                      "y":0},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u16.png"}},
{
              "id":"c899fd0594594b3d85c5c09a58531015",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":30},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4d3379bf2d6e46ca8cfc68792c8d05d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":30},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u26.png"}},
{
              "id":"a85379b95f594a058ef71e0296be620c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":60},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f171c34875f46cda129bb5c92dfb2c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":60},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u26.png"}},
{
              "id":"a656756089e34b16aff9d84c7b6d688d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":589,
                  "y":0},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"339a7d3ac4ee4d42863bc6046b3f1354",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":589,
                      "y":0},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u20.png"}},
{
              "id":"f9080097b60c46bbb90e009fe312019e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":589,
                  "y":30},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"466ed243178f4ec69d72002ac23245bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":589,
                      "y":30},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u30.png"}},
{
              "id":"f9b8da1431354715b472be1e1d665a89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":589,
                  "y":60},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fe07052a1a646a1b87ef25ee22eb403",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":589,
                      "y":60},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u30.png"}},
{
              "id":"ad245c3e223f481098ebffe9eb39ec61",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b55c7766c0044ed387e5d5cfb7495993",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u42.png"}},
{
              "id":"a0f51615efb64389bd433ea029810361",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":90},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b46ea1119d054444a2635e97740e84d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":90},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u46.png"}},
{
              "id":"136be857e10c4e648f6f12d5ddb88f58",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":589,
                  "y":90},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2954cb033d8b4845879d91cb82b4db9a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":589,
                      "y":90},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u50.png"}},
{
              "id":"1a74a84d201c46de8199a5022d1e6a86",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":209,
                  "y":0},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f6950272c9142bd90fa1cd580678aee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":209,
                      "y":0},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u14.png"}},
{
              "id":"73839e7c358c49bc9e015e5f7db31630",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":30},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5447fa1a11f943c3b5c000c9b77daa7f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":30},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u24.png"}},
{
              "id":"c615b7bd70be43a4b5c82d34a1bd0a11",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":60},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12980d5010c14f4bb5482e996f2397ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":60},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u24.png"}},
{
              "id":"70bb55d9c1bb49eaa8310777f203ce78",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":90},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3208d2de88cb48b2acf5e26bbd5ccd0f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":90},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u44.png"}},
{
              "id":"0dca91961d8d425aa2044e79912370a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":453,
                  "y":0},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e1b590fc78e4ad5ba498d48d6647ccc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":453,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u18.png"}},
{
              "id":"abeafd94a6fd469bafa45ddd8c275e4a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":453,
                  "y":30},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"908ce56f9dcd4d0288b1be3c6c8e515f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":453,
                      "y":30},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u28.png"}},
{
              "id":"0402ee1ee5ef480eb578936560ad6686",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":453,
                  "y":60},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"82b7d2f026b643faacd7594dbef5fb2c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":453,
                      "y":60},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u28.png"}},
{
              "id":"56ac93c4c24143debfbc6f00ea2327fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":453,
                  "y":90},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"69e283c43b5a45369cc3debc93383d3f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":453,
                      "y":90},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u48.png"}}]},
{
          "id":"464dc49e563943f6bd1e5378471a3a14",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":326},
            "size":{
              "width":390,
              "height":120}},
          "adaptiveStyles":{
}},
{
          "id":"007e7b1b25f549d0934ecddea0872a6c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":149},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"088f8d63b28d4236aace276cc946f29f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":179},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"97bc156103114bce8f4fb3b9ef134acf",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":209},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"abb23887b1b84fcba2c1e5af86c9d9ce",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":266},
            "size":{
              "width":742,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fee6887afce4d02ac2fc8a97ef731b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a0077c80fc7f4a51b81bb0f46b6d74d7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u42.png"}},
{
              "id":"1e0df8bdc92a465fb743fd256ffbf5f3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":0},
                "size":{
                  "width":533,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2f3eeaf8e1042929e81765c7eda0060",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":0},
                    "size":{
                      "width":533,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u62.png"}}]},
{
          "id":"68bde941de4c46a4bfb54a2120c76817",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":600},
            "size":{
              "width":390,
              "height":80}},
          "adaptiveStyles":{
}},
{
          "id":"13ad57ba382c467cb420eeafe2382fd0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":795},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"081a54a81f13435caf4bb393803ab643",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":795},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"500f72dfc2df4ceda5f8ea7873e6f4b9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":795},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8e708c3fb8d44b50b962cd6636414a48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":734},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a48bc416d7514fa1bfba59e5a97073e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":734},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e64480cf5244a3fa145d7402928dd74",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":729.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"596b8f0bc1824d10bbde556b6f53fc21",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":730},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2ae1b1496b8c489e90147140dbb94c6e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":570},
            "size":{
              "width":760,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/办公室主任审核/u77_line.png"}},
{
          "id":"02e7a7f767c64f7c96eb5c72255eeb4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":614,
              "y":632},
            "size":{
              "width":166,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"746531276d4b4931af7b6d6d55277b2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":614,
                  "y":632},
                "size":{
                  "width":166,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b864e7de64db41a5ab60e2376ea6eb57":{
      "scriptId":"u0"},
    "ff8db74d147248dda8cee0d506cc03af":{
      "scriptId":"u1"},
    "7d847490059048ea80fd5e3c8695eaae":{
      "scriptId":"u2"},
    "0d63f2158ac140ac8ec6fc67f2c709ee":{
      "scriptId":"u3"},
    "b41aca0af38a45918098da86562ca478":{
      "scriptId":"u4"},
    "4f47951baf234eed9da32a241686943d":{
      "scriptId":"u5"},
    "33d00ca8c2dd4a9e84aac6007737df23":{
      "scriptId":"u6"},
    "4381e0df30c64c828d7d5aca91f56fa1":{
      "scriptId":"u7"},
    "d61baceedc494e66ae981a6669284724":{
      "scriptId":"u8"},
    "1f13b6dc1dab440aa628650fb53114d6":{
      "scriptId":"u9"},
    "bb470474763149b6ac28950925987136":{
      "scriptId":"u10"},
    "27e9a27d8ccf479e809a9a865650dcea":{
      "scriptId":"u11"},
    "2e777fa98d464b37b2dc7a08b1644666":{
      "scriptId":"u12"},
    "35e34beec77c48798634d0f130b29c44":{
      "scriptId":"u13"},
    "aca0b06ee84742f08ade1ff52fd36918":{
      "scriptId":"u14"},
    "b689af57a008456fafddfba1d4cba906":{
      "scriptId":"u15"},
    "a8fb0a3cb18b4476a020e0c52fcdfbc1":{
      "scriptId":"u16"},
    "e51cbd9db910475c865aaca811ee7af3":{
      "scriptId":"u17"},
    "96aeff978a104d2e885872ecfa664935":{
      "scriptId":"u18"},
    "83b65dcdb45740fe86a554e54f2a41d3":{
      "scriptId":"u19"},
    "de60404c49564a3dbcd672f13b162b6a":{
      "scriptId":"u20"},
    "b6cdcae1055d42b3a38898e4b14268b2":{
      "scriptId":"u21"},
    "1a74a84d201c46de8199a5022d1e6a86":{
      "scriptId":"u22"},
    "2f6950272c9142bd90fa1cd580678aee":{
      "scriptId":"u23"},
    "55010c00d54c4a018650e8583a3ef0f0":{
      "scriptId":"u24"},
    "e2d31fdeeb904bedac3a2ec18feda934":{
      "scriptId":"u25"},
    "0dca91961d8d425aa2044e79912370a3":{
      "scriptId":"u26"},
    "7e1b590fc78e4ad5ba498d48d6647ccc":{
      "scriptId":"u27"},
    "a656756089e34b16aff9d84c7b6d688d":{
      "scriptId":"u28"},
    "339a7d3ac4ee4d42863bc6046b3f1354":{
      "scriptId":"u29"},
    "f7b6dd888873401d8b104008ec87ec4a":{
      "scriptId":"u30"},
    "aef0625041ec45ca8f6a4ba264d5c98e":{
      "scriptId":"u31"},
    "73839e7c358c49bc9e015e5f7db31630":{
      "scriptId":"u32"},
    "5447fa1a11f943c3b5c000c9b77daa7f":{
      "scriptId":"u33"},
    "c899fd0594594b3d85c5c09a58531015":{
      "scriptId":"u34"},
    "4d3379bf2d6e46ca8cfc68792c8d05d0":{
      "scriptId":"u35"},
    "abeafd94a6fd469bafa45ddd8c275e4a":{
      "scriptId":"u36"},
    "908ce56f9dcd4d0288b1be3c6c8e515f":{
      "scriptId":"u37"},
    "f9080097b60c46bbb90e009fe312019e":{
      "scriptId":"u38"},
    "466ed243178f4ec69d72002ac23245bf":{
      "scriptId":"u39"},
    "0437af5313884c61b19192ef899e461a":{
      "scriptId":"u40"},
    "5fd0a26c86364049af0ff37b3bc1add5":{
      "scriptId":"u41"},
    "c615b7bd70be43a4b5c82d34a1bd0a11":{
      "scriptId":"u42"},
    "12980d5010c14f4bb5482e996f2397ae":{
      "scriptId":"u43"},
    "a85379b95f594a058ef71e0296be620c":{
      "scriptId":"u44"},
    "7f171c34875f46cda129bb5c92dfb2c3":{
      "scriptId":"u45"},
    "0402ee1ee5ef480eb578936560ad6686":{
      "scriptId":"u46"},
    "82b7d2f026b643faacd7594dbef5fb2c":{
      "scriptId":"u47"},
    "f9b8da1431354715b472be1e1d665a89":{
      "scriptId":"u48"},
    "1fe07052a1a646a1b87ef25ee22eb403":{
      "scriptId":"u49"},
    "ad245c3e223f481098ebffe9eb39ec61":{
      "scriptId":"u50"},
    "b55c7766c0044ed387e5d5cfb7495993":{
      "scriptId":"u51"},
    "70bb55d9c1bb49eaa8310777f203ce78":{
      "scriptId":"u52"},
    "3208d2de88cb48b2acf5e26bbd5ccd0f":{
      "scriptId":"u53"},
    "a0f51615efb64389bd433ea029810361":{
      "scriptId":"u54"},
    "b46ea1119d054444a2635e97740e84d0":{
      "scriptId":"u55"},
    "56ac93c4c24143debfbc6f00ea2327fc":{
      "scriptId":"u56"},
    "69e283c43b5a45369cc3debc93383d3f":{
      "scriptId":"u57"},
    "136be857e10c4e648f6f12d5ddb88f58":{
      "scriptId":"u58"},
    "2954cb033d8b4845879d91cb82b4db9a":{
      "scriptId":"u59"},
    "464dc49e563943f6bd1e5378471a3a14":{
      "scriptId":"u60"},
    "007e7b1b25f549d0934ecddea0872a6c":{
      "scriptId":"u61"},
    "088f8d63b28d4236aace276cc946f29f":{
      "scriptId":"u62"},
    "97bc156103114bce8f4fb3b9ef134acf":{
      "scriptId":"u63"},
    "abb23887b1b84fcba2c1e5af86c9d9ce":{
      "scriptId":"u64"},
    "2fee6887afce4d02ac2fc8a97ef731b6":{
      "scriptId":"u65"},
    "a0077c80fc7f4a51b81bb0f46b6d74d7":{
      "scriptId":"u66"},
    "1e0df8bdc92a465fb743fd256ffbf5f3":{
      "scriptId":"u67"},
    "f2f3eeaf8e1042929e81765c7eda0060":{
      "scriptId":"u68"},
    "68bde941de4c46a4bfb54a2120c76817":{
      "scriptId":"u69"},
    "13ad57ba382c467cb420eeafe2382fd0":{
      "scriptId":"u70"},
    "081a54a81f13435caf4bb393803ab643":{
      "scriptId":"u71"},
    "500f72dfc2df4ceda5f8ea7873e6f4b9":{
      "scriptId":"u72"},
    "8e708c3fb8d44b50b962cd6636414a48":{
      "scriptId":"u73"},
    "a48bc416d7514fa1bfba59e5a97073e8":{
      "scriptId":"u74"},
    "2e64480cf5244a3fa145d7402928dd74":{
      "scriptId":"u75"},
    "596b8f0bc1824d10bbde556b6f53fc21":{
      "scriptId":"u76"},
    "2ae1b1496b8c489e90147140dbb94c6e":{
      "scriptId":"u77"},
    "02e7a7f767c64f7c96eb5c72255eeb4c":{
      "scriptId":"u78"},
    "746531276d4b4931af7b6d6d55277b2f":{
      "scriptId":"u79"}}});