$axure.loadCurrentPage({
  "url":"收文管理.html",
  "generationDate":new Date(1434534637234),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4fc9ac611dbe4ce0b7ab0d7a0a64de89",
    "type":"Axure:Page",
    "name":"收文管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c174ca98573d447ca02cdf8721b31b0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":196,
              "y":-26},
            "size":{
              "width":467,
              "height":620}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af9bffe0b6d040649264cf2ad8c55fab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":196,
                  "y":-26},
                "size":{
                  "width":467,
                  "height":620}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收文管理/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "c174ca98573d447ca02cdf8721b31b0c":{
      "scriptId":"u0"},
    "af9bffe0b6d040649264cf2ad8c55fab":{
      "scriptId":"u1"}}});