$axure.loadCurrentPage({
  "url":"添加编辑页面_2.html",
  "generationDate":new Date(1434534637266.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1de9c5786030468b8ecd27dce635b9fb",
    "type":"Axure:Page",
    "name":"添加编辑页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"529b59d2f677456ba5dbf9c144ff23e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":16},
            "size":{
              "width":757,
              "height":514}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83cd15cd4902441e8ec87f588f397fb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":16},
                "size":{
                  "width":757,
                  "height":514}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加编辑页面_2/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "529b59d2f677456ba5dbf9c144ff23e6":{
      "scriptId":"u0"},
    "83cd15cd4902441e8ec87f588f397fb4":{
      "scriptId":"u1"}}});