/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.projApproval.service.base;

import com.justonetech.projApproval.model.ConstructionPermit;
import com.justonetech.projApproval.service.ConstructionPermitService;
import com.justonetech.projApproval.service.persistence.ConstructionParticipantUnitsPersistence;
import com.justonetech.projApproval.service.persistence.ConstructionPermitPersistence;
import com.justonetech.projApproval.service.persistence.ConstructionUnitProjectPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the construction permit remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.justonetech.projApproval.service.impl.ConstructionPermitServiceImpl}.
 * </p>
 *
 * @author justonetech
 * @see com.justonetech.projApproval.service.impl.ConstructionPermitServiceImpl
 * @see com.justonetech.projApproval.service.ConstructionPermitServiceUtil
 * @generated
 */
public abstract class ConstructionPermitServiceBaseImpl extends BaseServiceImpl
	implements ConstructionPermitService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.justonetech.projApproval.service.ConstructionPermitServiceUtil} to access the construction permit remote service.
	 */

	/**
	 * Returns the construction participant units local service.
	 *
	 * @return the construction participant units local service
	 */
	public com.justonetech.projApproval.service.ConstructionParticipantUnitsLocalService getConstructionParticipantUnitsLocalService() {
		return constructionParticipantUnitsLocalService;
	}

	/**
	 * Sets the construction participant units local service.
	 *
	 * @param constructionParticipantUnitsLocalService the construction participant units local service
	 */
	public void setConstructionParticipantUnitsLocalService(
		com.justonetech.projApproval.service.ConstructionParticipantUnitsLocalService constructionParticipantUnitsLocalService) {
		this.constructionParticipantUnitsLocalService = constructionParticipantUnitsLocalService;
	}

	/**
	 * Returns the construction participant units persistence.
	 *
	 * @return the construction participant units persistence
	 */
	public ConstructionParticipantUnitsPersistence getConstructionParticipantUnitsPersistence() {
		return constructionParticipantUnitsPersistence;
	}

	/**
	 * Sets the construction participant units persistence.
	 *
	 * @param constructionParticipantUnitsPersistence the construction participant units persistence
	 */
	public void setConstructionParticipantUnitsPersistence(
		ConstructionParticipantUnitsPersistence constructionParticipantUnitsPersistence) {
		this.constructionParticipantUnitsPersistence = constructionParticipantUnitsPersistence;
	}

	/**
	 * Returns the construction permit local service.
	 *
	 * @return the construction permit local service
	 */
	public com.justonetech.projApproval.service.ConstructionPermitLocalService getConstructionPermitLocalService() {
		return constructionPermitLocalService;
	}

	/**
	 * Sets the construction permit local service.
	 *
	 * @param constructionPermitLocalService the construction permit local service
	 */
	public void setConstructionPermitLocalService(
		com.justonetech.projApproval.service.ConstructionPermitLocalService constructionPermitLocalService) {
		this.constructionPermitLocalService = constructionPermitLocalService;
	}

	/**
	 * Returns the construction permit remote service.
	 *
	 * @return the construction permit remote service
	 */
	public com.justonetech.projApproval.service.ConstructionPermitService getConstructionPermitService() {
		return constructionPermitService;
	}

	/**
	 * Sets the construction permit remote service.
	 *
	 * @param constructionPermitService the construction permit remote service
	 */
	public void setConstructionPermitService(
		com.justonetech.projApproval.service.ConstructionPermitService constructionPermitService) {
		this.constructionPermitService = constructionPermitService;
	}

	/**
	 * Returns the construction permit persistence.
	 *
	 * @return the construction permit persistence
	 */
	public ConstructionPermitPersistence getConstructionPermitPersistence() {
		return constructionPermitPersistence;
	}

	/**
	 * Sets the construction permit persistence.
	 *
	 * @param constructionPermitPersistence the construction permit persistence
	 */
	public void setConstructionPermitPersistence(
		ConstructionPermitPersistence constructionPermitPersistence) {
		this.constructionPermitPersistence = constructionPermitPersistence;
	}

	/**
	 * Returns the construction unit project local service.
	 *
	 * @return the construction unit project local service
	 */
	public com.justonetech.projApproval.service.ConstructionUnitProjectLocalService getConstructionUnitProjectLocalService() {
		return constructionUnitProjectLocalService;
	}

	/**
	 * Sets the construction unit project local service.
	 *
	 * @param constructionUnitProjectLocalService the construction unit project local service
	 */
	public void setConstructionUnitProjectLocalService(
		com.justonetech.projApproval.service.ConstructionUnitProjectLocalService constructionUnitProjectLocalService) {
		this.constructionUnitProjectLocalService = constructionUnitProjectLocalService;
	}

	/**
	 * Returns the construction unit project persistence.
	 *
	 * @return the construction unit project persistence
	 */
	public ConstructionUnitProjectPersistence getConstructionUnitProjectPersistence() {
		return constructionUnitProjectPersistence;
	}

	/**
	 * Sets the construction unit project persistence.
	 *
	 * @param constructionUnitProjectPersistence the construction unit project persistence
	 */
	public void setConstructionUnitProjectPersistence(
		ConstructionUnitProjectPersistence constructionUnitProjectPersistence) {
		this.constructionUnitProjectPersistence = constructionUnitProjectPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return ConstructionPermit.class;
	}

	protected String getModelClassName() {
		return ConstructionPermit.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = constructionPermitPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.justonetech.projApproval.service.ConstructionParticipantUnitsLocalService.class)
	protected com.justonetech.projApproval.service.ConstructionParticipantUnitsLocalService constructionParticipantUnitsLocalService;
	@BeanReference(type = ConstructionParticipantUnitsPersistence.class)
	protected ConstructionParticipantUnitsPersistence constructionParticipantUnitsPersistence;
	@BeanReference(type = com.justonetech.projApproval.service.ConstructionPermitLocalService.class)
	protected com.justonetech.projApproval.service.ConstructionPermitLocalService constructionPermitLocalService;
	@BeanReference(type = com.justonetech.projApproval.service.ConstructionPermitService.class)
	protected com.justonetech.projApproval.service.ConstructionPermitService constructionPermitService;
	@BeanReference(type = ConstructionPermitPersistence.class)
	protected ConstructionPermitPersistence constructionPermitPersistence;
	@BeanReference(type = com.justonetech.projApproval.service.ConstructionUnitProjectLocalService.class)
	protected com.justonetech.projApproval.service.ConstructionUnitProjectLocalService constructionUnitProjectLocalService;
	@BeanReference(type = ConstructionUnitProjectPersistence.class)
	protected ConstructionUnitProjectPersistence constructionUnitProjectPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ConstructionPermitServiceClpInvoker _clpInvoker = new ConstructionPermitServiceClpInvoker();
}