$axure.loadCurrentPage({
  "url":"科长审核页面.html",
  "generationDate":new Date(1434534636874.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"61f9892385414603a687749cdd25e30d",
    "type":"Axure:Page",
    "name":"科长审核页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"794909bd411b4bbf8ce90767467ae410",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":30},
            "size":{
              "width":760,
              "height":710}},
          "adaptiveStyles":{
}},
{
          "id":"14323db79ba74fa8b179c909664c58d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":30},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24cc5ac2be6c451e8c6a45a9daaee0b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":30},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"530a2d9433444ab89671d9cda1b9177b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":564},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8497c800663f42ff9abea025a68dd4ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":564},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8902dad0e5b94efcadf8a2283eebcaee",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":550},
            "size":{
              "width":410,
              "height":110}},
          "adaptiveStyles":{
}},
{
          "id":"8b155486df744d8bbc4cc03f48fdba60",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":685},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1e65187279c54a8ea7e06909982afd68",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":685},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a6ddec42ffb1456699711c24a1a55b8c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":685},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9d6082e21d3b45c9b0b71057092927a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":494},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b548e2bd81284e719681f60785aa0572",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":494},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9b6d69759fc4c3c9001dcb584bcb8f4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":56},
            "size":{
              "width":742,
              "height":414}},
          "adaptiveStyles":{
}},
{
          "id":"547fa8f097624b11900e9cbc47b86c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":56},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fd842b0e8224309a73e3bd8bae99d46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":56},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a64cac46a2e14a1dade011bd3a4941a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":330},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b76ddbc07cb471699953467d57869cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":330},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f1035e0b75f465d82ff36e2ded72473",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":102},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"46b00674128b42389a6734cac4994d92",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":102},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c5cb12f0ec064c90aec6fe1a13dca686",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":102},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9cc09573d19446d3b0bf93222d5bbb17",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":102},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"50cfacd095b447319cd3f4f94ca74ed2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":106},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a68649960041b5af00d37f375cc623",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":106},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f40d5b12ebab418e84c77ff4f5e560e2",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":146},
            "size":{
              "width":742,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36b472494ebe40498489d7c6171655d1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5cd018dee7fd4ea1933f159a3f726cec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u12.png"}},
{
              "id":"b78f54f854414c4a87bbdf57a7d5fdc3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57d01dfab0b44f9e8cfb3dda51a2004c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u22.png"}},
{
              "id":"9dcd99963dee405291fcd6258cbb1646",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05f0e82b0df9438fa1ea8f8b1bb045bc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u22.png"}},
{
              "id":"ca3c955961a54eb4af2d9981fd8a1fd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":342,
                  "y":0},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6dd789ceaa64aea87e135cbd3174bad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":342,
                      "y":0},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u16.png"}},
{
              "id":"cb87480c067b49c7812693b1511cd522",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":30},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d4b0865afa984d51a0b4eca3447036e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":30},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u26.png"}},
{
              "id":"6a15381930e74e21a25ee7025745fb47",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":60},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"114c60a02b244152983704558bb338f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":60},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u26.png"}},
{
              "id":"fbc31d7966bb4b22b19064691c7c3df0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":589,
                  "y":0},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"061804ad643345beab3a0e238bf23356",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":589,
                      "y":0},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u20.png"}},
{
              "id":"44f9507672e64537b05c9cc5d2b738b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":589,
                  "y":30},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"256775570fe94d76aedbe85a4ec7afd9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":589,
                      "y":30},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u30.png"}},
{
              "id":"385b4625e8c64ea1b183d4170e6021a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":589,
                  "y":60},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"51e7063c45c5460783a81051c0d7a952",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":589,
                      "y":60},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u30.png"}},
{
              "id":"edf4795e1907472c9900238c2043255a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac4648ee67ed4529a63c6a581dafbb0b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u42.png"}},
{
              "id":"1c6af1d9fed94c12a7d418a154eb63ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":342,
                  "y":90},
                "size":{
                  "width":111,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"222aca5eed0340baa697b602a7ddb190",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":342,
                      "y":90},
                    "size":{
                      "width":111,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u46.png"}},
{
              "id":"669486130eff42e3bba6d043f9bf68a1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":589,
                  "y":90},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dceb29d1e997435a85a24a82324af6ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":589,
                      "y":90},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u50.png"}},
{
              "id":"a8d670604a3e4426b69ce9e5733b15a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":209,
                  "y":0},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4f303893d0049388a9183cc4cfd5625",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":209,
                      "y":0},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u14.png"}},
{
              "id":"c516ca01ef2141b8823968b10f2caad8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":30},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cd15ef3241be4115be6289cdd4f2be72",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":30},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u24.png"}},
{
              "id":"83b4b9b55f1049d389488aa88a70fa12",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":60},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f04a268f7a34c27a803e9e5851c6338",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":60},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u24.png"}},
{
              "id":"d8a0de0bb7ab46e1acce5206f11e4ff8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":90},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90d97bf007dc4cb0b3e4898e22740b32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":90},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u44.png"}},
{
              "id":"e194e20eb8cf4513aa21d43018cd83a0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99FF99},
                "location":{
                  "x":453,
                  "y":0},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"80f7865ffe994805937b816072bdcd6c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF99FF99},
                    "location":{
                      "x":453,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u18.png"}},
{
              "id":"40fec9a760e84feebe30c2f21387ed5c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":453,
                  "y":30},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a02c7ffd6f547b0b98e1ec01ffbd92a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":453,
                      "y":30},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u28.png"}},
{
              "id":"37d4db85ab9448c1a27dc91dd22b6bd9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":453,
                  "y":60},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06dae26954794bebbeb32603ba05bf4f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":453,
                      "y":60},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u28.png"}},
{
              "id":"65eeb21fa64243a8b0f75e5b35247d20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":453,
                  "y":90},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ff0a1b617d540c6b30c317814b56101",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":453,
                      "y":90},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u48.png"}}]},
{
          "id":"a731626e60054367bd015d1bf4967665",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":326},
            "size":{
              "width":390,
              "height":120}},
          "adaptiveStyles":{
}},
{
          "id":"8ef4b7bee73d405c8a49e8c66a702590",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":149},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"93323717ebd94c5d93991c8bdab0959f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":179},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ac33424662c7468699facc3109b420ce",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":209},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a9013049a09e4f00a69a8246fded9843",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":266},
            "size":{
              "width":742,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7375d21ca94f4f61999a0931c6ba3cce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f300317a693b4359b96ff2adb24191e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u42.png"}},
{
              "id":"cde53f88ba0d4026b651820451e9e624",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":209,
                  "y":0},
                "size":{
                  "width":533,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dccc66a0d52443da14e45473d42fc6d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":209,
                      "y":0},
                    "size":{
                      "width":533,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请编辑页面/u62.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "794909bd411b4bbf8ce90767467ae410":{
      "scriptId":"u0"},
    "14323db79ba74fa8b179c909664c58d9":{
      "scriptId":"u1"},
    "24cc5ac2be6c451e8c6a45a9daaee0b1":{
      "scriptId":"u2"},
    "530a2d9433444ab89671d9cda1b9177b":{
      "scriptId":"u3"},
    "8497c800663f42ff9abea025a68dd4ca":{
      "scriptId":"u4"},
    "8902dad0e5b94efcadf8a2283eebcaee":{
      "scriptId":"u5"},
    "8b155486df744d8bbc4cc03f48fdba60":{
      "scriptId":"u6"},
    "1e65187279c54a8ea7e06909982afd68":{
      "scriptId":"u7"},
    "a6ddec42ffb1456699711c24a1a55b8c":{
      "scriptId":"u8"},
    "9d6082e21d3b45c9b0b71057092927a3":{
      "scriptId":"u9"},
    "b548e2bd81284e719681f60785aa0572":{
      "scriptId":"u10"},
    "a9b6d69759fc4c3c9001dcb584bcb8f4":{
      "scriptId":"u11"},
    "547fa8f097624b11900e9cbc47b86c95":{
      "scriptId":"u12"},
    "9fd842b0e8224309a73e3bd8bae99d46":{
      "scriptId":"u13"},
    "a64cac46a2e14a1dade011bd3a4941a2":{
      "scriptId":"u14"},
    "3b76ddbc07cb471699953467d57869cc":{
      "scriptId":"u15"},
    "8f1035e0b75f465d82ff36e2ded72473":{
      "scriptId":"u16"},
    "46b00674128b42389a6734cac4994d92":{
      "scriptId":"u17"},
    "c5cb12f0ec064c90aec6fe1a13dca686":{
      "scriptId":"u18"},
    "9cc09573d19446d3b0bf93222d5bbb17":{
      "scriptId":"u19"},
    "50cfacd095b447319cd3f4f94ca74ed2":{
      "scriptId":"u20"},
    "10a68649960041b5af00d37f375cc623":{
      "scriptId":"u21"},
    "f40d5b12ebab418e84c77ff4f5e560e2":{
      "scriptId":"u22"},
    "36b472494ebe40498489d7c6171655d1":{
      "scriptId":"u23"},
    "5cd018dee7fd4ea1933f159a3f726cec":{
      "scriptId":"u24"},
    "a8d670604a3e4426b69ce9e5733b15a9":{
      "scriptId":"u25"},
    "b4f303893d0049388a9183cc4cfd5625":{
      "scriptId":"u26"},
    "ca3c955961a54eb4af2d9981fd8a1fd4":{
      "scriptId":"u27"},
    "c6dd789ceaa64aea87e135cbd3174bad":{
      "scriptId":"u28"},
    "e194e20eb8cf4513aa21d43018cd83a0":{
      "scriptId":"u29"},
    "80f7865ffe994805937b816072bdcd6c":{
      "scriptId":"u30"},
    "fbc31d7966bb4b22b19064691c7c3df0":{
      "scriptId":"u31"},
    "061804ad643345beab3a0e238bf23356":{
      "scriptId":"u32"},
    "b78f54f854414c4a87bbdf57a7d5fdc3":{
      "scriptId":"u33"},
    "57d01dfab0b44f9e8cfb3dda51a2004c":{
      "scriptId":"u34"},
    "c516ca01ef2141b8823968b10f2caad8":{
      "scriptId":"u35"},
    "cd15ef3241be4115be6289cdd4f2be72":{
      "scriptId":"u36"},
    "cb87480c067b49c7812693b1511cd522":{
      "scriptId":"u37"},
    "d4b0865afa984d51a0b4eca3447036e5":{
      "scriptId":"u38"},
    "40fec9a760e84feebe30c2f21387ed5c":{
      "scriptId":"u39"},
    "1a02c7ffd6f547b0b98e1ec01ffbd92a":{
      "scriptId":"u40"},
    "44f9507672e64537b05c9cc5d2b738b6":{
      "scriptId":"u41"},
    "256775570fe94d76aedbe85a4ec7afd9":{
      "scriptId":"u42"},
    "9dcd99963dee405291fcd6258cbb1646":{
      "scriptId":"u43"},
    "05f0e82b0df9438fa1ea8f8b1bb045bc":{
      "scriptId":"u44"},
    "83b4b9b55f1049d389488aa88a70fa12":{
      "scriptId":"u45"},
    "2f04a268f7a34c27a803e9e5851c6338":{
      "scriptId":"u46"},
    "6a15381930e74e21a25ee7025745fb47":{
      "scriptId":"u47"},
    "114c60a02b244152983704558bb338f7":{
      "scriptId":"u48"},
    "37d4db85ab9448c1a27dc91dd22b6bd9":{
      "scriptId":"u49"},
    "06dae26954794bebbeb32603ba05bf4f":{
      "scriptId":"u50"},
    "385b4625e8c64ea1b183d4170e6021a2":{
      "scriptId":"u51"},
    "51e7063c45c5460783a81051c0d7a952":{
      "scriptId":"u52"},
    "edf4795e1907472c9900238c2043255a":{
      "scriptId":"u53"},
    "ac4648ee67ed4529a63c6a581dafbb0b":{
      "scriptId":"u54"},
    "d8a0de0bb7ab46e1acce5206f11e4ff8":{
      "scriptId":"u55"},
    "90d97bf007dc4cb0b3e4898e22740b32":{
      "scriptId":"u56"},
    "1c6af1d9fed94c12a7d418a154eb63ea":{
      "scriptId":"u57"},
    "222aca5eed0340baa697b602a7ddb190":{
      "scriptId":"u58"},
    "65eeb21fa64243a8b0f75e5b35247d20":{
      "scriptId":"u59"},
    "2ff0a1b617d540c6b30c317814b56101":{
      "scriptId":"u60"},
    "669486130eff42e3bba6d043f9bf68a1":{
      "scriptId":"u61"},
    "dceb29d1e997435a85a24a82324af6ae":{
      "scriptId":"u62"},
    "a731626e60054367bd015d1bf4967665":{
      "scriptId":"u63"},
    "8ef4b7bee73d405c8a49e8c66a702590":{
      "scriptId":"u64"},
    "93323717ebd94c5d93991c8bdab0959f":{
      "scriptId":"u65"},
    "ac33424662c7468699facc3109b420ce":{
      "scriptId":"u66"},
    "a9013049a09e4f00a69a8246fded9843":{
      "scriptId":"u67"},
    "7375d21ca94f4f61999a0931c6ba3cce":{
      "scriptId":"u68"},
    "f300317a693b4359b96ff2adb24191e0":{
      "scriptId":"u69"},
    "cde53f88ba0d4026b651820451e9e624":{
      "scriptId":"u70"},
    "5dccc66a0d52443da14e45473d42fc6d":{
      "scriptId":"u71"}}});