$axure.loadCurrentPage({
  "url":"承担项目.html",
  "generationDate":new Date(1430724551669.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d56ab829c431475e985e62210edb05b1",
    "type":"Axure:Page",
    "name":"承担项目",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f796511f0398445a8af8f5c9a97e5bb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":800,
              "height":402}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12ce27499ac84a40908ad9306003ec51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":0},
                "size":{
                  "width":800,
                  "height":402}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承担项目/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f796511f0398445a8af8f5c9a97e5bb5":{
      "scriptId":"u0"},
    "12ce27499ac84a40908ad9306003ec51":{
      "scriptId":"u1"}}});