/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.expert.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Zzjl service. Represents a row in the &quot;expert_Zzjl&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.justonetech.expert.model.impl.ZzjlModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.justonetech.expert.model.impl.ZzjlImpl}.
 * </p>
 *
 * @author fanqi
 * @see Zzjl
 * @see com.justonetech.expert.model.impl.ZzjlImpl
 * @see com.justonetech.expert.model.impl.ZzjlModelImpl
 * @generated
 */
public interface ZzjlModel extends BaseModel<Zzjl> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a zzjl model instance should use the {@link Zzjl} interface instead.
	 */

	/**
	 * Returns the primary key of this zzjl.
	 *
	 * @return the primary key of this zzjl
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this zzjl.
	 *
	 * @param primaryKey the primary key of this zzjl
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the zzjl ID of this zzjl.
	 *
	 * @return the zzjl ID of this zzjl
	 */
	public long getZzjlId();

	/**
	 * Sets the zzjl ID of this zzjl.
	 *
	 * @param zzjlId the zzjl ID of this zzjl
	 */
	public void setZzjlId(long zzjlId);

	/**
	 * Returns the expert ID of this zzjl.
	 *
	 * @return the expert ID of this zzjl
	 */
	@AutoEscape
	public String getExpertId();

	/**
	 * Sets the expert ID of this zzjl.
	 *
	 * @param expertId the expert ID of this zzjl
	 */
	public void setExpertId(String expertId);

	/**
	 * Returns the zzdw of this zzjl.
	 *
	 * @return the zzdw of this zzjl
	 */
	@AutoEscape
	public String getZzdw();

	/**
	 * Sets the zzdw of this zzjl.
	 *
	 * @param zzdw the zzdw of this zzjl
	 */
	public void setZzdw(String zzdw);

	/**
	 * Returns the qzny of this zzjl.
	 *
	 * @return the qzny of this zzjl
	 */
	@AutoEscape
	public String getQzny();

	/**
	 * Sets the qzny of this zzjl.
	 *
	 * @param qzny the qzny of this zzjl
	 */
	public void setQzny(String qzny);

	/**
	 * Returns the cszyzygz of this zzjl.
	 *
	 * @return the cszyzygz of this zzjl
	 */
	@AutoEscape
	public String getCszyzygz();

	/**
	 * Sets the cszyzygz of this zzjl.
	 *
	 * @param cszyzygz the cszyzygz of this zzjl
	 */
	public void setCszyzygz(String cszyzygz);

	/**
	 * Returns the zw of this zzjl.
	 *
	 * @return the zw of this zzjl
	 */
	@AutoEscape
	public String getZw();

	/**
	 * Sets the zw of this zzjl.
	 *
	 * @param zw the zw of this zzjl
	 */
	public void setZw(String zw);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.justonetech.expert.model.Zzjl zzjl);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.justonetech.expert.model.Zzjl> toCacheModel();

	@Override
	public com.justonetech.expert.model.Zzjl toEscapedModel();

	@Override
	public com.justonetech.expert.model.Zzjl toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}