$axure.loadCurrentPage({
  "url":"发文管理.html",
  "generationDate":new Date(1434534637242),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5c54f4c5abcd4d719fc32bb9c4f0fa4b",
    "type":"Axure:Page",
    "name":"发文管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"61666d1707c84fa79af245c4d8f0d376",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":-25},
            "size":{
              "width":469,
              "height":618}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77ff8747bfd347a98ba5808a2a88ffce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":195,
                  "y":-25},
                "size":{
                  "width":469,
                  "height":618}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发文管理/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "61666d1707c84fa79af245c4d8f0d376":{
      "scriptId":"u0"},
    "77ff8747bfd347a98ba5808a2a88ffce":{
      "scriptId":"u1"}}});