/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.projApproval.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ConstructionParticipantUnits service. Represents a row in the &quot;projApproval_ConstructionParticipantUnits&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.justonetech.projApproval.model.impl.ConstructionParticipantUnitsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.justonetech.projApproval.model.impl.ConstructionParticipantUnitsImpl}.
 * </p>
 *
 * @author justonetech
 * @see ConstructionParticipantUnits
 * @see com.justonetech.projApproval.model.impl.ConstructionParticipantUnitsImpl
 * @see com.justonetech.projApproval.model.impl.ConstructionParticipantUnitsModelImpl
 * @generated
 */
public interface ConstructionParticipantUnitsModel extends BaseModel<ConstructionParticipantUnits> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a construction participant units model instance should use the {@link ConstructionParticipantUnits} interface instead.
	 */

	/**
	 * Returns the primary key of this construction participant units.
	 *
	 * @return the primary key of this construction participant units
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this construction participant units.
	 *
	 * @param primaryKey the primary key of this construction participant units
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the construction participant units ID of this construction participant units.
	 *
	 * @return the construction participant units ID of this construction participant units
	 */
	public long getConstructionParticipantUnitsId();

	/**
	 * Sets the construction participant units ID of this construction participant units.
	 *
	 * @param constructionParticipantUnitsId the construction participant units ID of this construction participant units
	 */
	public void setConstructionParticipantUnitsId(
		long constructionParticipantUnitsId);

	/**
	 * Returns the sort no of this construction participant units.
	 *
	 * @return the sort no of this construction participant units
	 */
	public int getSortNo();

	/**
	 * Sets the sort no of this construction participant units.
	 *
	 * @param sortNo the sort no of this construction participant units
	 */
	public void setSortNo(int sortNo);

	/**
	 * Returns the contract info submit num of this construction participant units.
	 *
	 * @return the contract info submit num of this construction participant units
	 */
	@AutoEscape
	public String getContractInfoSubmitNum();

	/**
	 * Sets the contract info submit num of this construction participant units.
	 *
	 * @param contractInfoSubmitNum the contract info submit num of this construction participant units
	 */
	public void setContractInfoSubmitNum(String contractInfoSubmitNum);

	/**
	 * Returns the unit type of this construction participant units.
	 *
	 * @return the unit type of this construction participant units
	 */
	public long getUnitType();

	/**
	 * Sets the unit type of this construction participant units.
	 *
	 * @param unitType the unit type of this construction participant units
	 */
	public void setUnitType(long unitType);

	/**
	 * Returns the unit name of this construction participant units.
	 *
	 * @return the unit name of this construction participant units
	 */
	@AutoEscape
	public String getUnitName();

	/**
	 * Sets the unit name of this construction participant units.
	 *
	 * @param unitName the unit name of this construction participant units
	 */
	public void setUnitName(String unitName);

	/**
	 * Returns the project leader of this construction participant units.
	 *
	 * @return the project leader of this construction participant units
	 */
	@AutoEscape
	public String getProjectLeader();

	/**
	 * Sets the project leader of this construction participant units.
	 *
	 * @param projectLeader the project leader of this construction participant units
	 */
	public void setProjectLeader(String projectLeader);

	/**
	 * Returns the telephone num of this construction participant units.
	 *
	 * @return the telephone num of this construction participant units
	 */
	@AutoEscape
	public String getTelephoneNum();

	/**
	 * Sets the telephone num of this construction participant units.
	 *
	 * @param telephoneNum the telephone num of this construction participant units
	 */
	public void setTelephoneNum(String telephoneNum);

	/**
	 * Returns the construction permit ID of this construction participant units.
	 *
	 * @return the construction permit ID of this construction participant units
	 */
	public long getConstructionPermitId();

	/**
	 * Sets the construction permit ID of this construction participant units.
	 *
	 * @param constructionPermitId the construction permit ID of this construction participant units
	 */
	public void setConstructionPermitId(long constructionPermitId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.justonetech.projApproval.model.ConstructionParticipantUnits constructionParticipantUnits);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.justonetech.projApproval.model.ConstructionParticipantUnits> toCacheModel();

	@Override
	public com.justonetech.projApproval.model.ConstructionParticipantUnits toEscapedModel();

	@Override
	public com.justonetech.projApproval.model.ConstructionParticipantUnits toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}