$axure.loadCurrentPage({
  "url":"职工之家_暂不开发_.html",
  "generationDate":new Date(1434534637445.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f594e80c07e6439ca7991c42632c6aee",
    "type":"Axure:Page",
    "name":"职工之家(暂不开发)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"adf725f10c3c43139f69f332d0760b31",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":80},
            "size":{
              "width":860,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/职工之家_暂不开发_/u0_line.png"}},
{
          "id":"919023ee2c0d4370a7c54bf3644c411d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "location":{
              "x":80,
              "y":33},
            "size":{
              "width":560,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7282aac519da4004a77cedc87a9692cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "location":{
                  "x":80,
                  "y":33},
                "size":{
                  "width":560,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fce4e6fbaca4c39a721968b51d04966",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333399,
              "opacity":1},
            "location":{
              "x":79,
              "y":61},
            "size":{
              "width":560,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d35c904fe8f48bfb28e330fb812b3f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333399,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":61},
                "size":{
                  "width":560,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fecf4fe0ef24a038c5b20129c7ac6bf",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":59},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5abbdc68f9b44ad08664d82d3ac215d2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":130,
              "y":59},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"44321754837d4e19b41dbabf278d9089",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":57.5},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"53cf1ec43af14c5a9cfc00ba38e39ffd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333399,
              "opacity":1},
            "location":{
              "x":820,
              "y":59},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c83a6a2cd2064864b91be798ba47c5ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333399,
                  "opacity":1},
                "location":{
                  "x":820,
                  "y":59},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ae7dddc7d5d45469027c83620b68995",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":59},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"24063cce0b0f4cdaa73d43ee4ddba9a7",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":110},
            "size":{
              "width":851,
              "height":288}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"893567a0b5ae4961b607c66302935a0a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CCFF},
                "size":{
                  "width":459,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec105ed125344cfb94d32f47908430d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF33CCFF},
                    "size":{
                      "width":459,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u12.png"}},
{
              "id":"25230f9381894ddf8697db665aaa0931",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333399,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":459,
                  "height":60}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e26b5bb7c0d241118a87f18f548ea047",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333399,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":459,
                      "height":60}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u20.png"}},
{
              "id":"69cec949366f45159713db01e1d760f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333399,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":459,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d49ce539be7c44cda0d34fdfc6f13c03",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333399,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":459,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u28.png"}},
{
              "id":"042fd143672c4a95a9ae60f22d4c0b39",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CCFF},
                "location":{
                  "x":459,
                  "y":0},
                "size":{
                  "width":105,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"058f17818c7f453cba8ba79c5631199e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF33CCFF},
                    "location":{
                      "x":459,
                      "y":0},
                    "size":{
                      "width":105,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u14.png"}},
{
              "id":"c55c6c6329cd4d278df7056a7c12d975",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":459,
                  "y":30},
                "size":{
                  "width":105,
                  "height":60}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"491f2bd46a614cc1b96c4657ab357644",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":459,
                      "y":30},
                    "size":{
                      "width":105,
                      "height":60}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u22.png"}},
{
              "id":"c25fcf91287e46e692a0a56a6540893a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":459,
                  "y":90},
                "size":{
                  "width":105,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"11a57d138bd04f099e2e13033a15ed80",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":459,
                      "y":90},
                    "size":{
                      "width":105,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u30.png"}},
{
              "id":"6d31d8e6501641ce8f508642b0cd01fb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CCFF},
                "location":{
                  "x":564,
                  "y":0},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61a4a5f3078249eca3d7d77881601b92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF33CCFF},
                    "location":{
                      "x":564,
                      "y":0},
                    "size":{
                      "width":135,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u16.png"}},
{
              "id":"48ed7e4642c64292ac8c891e69b096c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":564,
                  "y":30},
                "size":{
                  "width":135,
                  "height":60}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39846e4d26b346eb9d551540836683c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":564,
                      "y":30},
                    "size":{
                      "width":135,
                      "height":60}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u24.png"}},
{
              "id":"9cda7ee89d1d4d46beb257f657f16d87",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":564,
                  "y":90},
                "size":{
                  "width":135,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b3b52e8deffe43eb827903cb4cf90a96",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":564,
                      "y":90},
                    "size":{
                      "width":135,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u32.png"}},
{
              "id":"cf7aad198d754cee856108a3ae5db590",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CCFF},
                "location":{
                  "x":699,
                  "y":0},
                "size":{
                  "width":152,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"089fdbb565d84081afc692ccb7e76791",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF33CCFF},
                    "location":{
                      "x":699,
                      "y":0},
                    "size":{
                      "width":152,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u18.png"}},
{
              "id":"dd5fdc3124704c379d63b71ae5fb539d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":699,
                  "y":30},
                "size":{
                  "width":152,
                  "height":60}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"23aeecc3fd42472d939c3f774b9ca88e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":699,
                      "y":30},
                    "size":{
                      "width":152,
                      "height":60}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u26.png"}},
{
              "id":"c613ae9427404736b444ee91bab0c6c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":699,
                  "y":90},
                "size":{
                  "width":152,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e52dee92838f4884b305bf3c520f2ed9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":699,
                      "y":90},
                    "size":{
                      "width":152,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u34.png"}},
{
              "id":"ddf02395a43b4a339149f32b405422a0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333399,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":156},
                "size":{
                  "width":459,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8fc77dc93eaf46cbb41cfb0e9861ab62",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333399,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":156},
                    "size":{
                      "width":459,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u28.png"}},
{
              "id":"df4a73a42d18491a99678124e52468f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":459,
                  "y":156},
                "size":{
                  "width":105,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d903e8a1b10c4f19b7f78014ae1dc4ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":459,
                      "y":156},
                    "size":{
                      "width":105,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u30.png"}},
{
              "id":"5e4b59361be443da8fc2a3b0bbe79636",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":564,
                  "y":156},
                "size":{
                  "width":135,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb9dd25d89de49b188b9442e2fdc5773",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":564,
                      "y":156},
                    "size":{
                      "width":135,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u32.png"}},
{
              "id":"42f64a72c4aa45edaef837512e454a73",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":699,
                  "y":156},
                "size":{
                  "width":152,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cddfd8b26bd942d599a2f52ef65cdf48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":699,
                      "y":156},
                    "size":{
                      "width":152,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u34.png"}},
{
              "id":"515be20ab35b42ab9432164636734f65",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333399,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":222},
                "size":{
                  "width":459,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"830203c0da0d4e9db60811ae36422499",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333399,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":222},
                    "size":{
                      "width":459,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u44.png"}},
{
              "id":"dcf6c3ce053744b5b8eac97fb0ff6aa6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":459,
                  "y":222},
                "size":{
                  "width":105,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5962d4eb86964f11a915f9fade0c02e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":459,
                      "y":222},
                    "size":{
                      "width":105,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u46.png"}},
{
              "id":"503fdfd18de44db69dad026a2fae78b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":564,
                  "y":222},
                "size":{
                  "width":135,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9001cbe9d29c4a31a57d92872561611d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":564,
                      "y":222},
                    "size":{
                      "width":135,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u48.png"}},
{
              "id":"21170de8c75e4b0e852d026e6b1b2ea5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":699,
                  "y":222},
                "size":{
                  "width":152,
                  "height":66}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"981231313fdb4c1db67c4e8d05ebb5b4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":699,
                      "y":222},
                    "size":{
                      "width":152,
                      "height":66}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/职工之家_暂不开发_/u50.png"}}]},
{
          "id":"a35698b3ebbe45a19003d4390f6d1062",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":823,
              "y":32},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b2fb510832ac47c5853f182ac6dd13d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":789,
              "y":420},
            "size":{
              "width":144,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab458ea2ed964d78936f7449f1e595b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":789,
                  "y":420},
                "size":{
                  "width":144,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/职工之家_暂不开发_/u53.png"}},
{
          "id":"e664798b792248969531e0d3381888a4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":340,
              "y":160},
            "size":{
              "width":20,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "adf725f10c3c43139f69f332d0760b31":{
      "scriptId":"u0"},
    "919023ee2c0d4370a7c54bf3644c411d":{
      "scriptId":"u1"},
    "7282aac519da4004a77cedc87a9692cd":{
      "scriptId":"u2"},
    "4fce4e6fbaca4c39a721968b51d04966":{
      "scriptId":"u3"},
    "9d35c904fe8f48bfb28e330fb812b3f1":{
      "scriptId":"u4"},
    "6fecf4fe0ef24a038c5b20129c7ac6bf":{
      "scriptId":"u5"},
    "5abbdc68f9b44ad08664d82d3ac215d2":{
      "scriptId":"u6"},
    "44321754837d4e19b41dbabf278d9089":{
      "scriptId":"u7"},
    "53cf1ec43af14c5a9cfc00ba38e39ffd":{
      "scriptId":"u8"},
    "c83a6a2cd2064864b91be798ba47c5ec":{
      "scriptId":"u9"},
    "2ae7dddc7d5d45469027c83620b68995":{
      "scriptId":"u10"},
    "24063cce0b0f4cdaa73d43ee4ddba9a7":{
      "scriptId":"u11"},
    "893567a0b5ae4961b607c66302935a0a":{
      "scriptId":"u12"},
    "ec105ed125344cfb94d32f47908430d8":{
      "scriptId":"u13"},
    "042fd143672c4a95a9ae60f22d4c0b39":{
      "scriptId":"u14"},
    "058f17818c7f453cba8ba79c5631199e":{
      "scriptId":"u15"},
    "6d31d8e6501641ce8f508642b0cd01fb":{
      "scriptId":"u16"},
    "61a4a5f3078249eca3d7d77881601b92":{
      "scriptId":"u17"},
    "cf7aad198d754cee856108a3ae5db590":{
      "scriptId":"u18"},
    "089fdbb565d84081afc692ccb7e76791":{
      "scriptId":"u19"},
    "25230f9381894ddf8697db665aaa0931":{
      "scriptId":"u20"},
    "e26b5bb7c0d241118a87f18f548ea047":{
      "scriptId":"u21"},
    "c55c6c6329cd4d278df7056a7c12d975":{
      "scriptId":"u22"},
    "491f2bd46a614cc1b96c4657ab357644":{
      "scriptId":"u23"},
    "48ed7e4642c64292ac8c891e69b096c7":{
      "scriptId":"u24"},
    "39846e4d26b346eb9d551540836683c8":{
      "scriptId":"u25"},
    "dd5fdc3124704c379d63b71ae5fb539d":{
      "scriptId":"u26"},
    "23aeecc3fd42472d939c3f774b9ca88e":{
      "scriptId":"u27"},
    "69cec949366f45159713db01e1d760f6":{
      "scriptId":"u28"},
    "d49ce539be7c44cda0d34fdfc6f13c03":{
      "scriptId":"u29"},
    "c25fcf91287e46e692a0a56a6540893a":{
      "scriptId":"u30"},
    "11a57d138bd04f099e2e13033a15ed80":{
      "scriptId":"u31"},
    "9cda7ee89d1d4d46beb257f657f16d87":{
      "scriptId":"u32"},
    "b3b52e8deffe43eb827903cb4cf90a96":{
      "scriptId":"u33"},
    "c613ae9427404736b444ee91bab0c6c3":{
      "scriptId":"u34"},
    "e52dee92838f4884b305bf3c520f2ed9":{
      "scriptId":"u35"},
    "ddf02395a43b4a339149f32b405422a0":{
      "scriptId":"u36"},
    "8fc77dc93eaf46cbb41cfb0e9861ab62":{
      "scriptId":"u37"},
    "df4a73a42d18491a99678124e52468f2":{
      "scriptId":"u38"},
    "d903e8a1b10c4f19b7f78014ae1dc4ff":{
      "scriptId":"u39"},
    "5e4b59361be443da8fc2a3b0bbe79636":{
      "scriptId":"u40"},
    "bb9dd25d89de49b188b9442e2fdc5773":{
      "scriptId":"u41"},
    "42f64a72c4aa45edaef837512e454a73":{
      "scriptId":"u42"},
    "cddfd8b26bd942d599a2f52ef65cdf48":{
      "scriptId":"u43"},
    "515be20ab35b42ab9432164636734f65":{
      "scriptId":"u44"},
    "830203c0da0d4e9db60811ae36422499":{
      "scriptId":"u45"},
    "dcf6c3ce053744b5b8eac97fb0ff6aa6":{
      "scriptId":"u46"},
    "5962d4eb86964f11a915f9fade0c02e5":{
      "scriptId":"u47"},
    "503fdfd18de44db69dad026a2fae78b6":{
      "scriptId":"u48"},
    "9001cbe9d29c4a31a57d92872561611d":{
      "scriptId":"u49"},
    "21170de8c75e4b0e852d026e6b1b2ea5":{
      "scriptId":"u50"},
    "981231313fdb4c1db67c4e8d05ebb5b4":{
      "scriptId":"u51"},
    "a35698b3ebbe45a19003d4390f6d1062":{
      "scriptId":"u52"},
    "b2fb510832ac47c5853f182ac6dd13d2":{
      "scriptId":"u53"},
    "ab458ea2ed964d78936f7449f1e595b8":{
      "scriptId":"u54"},
    "e664798b792248969531e0d3381888a4":{
      "scriptId":"u55"}}});