$axure.loadCurrentPage({
  "url":"新增单位.html",
  "generationDate":new Date(1430724551660.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ae76435e67c34f91877fedf80c8e35a0",
    "type":"Axure:Page",
    "name":"新增单位",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ff64cd723f66471f8d434bba581a48c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":705,
              "height":388}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4854af4d8b3245f6be846520fcbaa062",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":705,
                  "height":388}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增单位/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ff64cd723f66471f8d434bba581a48c5":{
      "scriptId":"u0"},
    "4854af4d8b3245f6be846520fcbaa062":{
      "scriptId":"u1"}}});