$axure.loadCurrentPage({
  "url":"浏览.html",
  "generationDate":new Date(1434534637540.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c08fa8b31ea14ea0bb26985c940d0e28",
    "type":"Axure:Page",
    "name":"浏览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"640d8c3f4cf74b0e8a6c0cf4fd889eea",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":80},
            "size":{
              "width":860,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/回帖/u0_line.png"}},
{
          "id":"4e11fb9033f84f4d9ff4738f727096e1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":474,
              "y":28},
            "size":{
              "width":20,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d5a4bcd49a6a4638be0ca030765851b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333399,
              "opacity":1},
            "location":{
              "x":146,
              "y":28},
            "size":{
              "width":490,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee954fcf0e0e4149b19f8fb1e3851422",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333399,
                  "opacity":1},
                "location":{
                  "x":146,
                  "y":28},
                "size":{
                  "width":490,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d378492af7c4ef7b24e2b0867dcc9f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":28},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d4d94fe4eeb45c0ba8c475d029b3c44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":28},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/回帖/u4.png"}},
{
          "id":"6971edac47fc42a6934458cebece143e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":152,
              "y":57},
            "size":{
              "width":358,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d53d435504a4486ab080bbdef186c38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":57},
                "size":{
                  "width":358,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dab0c719e84f4a20a7a0ed973fbcbc70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":802,
              "y":31},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e50e162a246d4bce9ee9c99c81f537a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":802,
                  "y":31},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bba83e5e699e4a2ba53878a652fbf7a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":831,
              "y":57},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a38c8b68bcc94c778e2cce96d583007c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":57},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b19290a8a894ccf8a7bac303bfb4aaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":152,
              "y":156},
            "size":{
              "width":490,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c98b869fd72545f2ac0c95daf2a4d73d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":156},
                "size":{
                  "width":490,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f66b87332dbe4274a6f471fca88e9614",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":120},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cab86d3fe0cf451d97238de25a12ed5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":120},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/回帖/u4.png"}},
{
          "id":"11569f2f6e2f48069cddc4bfd394a8db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":121},
            "size":{
              "width":358,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd0d9cd9ab3442f0af112af521a8ffc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":121},
                "size":{
                  "width":358,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d706119413a49b38f24a819bfbe94ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":122},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"360cda7807134c75ba2fa6249f86debc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":122},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9501df7a5fb41518c6951d0f30cbc5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":152,
              "y":251},
            "size":{
              "width":490,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"761f8b82d482427996b7781ba79dce68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":251},
                "size":{
                  "width":490,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5dadb0b70294c64841f4e625e861e77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":215},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3f5c72bf0504cee9564e794ad50b38e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":215},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/回帖/u4.png"}},
{
          "id":"61b93a97006c465f912eff08409b117e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":216},
            "size":{
              "width":358,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4295a3e70d484c35a99c119f4e7ef318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":216},
                "size":{
                  "width":358,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e5f764143684a1abd2faa91659066bd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":86,
              "y":188},
            "size":{
              "width":860,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/浏览/u26_line.png"}},
{
          "id":"b33cec629bdb4051a2f1a253327516f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":152,
              "y":364},
            "size":{
              "width":490,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c77c95177434e848daecba7bb5fc1b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":364},
                "size":{
                  "width":490,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2de1325706ee412c947c8f3244b070ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":328},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4589caf67d54bb88f710580052e5360",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":328},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/回帖/u4.png"}},
{
          "id":"8a4dbd56bbb94a88889d78abcc62a6b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":329},
            "size":{
              "width":358,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24466b6c530d4c6386f1acfc2d4a6584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":329},
                "size":{
                  "width":358,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"350c07f381e04a61b1256dd674be81b2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":86,
              "y":301},
            "size":{
              "width":860,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/浏览/u26_line.png"}},
{
          "id":"90a39c5d5c80400b934f3b5211d52527",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":470},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e4888bfd573b468091206c76b07fc371",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":470},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "640d8c3f4cf74b0e8a6c0cf4fd889eea":{
      "scriptId":"u0"},
    "4e11fb9033f84f4d9ff4738f727096e1":{
      "scriptId":"u1"},
    "d5a4bcd49a6a4638be0ca030765851b8":{
      "scriptId":"u2"},
    "ee954fcf0e0e4149b19f8fb1e3851422":{
      "scriptId":"u3"},
    "4d378492af7c4ef7b24e2b0867dcc9f7":{
      "scriptId":"u4"},
    "0d4d94fe4eeb45c0ba8c475d029b3c44":{
      "scriptId":"u5"},
    "6971edac47fc42a6934458cebece143e":{
      "scriptId":"u6"},
    "5d53d435504a4486ab080bbdef186c38":{
      "scriptId":"u7"},
    "dab0c719e84f4a20a7a0ed973fbcbc70":{
      "scriptId":"u8"},
    "e50e162a246d4bce9ee9c99c81f537a3":{
      "scriptId":"u9"},
    "bba83e5e699e4a2ba53878a652fbf7a9":{
      "scriptId":"u10"},
    "a38c8b68bcc94c778e2cce96d583007c":{
      "scriptId":"u11"},
    "5b19290a8a894ccf8a7bac303bfb4aaf":{
      "scriptId":"u12"},
    "c98b869fd72545f2ac0c95daf2a4d73d":{
      "scriptId":"u13"},
    "f66b87332dbe4274a6f471fca88e9614":{
      "scriptId":"u14"},
    "cab86d3fe0cf451d97238de25a12ed5d":{
      "scriptId":"u15"},
    "11569f2f6e2f48069cddc4bfd394a8db":{
      "scriptId":"u16"},
    "cd0d9cd9ab3442f0af112af521a8ffc3":{
      "scriptId":"u17"},
    "5d706119413a49b38f24a819bfbe94ba":{
      "scriptId":"u18"},
    "360cda7807134c75ba2fa6249f86debc":{
      "scriptId":"u19"},
    "b9501df7a5fb41518c6951d0f30cbc5d":{
      "scriptId":"u20"},
    "761f8b82d482427996b7781ba79dce68":{
      "scriptId":"u21"},
    "a5dadb0b70294c64841f4e625e861e77":{
      "scriptId":"u22"},
    "b3f5c72bf0504cee9564e794ad50b38e":{
      "scriptId":"u23"},
    "61b93a97006c465f912eff08409b117e":{
      "scriptId":"u24"},
    "4295a3e70d484c35a99c119f4e7ef318":{
      "scriptId":"u25"},
    "6e5f764143684a1abd2faa91659066bd":{
      "scriptId":"u26"},
    "b33cec629bdb4051a2f1a253327516f1":{
      "scriptId":"u27"},
    "1c77c95177434e848daecba7bb5fc1b5":{
      "scriptId":"u28"},
    "2de1325706ee412c947c8f3244b070ef":{
      "scriptId":"u29"},
    "c4589caf67d54bb88f710580052e5360":{
      "scriptId":"u30"},
    "8a4dbd56bbb94a88889d78abcc62a6b2":{
      "scriptId":"u31"},
    "24466b6c530d4c6386f1acfc2d4a6584":{
      "scriptId":"u32"},
    "350c07f381e04a61b1256dd674be81b2":{
      "scriptId":"u33"},
    "90a39c5d5c80400b934f3b5211d52527":{
      "scriptId":"u34"},
    "e4888bfd573b468091206c76b07fc371":{
      "scriptId":"u35"}}});