$axure.loadCurrentPage({
  "url":"车辆管理.html",
  "generationDate":new Date(1434534636407.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"21e14d08b04145c39f0a96885582e518",
    "type":"Axure:Page",
    "name":"车辆管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6741e27eb7304df596b6a872891ad239",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":60},
            "size":{
              "width":1075,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a5d6ef2e0ff472cb805babe829ee32c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b96f366711d14043b97da22433576fd8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u1.png"}},
{
              "id":"1b2acb44f729454eb3c33ad9598fbb16",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9ee4637d6df44edab90de0d144702f2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"5c4bcfd0dced45378e2126ca640b17e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19dd4037359a4b7f8a5d510f15541b31",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"5550121ca20b4ae895159ed763b58715",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"220eac3661cc464e90ae01ea1aba7f8e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u1.png"}},
{
              "id":"406d9c707d2543c684b7e04db6d85627",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b9834b682d949a19dc483f31788dd8f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"b479e67b035a46c99b5b355c04ca676e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d7372a745454c0ca89e31dc360e49ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"71a143c9613e4c3d8b0b340cc078bd34",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32e46568589c4e50a19fc7ad5fa2b55b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u1.png"}},
{
              "id":"2021594e7f334f1aacc8261ac9f916b8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"306beca9405e48b0a9c4c690dcc8e0a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"2c07b31c53a84694a678dc36288fac1e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25ebdeeb9afe48668934df42b0d3988d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"afc954bef89d4c989b56518267b5e550",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa7c44ea2f90478f9e39ea8b1a19936b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u1.png"}},
{
              "id":"3d40fae54f2f411484941bc20f88b36a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"48ec3973e740458597793548e2f5d3b6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"21ff4958ed3a4e6bae466e6d04a00b6a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7cec0a31da194336b57bf1d348b11145",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"cbbf243935b447a78d81cfe3e084437d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":598,
                  "y":0},
                "size":{
                  "width":237,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c4db9a2b63364a2b87949cd800c08d31",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":598,
                      "y":0},
                    "size":{
                      "width":237,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u13.png"}},
{
              "id":"b063e2fcc091431cbf365daf29a5504a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":30},
                "size":{
                  "width":237,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a92c2b35ef54d249cd15983fd4866d7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":30},
                    "size":{
                      "width":237,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u31.png"}},
{
              "id":"55c58ac5a42d42a98d60ed126ae50706",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":60},
                "size":{
                  "width":237,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3af4bfbb79454ba7af5f9f54be936ab1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":60},
                    "size":{
                      "width":237,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u31.png"}},
{
              "id":"07308967e4a34d3393921024a588cf20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":835,
                  "y":0},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"200666f212924e269beaf52c07634b5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":835,
                      "y":0},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u15.png"}},
{
              "id":"84bce25ccb6d41f5bc7a3e5e86f50e69",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":835,
                  "y":30},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9cc2d4720997469ba0eb4d211ae648b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":835,
                      "y":30},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u33.png"}},
{
              "id":"1640225ac0264699b8f8c31c2b5f8d1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":835,
                  "y":60},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f107922f4a744a4a966c4fb029bfc711",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":835,
                      "y":60},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u33.png"}},
{
              "id":"14cf7be2dced40a1a54e5df861a0f98e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":497,
                  "y":0},
                "size":{
                  "width":101,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a26b4a3efac4b958b0b2abe590ce625",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":497,
                      "y":0},
                    "size":{
                      "width":101,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u11.png"}},
{
              "id":"8440ed131cd54db79f189912bf8b2887",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":497,
                  "y":30},
                "size":{
                  "width":101,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"47db5697fb8b4ace95998bbd796add4f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":497,
                      "y":30},
                    "size":{
                      "width":101,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u29.png"}},
{
              "id":"98e5317637e54777bd3f6d57b3a2de27",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":497,
                  "y":60},
                "size":{
                  "width":101,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54dd911c33b64cf79329b862f4ef81e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":497,
                      "y":60},
                    "size":{
                      "width":101,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u29.png"}},
{
              "id":"669a07eb776c482fb5f6f2ac3d13b3d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d94ccc80d2674ec2ad79c7b17fa77e6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u9.png"}},
{
              "id":"6cc69db5e5e24f229514bedee2d2090d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1d252c8c4764441fbd5a9b50146ca545",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":30},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u27.png"}},
{
              "id":"dd468f8d9947414293895192572f70cd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ac515af258749c58cfdf91ea4c6164a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":60},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u27.png"}},
{
              "id":"f2f7c0bf1970459aa9acfcdbf71e77c2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a4501b42eef4116819d0fd93ba264e8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"03480465bcf74ea58deef6b087ffc494",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c44b80b63ad14507931a411c2be56e35",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"6d158dd545b04b3b9ab9f542da138011",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d0db82d2c37d491b9d59203fcb79f0bc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"e1de3037094a4ca68b6de96b8291152a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7501c60083034f049ce3399a682f101f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"4ef1cd1505ed4a82b2da753e326489af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":90},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2677c6cb83a481c8ebbc588e86c46f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":90},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u27.png"}},
{
              "id":"6c0f7818bfc146a6bc340f7f35102d54",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":497,
                  "y":90},
                "size":{
                  "width":101,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"88ea3c5ae0044b71bf94c076001319ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":497,
                      "y":90},
                    "size":{
                      "width":101,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u29.png"}},
{
              "id":"b97209b464484e419917a673bded9165",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":90},
                "size":{
                  "width":237,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9be0633df8614761b8eb545b21d0eee3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":90},
                    "size":{
                      "width":237,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u31.png"}},
{
              "id":"efa275a48cd848a8a73f73e72e905deb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":835,
                  "y":90},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0335a14cb2694439a3f457f7be2d8110",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":835,
                      "y":90},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u33.png"}},
{
              "id":"1130f54feab34502a746af478ea62e69",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c1d1e7b8d994c3a82caedcd35f607a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u101.png"}},
{
              "id":"ab2a3ad17bb54186bdc57ed77b0f3ca5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":150},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff76218c390042eda039862995de78ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u101.png"}},
{
              "id":"995ef4834aff471a85aba3ddb91bbb56",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":150},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5e2121fc4dcb473a82a833367606772b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u101.png"}},
{
              "id":"f03f6c0479a7420da29830163a6743ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":150},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"992f1043cf184cf29bfea5d93c9502c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u101.png"}},
{
              "id":"d8e70d8f2a444d0e8f7810cfe7db8943",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":150},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06c5a0ddd89b4c3584447fc8a880a45e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":150},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u99.png"}},
{
              "id":"3da4ad70ee4f451daa4cc4149c46bbc7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":497,
                  "y":150},
                "size":{
                  "width":101,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6456976d7d39479fb8aa5fa6b7a86fb2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":497,
                      "y":150},
                    "size":{
                      "width":101,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u101.png"}},
{
              "id":"3a58a5baa3164fb99bd8c42eeff1b176",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":150},
                "size":{
                  "width":237,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74fb474e584245d4aec8692b1d3e7358",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":150},
                    "size":{
                      "width":237,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u103.png"}},
{
              "id":"9195e926fa2841e7b044b1eeb85f1ade",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":835,
                  "y":150},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b25f564bfa764b35bb833b296f36e7de",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":835,
                      "y":150},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u105.png"}},
{
              "id":"23d374ba355142fe97970851155d32b9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92236f0fe80f46478452c40c532e385d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"9f623635ddda42eabe7ca7f9ab8546a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2a6d2dd1701492eb606186807753f49",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"7829298c2fe648789484b50bc69ed20e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70a145bb2d994ca7b15c36375f2af3a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"ef17592e6afa4916a9f92fca6c2237e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff6e85a169854a2eafe37250c0740139",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u21.png"}},
{
              "id":"1eb452bc85f441ec89313cbaf28d1abe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":120},
                "size":{
                  "width":97,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"30325e977d424c4592a28165e93a1da5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":120},
                    "size":{
                      "width":97,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u27.png"}},
{
              "id":"5b55f317c7bb45c9b9453016f17cfb6e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":497,
                  "y":120},
                "size":{
                  "width":101,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3d383cf19db64124bca6132609b7928d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":497,
                      "y":120},
                    "size":{
                      "width":101,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u29.png"}},
{
              "id":"e14440ff56f34aa59baad024c66ed12f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":598,
                  "y":120},
                "size":{
                  "width":237,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d2b5952d25ee43e5a1248f045cc20b3f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":598,
                      "y":120},
                    "size":{
                      "width":237,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u31.png"}},
{
              "id":"b2069c145c9744b2b90dafdb089ed234",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":835,
                  "y":120},
                "size":{
                  "width":119,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3586371a44274088970b700eb1aca27c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":835,
                      "y":120},
                    "size":{
                      "width":119,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u33.png"}},
{
              "id":"5b7c52a1454d44208d03d5b447382b1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":954,
                  "y":0},
                "size":{
                  "width":121,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62c7c6dd2cf847e6b8e8a27ac73b7d7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":954,
                      "y":0},
                    "size":{
                      "width":121,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u17.png"}},
{
              "id":"3bf0a467ca1e46959ab830e8765e7682",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":954,
                  "y":30},
                "size":{
                  "width":121,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9c61eecd2a64342992b8c367d5ec116",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":954,
                      "y":30},
                    "size":{
                      "width":121,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u35.png"}},
{
              "id":"db86595dfb9a4328b499c31dc5b0296f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":954,
                  "y":60},
                "size":{
                  "width":121,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee95892d6b054db18395b8ac8c46f72a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":954,
                      "y":60},
                    "size":{
                      "width":121,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u35.png"}},
{
              "id":"2b166dcc26034e1cb42949bb2207686d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":954,
                  "y":90},
                "size":{
                  "width":121,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7157de55c2884939add4adaaf01d94a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":954,
                      "y":90},
                    "size":{
                      "width":121,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u35.png"}},
{
              "id":"128bb93b3da54320a378f389d861daf9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":954,
                  "y":120},
                "size":{
                  "width":121,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55fcbee5b93e47118c0ec4298648440f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":954,
                      "y":120},
                    "size":{
                      "width":121,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u35.png"}},
{
              "id":"a91ae207886d45738ca8ac19e2567fa2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":954,
                  "y":150},
                "size":{
                  "width":121,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6299d72a881641318f8e464da0ae98a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":954,
                      "y":150},
                    "size":{
                      "width":121,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆管理/u107.png"}}]},
{
          "id":"28069f370d504a8e943bc357c9bc22dd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":25},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"24d3d0b5183545a7af2524ac25f0a3c4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":25},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"67766b0210854a3e8c092566803eec7f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":153},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5800ab7e71e44ad89857c0d1bb29127e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":124},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"765b2d78f30246a2a8c31c0c919813ab",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":124},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5784f6d848414552afcb7f3b1034aab8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":153},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"213f412b31f74bbca9746a05d9135c17",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1020,
              "y":92},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3f96f631c528461480d9d9b0915c3ddc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":274},
            "size":{
              "width":332,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0952122b3a464e5e831091593f31b5ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":274},
                "size":{
                  "width":332,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b63240c6e1c4dfc9f6287f49149d4b1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":182},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"836fa831e70546139afb8a9b145095bc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":182},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "6741e27eb7304df596b6a872891ad239":{
      "scriptId":"u0"},
    "7a5d6ef2e0ff472cb805babe829ee32c":{
      "scriptId":"u1"},
    "b96f366711d14043b97da22433576fd8":{
      "scriptId":"u2"},
    "5550121ca20b4ae895159ed763b58715":{
      "scriptId":"u3"},
    "220eac3661cc464e90ae01ea1aba7f8e":{
      "scriptId":"u4"},
    "71a143c9613e4c3d8b0b340cc078bd34":{
      "scriptId":"u5"},
    "32e46568589c4e50a19fc7ad5fa2b55b":{
      "scriptId":"u6"},
    "afc954bef89d4c989b56518267b5e550":{
      "scriptId":"u7"},
    "aa7c44ea2f90478f9e39ea8b1a19936b":{
      "scriptId":"u8"},
    "669a07eb776c482fb5f6f2ac3d13b3d0":{
      "scriptId":"u9"},
    "d94ccc80d2674ec2ad79c7b17fa77e6f":{
      "scriptId":"u10"},
    "14cf7be2dced40a1a54e5df861a0f98e":{
      "scriptId":"u11"},
    "4a26b4a3efac4b958b0b2abe590ce625":{
      "scriptId":"u12"},
    "cbbf243935b447a78d81cfe3e084437d":{
      "scriptId":"u13"},
    "c4db9a2b63364a2b87949cd800c08d31":{
      "scriptId":"u14"},
    "07308967e4a34d3393921024a588cf20":{
      "scriptId":"u15"},
    "200666f212924e269beaf52c07634b5b":{
      "scriptId":"u16"},
    "5b7c52a1454d44208d03d5b447382b1c":{
      "scriptId":"u17"},
    "62c7c6dd2cf847e6b8e8a27ac73b7d7e":{
      "scriptId":"u18"},
    "1b2acb44f729454eb3c33ad9598fbb16":{
      "scriptId":"u19"},
    "a9ee4637d6df44edab90de0d144702f2":{
      "scriptId":"u20"},
    "406d9c707d2543c684b7e04db6d85627":{
      "scriptId":"u21"},
    "3b9834b682d949a19dc483f31788dd8f":{
      "scriptId":"u22"},
    "2021594e7f334f1aacc8261ac9f916b8":{
      "scriptId":"u23"},
    "306beca9405e48b0a9c4c690dcc8e0a2":{
      "scriptId":"u24"},
    "3d40fae54f2f411484941bc20f88b36a":{
      "scriptId":"u25"},
    "48ec3973e740458597793548e2f5d3b6":{
      "scriptId":"u26"},
    "6cc69db5e5e24f229514bedee2d2090d":{
      "scriptId":"u27"},
    "1d252c8c4764441fbd5a9b50146ca545":{
      "scriptId":"u28"},
    "8440ed131cd54db79f189912bf8b2887":{
      "scriptId":"u29"},
    "47db5697fb8b4ace95998bbd796add4f":{
      "scriptId":"u30"},
    "b063e2fcc091431cbf365daf29a5504a":{
      "scriptId":"u31"},
    "4a92c2b35ef54d249cd15983fd4866d7":{
      "scriptId":"u32"},
    "84bce25ccb6d41f5bc7a3e5e86f50e69":{
      "scriptId":"u33"},
    "9cc2d4720997469ba0eb4d211ae648b8":{
      "scriptId":"u34"},
    "3bf0a467ca1e46959ab830e8765e7682":{
      "scriptId":"u35"},
    "a9c61eecd2a64342992b8c367d5ec116":{
      "scriptId":"u36"},
    "5c4bcfd0dced45378e2126ca640b17e8":{
      "scriptId":"u37"},
    "19dd4037359a4b7f8a5d510f15541b31":{
      "scriptId":"u38"},
    "b479e67b035a46c99b5b355c04ca676e":{
      "scriptId":"u39"},
    "9d7372a745454c0ca89e31dc360e49ad":{
      "scriptId":"u40"},
    "2c07b31c53a84694a678dc36288fac1e":{
      "scriptId":"u41"},
    "25ebdeeb9afe48668934df42b0d3988d":{
      "scriptId":"u42"},
    "21ff4958ed3a4e6bae466e6d04a00b6a":{
      "scriptId":"u43"},
    "7cec0a31da194336b57bf1d348b11145":{
      "scriptId":"u44"},
    "dd468f8d9947414293895192572f70cd":{
      "scriptId":"u45"},
    "9ac515af258749c58cfdf91ea4c6164a":{
      "scriptId":"u46"},
    "98e5317637e54777bd3f6d57b3a2de27":{
      "scriptId":"u47"},
    "54dd911c33b64cf79329b862f4ef81e7":{
      "scriptId":"u48"},
    "55c58ac5a42d42a98d60ed126ae50706":{
      "scriptId":"u49"},
    "3af4bfbb79454ba7af5f9f54be936ab1":{
      "scriptId":"u50"},
    "1640225ac0264699b8f8c31c2b5f8d1c":{
      "scriptId":"u51"},
    "f107922f4a744a4a966c4fb029bfc711":{
      "scriptId":"u52"},
    "db86595dfb9a4328b499c31dc5b0296f":{
      "scriptId":"u53"},
    "ee95892d6b054db18395b8ac8c46f72a":{
      "scriptId":"u54"},
    "f2f7c0bf1970459aa9acfcdbf71e77c2":{
      "scriptId":"u55"},
    "5a4501b42eef4116819d0fd93ba264e8":{
      "scriptId":"u56"},
    "03480465bcf74ea58deef6b087ffc494":{
      "scriptId":"u57"},
    "c44b80b63ad14507931a411c2be56e35":{
      "scriptId":"u58"},
    "6d158dd545b04b3b9ab9f542da138011":{
      "scriptId":"u59"},
    "d0db82d2c37d491b9d59203fcb79f0bc":{
      "scriptId":"u60"},
    "e1de3037094a4ca68b6de96b8291152a":{
      "scriptId":"u61"},
    "7501c60083034f049ce3399a682f101f":{
      "scriptId":"u62"},
    "4ef1cd1505ed4a82b2da753e326489af":{
      "scriptId":"u63"},
    "e2677c6cb83a481c8ebbc588e86c46f9":{
      "scriptId":"u64"},
    "6c0f7818bfc146a6bc340f7f35102d54":{
      "scriptId":"u65"},
    "88ea3c5ae0044b71bf94c076001319ed":{
      "scriptId":"u66"},
    "b97209b464484e419917a673bded9165":{
      "scriptId":"u67"},
    "9be0633df8614761b8eb545b21d0eee3":{
      "scriptId":"u68"},
    "efa275a48cd848a8a73f73e72e905deb":{
      "scriptId":"u69"},
    "0335a14cb2694439a3f457f7be2d8110":{
      "scriptId":"u70"},
    "2b166dcc26034e1cb42949bb2207686d":{
      "scriptId":"u71"},
    "7157de55c2884939add4adaaf01d94a3":{
      "scriptId":"u72"},
    "23d374ba355142fe97970851155d32b9":{
      "scriptId":"u73"},
    "92236f0fe80f46478452c40c532e385d":{
      "scriptId":"u74"},
    "9f623635ddda42eabe7ca7f9ab8546a9":{
      "scriptId":"u75"},
    "a2a6d2dd1701492eb606186807753f49":{
      "scriptId":"u76"},
    "7829298c2fe648789484b50bc69ed20e":{
      "scriptId":"u77"},
    "70a145bb2d994ca7b15c36375f2af3a8":{
      "scriptId":"u78"},
    "ef17592e6afa4916a9f92fca6c2237e1":{
      "scriptId":"u79"},
    "ff6e85a169854a2eafe37250c0740139":{
      "scriptId":"u80"},
    "1eb452bc85f441ec89313cbaf28d1abe":{
      "scriptId":"u81"},
    "30325e977d424c4592a28165e93a1da5":{
      "scriptId":"u82"},
    "5b55f317c7bb45c9b9453016f17cfb6e":{
      "scriptId":"u83"},
    "3d383cf19db64124bca6132609b7928d":{
      "scriptId":"u84"},
    "e14440ff56f34aa59baad024c66ed12f":{
      "scriptId":"u85"},
    "d2b5952d25ee43e5a1248f045cc20b3f":{
      "scriptId":"u86"},
    "b2069c145c9744b2b90dafdb089ed234":{
      "scriptId":"u87"},
    "3586371a44274088970b700eb1aca27c":{
      "scriptId":"u88"},
    "128bb93b3da54320a378f389d861daf9":{
      "scriptId":"u89"},
    "55fcbee5b93e47118c0ec4298648440f":{
      "scriptId":"u90"},
    "1130f54feab34502a746af478ea62e69":{
      "scriptId":"u91"},
    "2c1d1e7b8d994c3a82caedcd35f607a8":{
      "scriptId":"u92"},
    "ab2a3ad17bb54186bdc57ed77b0f3ca5":{
      "scriptId":"u93"},
    "ff76218c390042eda039862995de78ce":{
      "scriptId":"u94"},
    "995ef4834aff471a85aba3ddb91bbb56":{
      "scriptId":"u95"},
    "5e2121fc4dcb473a82a833367606772b":{
      "scriptId":"u96"},
    "f03f6c0479a7420da29830163a6743ee":{
      "scriptId":"u97"},
    "992f1043cf184cf29bfea5d93c9502c4":{
      "scriptId":"u98"},
    "d8e70d8f2a444d0e8f7810cfe7db8943":{
      "scriptId":"u99"},
    "06c5a0ddd89b4c3584447fc8a880a45e":{
      "scriptId":"u100"},
    "3da4ad70ee4f451daa4cc4149c46bbc7":{
      "scriptId":"u101"},
    "6456976d7d39479fb8aa5fa6b7a86fb2":{
      "scriptId":"u102"},
    "3a58a5baa3164fb99bd8c42eeff1b176":{
      "scriptId":"u103"},
    "74fb474e584245d4aec8692b1d3e7358":{
      "scriptId":"u104"},
    "9195e926fa2841e7b044b1eeb85f1ade":{
      "scriptId":"u105"},
    "b25f564bfa764b35bb833b296f36e7de":{
      "scriptId":"u106"},
    "a91ae207886d45738ca8ac19e2567fa2":{
      "scriptId":"u107"},
    "6299d72a881641318f8e464da0ae98a3":{
      "scriptId":"u108"},
    "28069f370d504a8e943bc357c9bc22dd":{
      "scriptId":"u109"},
    "24d3d0b5183545a7af2524ac25f0a3c4":{
      "scriptId":"u110"},
    "67766b0210854a3e8c092566803eec7f":{
      "scriptId":"u111"},
    "5800ab7e71e44ad89857c0d1bb29127e":{
      "scriptId":"u112"},
    "765b2d78f30246a2a8c31c0c919813ab":{
      "scriptId":"u113"},
    "5784f6d848414552afcb7f3b1034aab8":{
      "scriptId":"u114"},
    "213f412b31f74bbca9746a05d9135c17":{
      "scriptId":"u115"},
    "3f96f631c528461480d9d9b0915c3ddc":{
      "scriptId":"u116"},
    "0952122b3a464e5e831091593f31b5ab":{
      "scriptId":"u117"},
    "2b63240c6e1c4dfc9f6287f49149d4b1":{
      "scriptId":"u118"},
    "836fa831e70546139afb8a9b145095bc":{
      "scriptId":"u119"}}});