/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.oa.model.impl;

import com.justonetech.oa.model.OfficeSupplyApplication;
import com.justonetech.oa.model.OfficeSupplyApplicationModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the OfficeSupplyApplication service. Represents a row in the &quot;oa_OfficeSupplyApplication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.justonetech.oa.model.OfficeSupplyApplicationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OfficeSupplyApplicationImpl}.
 * </p>
 *
 * @author justonetech
 * @see OfficeSupplyApplicationImpl
 * @see com.justonetech.oa.model.OfficeSupplyApplication
 * @see com.justonetech.oa.model.OfficeSupplyApplicationModel
 * @generated
 */
public class OfficeSupplyApplicationModelImpl extends BaseModelImpl<OfficeSupplyApplication>
	implements OfficeSupplyApplicationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a office supply application model instance should use the {@link com.justonetech.oa.model.OfficeSupplyApplication} interface instead.
	 */
	public static final String TABLE_NAME = "oa_OfficeSupplyApplication";
	public static final Object[][] TABLE_COLUMNS = {
			{ "officeSupplyApplicationId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createTime", Types.TIMESTAMP },
			{ "modifiedTime", Types.TIMESTAMP },
			{ "deptId", Types.BIGINT },
			{ "deptName", Types.VARCHAR },
			{ "introductions", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table oa_OfficeSupplyApplication (officeSupplyApplicationId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createTime DATE null,modifiedTime DATE null,deptId LONG,deptName VARCHAR(75) null,introductions VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table oa_OfficeSupplyApplication";
	public static final String ORDER_BY_JPQL = " ORDER BY officeSupplyApplication.modifiedTime DESC";
	public static final String ORDER_BY_SQL = " ORDER BY oa_OfficeSupplyApplication.modifiedTime DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.justonetech.oa.model.OfficeSupplyApplication"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.justonetech.oa.model.OfficeSupplyApplication"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.justonetech.oa.model.OfficeSupplyApplication"),
			true);
	public static long USERID_COLUMN_BITMASK = 1L;
	public static long MODIFIEDTIME_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.justonetech.oa.model.OfficeSupplyApplication"));

	public OfficeSupplyApplicationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _officeSupplyApplicationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOfficeSupplyApplicationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _officeSupplyApplicationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OfficeSupplyApplication.class;
	}

	@Override
	public String getModelClassName() {
		return OfficeSupplyApplication.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("officeSupplyApplicationId",
			getOfficeSupplyApplicationId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createTime", getCreateTime());
		attributes.put("modifiedTime", getModifiedTime());
		attributes.put("deptId", getDeptId());
		attributes.put("deptName", getDeptName());
		attributes.put("introductions", getIntroductions());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long officeSupplyApplicationId = (Long)attributes.get(
				"officeSupplyApplicationId");

		if (officeSupplyApplicationId != null) {
			setOfficeSupplyApplicationId(officeSupplyApplicationId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createTime = (Date)attributes.get("createTime");

		if (createTime != null) {
			setCreateTime(createTime);
		}

		Date modifiedTime = (Date)attributes.get("modifiedTime");

		if (modifiedTime != null) {
			setModifiedTime(modifiedTime);
		}

		Long deptId = (Long)attributes.get("deptId");

		if (deptId != null) {
			setDeptId(deptId);
		}

		String deptName = (String)attributes.get("deptName");

		if (deptName != null) {
			setDeptName(deptName);
		}

		String introductions = (String)attributes.get("introductions");

		if (introductions != null) {
			setIntroductions(introductions);
		}
	}

	@Override
	public long getOfficeSupplyApplicationId() {
		return _officeSupplyApplicationId;
	}

	@Override
	public void setOfficeSupplyApplicationId(long officeSupplyApplicationId) {
		_officeSupplyApplicationId = officeSupplyApplicationId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateTime() {
		return _createTime;
	}

	@Override
	public void setCreateTime(Date createTime) {
		_createTime = createTime;
	}

	@Override
	public Date getModifiedTime() {
		return _modifiedTime;
	}

	@Override
	public void setModifiedTime(Date modifiedTime) {
		_columnBitmask = -1L;

		_modifiedTime = modifiedTime;
	}

	@Override
	public long getDeptId() {
		return _deptId;
	}

	@Override
	public void setDeptId(long deptId) {
		_deptId = deptId;
	}

	@Override
	public String getDeptName() {
		if (_deptName == null) {
			return StringPool.BLANK;
		}
		else {
			return _deptName;
		}
	}

	@Override
	public void setDeptName(String deptName) {
		_deptName = deptName;
	}

	@Override
	public String getIntroductions() {
		if (_introductions == null) {
			return StringPool.BLANK;
		}
		else {
			return _introductions;
		}
	}

	@Override
	public void setIntroductions(String introductions) {
		_introductions = introductions;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			OfficeSupplyApplication.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OfficeSupplyApplication toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OfficeSupplyApplication)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OfficeSupplyApplicationImpl officeSupplyApplicationImpl = new OfficeSupplyApplicationImpl();

		officeSupplyApplicationImpl.setOfficeSupplyApplicationId(getOfficeSupplyApplicationId());
		officeSupplyApplicationImpl.setUserId(getUserId());
		officeSupplyApplicationImpl.setUserName(getUserName());
		officeSupplyApplicationImpl.setCreateTime(getCreateTime());
		officeSupplyApplicationImpl.setModifiedTime(getModifiedTime());
		officeSupplyApplicationImpl.setDeptId(getDeptId());
		officeSupplyApplicationImpl.setDeptName(getDeptName());
		officeSupplyApplicationImpl.setIntroductions(getIntroductions());

		officeSupplyApplicationImpl.resetOriginalValues();

		return officeSupplyApplicationImpl;
	}

	@Override
	public int compareTo(OfficeSupplyApplication officeSupplyApplication) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedTime(),
				officeSupplyApplication.getModifiedTime());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OfficeSupplyApplication)) {
			return false;
		}

		OfficeSupplyApplication officeSupplyApplication = (OfficeSupplyApplication)obj;

		long primaryKey = officeSupplyApplication.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		OfficeSupplyApplicationModelImpl officeSupplyApplicationModelImpl = this;

		officeSupplyApplicationModelImpl._originalUserId = officeSupplyApplicationModelImpl._userId;

		officeSupplyApplicationModelImpl._setOriginalUserId = false;

		officeSupplyApplicationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<OfficeSupplyApplication> toCacheModel() {
		OfficeSupplyApplicationCacheModel officeSupplyApplicationCacheModel = new OfficeSupplyApplicationCacheModel();

		officeSupplyApplicationCacheModel.officeSupplyApplicationId = getOfficeSupplyApplicationId();

		officeSupplyApplicationCacheModel.userId = getUserId();

		officeSupplyApplicationCacheModel.userName = getUserName();

		String userName = officeSupplyApplicationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			officeSupplyApplicationCacheModel.userName = null;
		}

		Date createTime = getCreateTime();

		if (createTime != null) {
			officeSupplyApplicationCacheModel.createTime = createTime.getTime();
		}
		else {
			officeSupplyApplicationCacheModel.createTime = Long.MIN_VALUE;
		}

		Date modifiedTime = getModifiedTime();

		if (modifiedTime != null) {
			officeSupplyApplicationCacheModel.modifiedTime = modifiedTime.getTime();
		}
		else {
			officeSupplyApplicationCacheModel.modifiedTime = Long.MIN_VALUE;
		}

		officeSupplyApplicationCacheModel.deptId = getDeptId();

		officeSupplyApplicationCacheModel.deptName = getDeptName();

		String deptName = officeSupplyApplicationCacheModel.deptName;

		if ((deptName != null) && (deptName.length() == 0)) {
			officeSupplyApplicationCacheModel.deptName = null;
		}

		officeSupplyApplicationCacheModel.introductions = getIntroductions();

		String introductions = officeSupplyApplicationCacheModel.introductions;

		if ((introductions != null) && (introductions.length() == 0)) {
			officeSupplyApplicationCacheModel.introductions = null;
		}

		return officeSupplyApplicationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{officeSupplyApplicationId=");
		sb.append(getOfficeSupplyApplicationId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createTime=");
		sb.append(getCreateTime());
		sb.append(", modifiedTime=");
		sb.append(getModifiedTime());
		sb.append(", deptId=");
		sb.append(getDeptId());
		sb.append(", deptName=");
		sb.append(getDeptName());
		sb.append(", introductions=");
		sb.append(getIntroductions());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.justonetech.oa.model.OfficeSupplyApplication");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>officeSupplyApplicationId</column-name><column-value><![CDATA[");
		sb.append(getOfficeSupplyApplicationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createTime</column-name><column-value><![CDATA[");
		sb.append(getCreateTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedTime</column-name><column-value><![CDATA[");
		sb.append(getModifiedTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deptId</column-name><column-value><![CDATA[");
		sb.append(getDeptId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deptName</column-name><column-value><![CDATA[");
		sb.append(getDeptName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>introductions</column-name><column-value><![CDATA[");
		sb.append(getIntroductions());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = OfficeSupplyApplication.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			OfficeSupplyApplication.class
		};
	private long _officeSupplyApplicationId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createTime;
	private Date _modifiedTime;
	private long _deptId;
	private String _deptName;
	private String _introductions;
	private long _columnBitmask;
	private OfficeSupplyApplication _escapedModel;
}