$axure.loadCurrentPage({
  "url":"短信平台.html",
  "generationDate":new Date(1434534637333.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1393451377fc417992cfdaa6e3029b84",
    "type":"Axure:Page",
    "name":"短信平台",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"98bcd12d34eb47d9a6dd8545cb072d9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":44},
            "size":{
              "width":432,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"787a6f58cfa6493db0ffe9fe2c6f1cf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":44},
                "size":{
                  "width":432,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a57f2396110473ba930fea964e22f98",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":100},
            "size":{
              "width":963,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ae35188ea934082881b6600defbc1ab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":198,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29dddea0c9124a73aea2f33cbda7ffeb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":198,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u3.png"}},
{
              "id":"746dfc058cfe49e5bf75acb6de47548b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":198,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb535dbe34254b41a9965261a7b4fee6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":198,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u17.png"}},
{
              "id":"84c038b8245444bb9de80786709f8fc0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":198,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ba5eeabb906450388972474644d2077",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":198,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u17.png"}},
{
              "id":"7d1d2043b69745e8b05c7c9fbaa9cf0d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":198,
                  "y":0},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a1870dec368049c39e8713be1efec2d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":198,
                      "y":0},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u5.png"}},
{
              "id":"48585501a8ad448e9672b0c5f6489a81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":198,
                  "y":30},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"802a05cc365d4c5d84657bc9bc0778fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":198,
                      "y":30},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u19.png"}},
{
              "id":"0d77cd13b158478bb5ef2df1a0215c7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":198,
                  "y":60},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2fc4b8c6fae24d8cadb10a1d764271de",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":198,
                      "y":60},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u19.png"}},
{
              "id":"ea400858dc544065bd85be298d755572",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":336,
                  "y":0},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"14086c0596aa4361bc8d6745ed38dd03",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":336,
                      "y":0},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u7.png"}},
{
              "id":"b7a64d2808ce4ca08f3792697964100c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":336,
                  "y":30},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c763ba69000d4cd3aa091668897d5978",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":336,
                      "y":30},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u21.png"}},
{
              "id":"beab2f55e0c040b0adbf37a922849257",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":336,
                  "y":60},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6112d27101e34a8ca28289a3a2bf8c47",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":336,
                      "y":60},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u21.png"}},
{
              "id":"88ae0348e7d8448f8c459d23442d840b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":451,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc90d20e18fd40868c047ee1eda94318",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":451,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u5.png"}},
{
              "id":"055b82ecbcfd4463a6a621f59e48f034",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":451,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b37e975b39c040e98efeefa4faea2c42",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":451,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u25.png"}},
{
              "id":"b79595dc3e1847208c92462b3aa77c01",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":451,
                  "y":60},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8d9710d79af4d0b97e1ca978b2ad168",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":451,
                      "y":60},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u25.png"}},
{
              "id":"a80a0bbe8d7c467eb91265710cff0f91",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":571,
                  "y":0},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3aa7de84fb74d4da200930260a03601",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":571,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u11.png"}},
{
              "id":"d9cb7d3603aa47c799efed2137bab0b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":571,
                  "y":30},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d759cef547e49d9b54987d438b179a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":571,
                      "y":30},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u25.png"}},
{
              "id":"3261d311ff1143f4ba3541e1bcd5febf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":571,
                  "y":60},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c8d41170d7254ca8ad76ed962dc6dfa6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":571,
                      "y":60},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u25.png"}},
{
              "id":"5736089567014f4d8c319e3eb4d8721e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":688,
                  "y":0},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c0c888e7aeca410c8c44e680b49e00f1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":688,
                      "y":0},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u5.png"}},
{
              "id":"1956cca4b376443085e31dc294b82efc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":688,
                  "y":30},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a6d12e732284c2e9487471c90b8bd79",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":688,
                      "y":30},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u19.png"}},
{
              "id":"e8d4701cc9e945e0b0d6ec8e4b0d054a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":688,
                  "y":60},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ebdac03e5b744be88020ac23637f421",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":688,
                      "y":60},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u19.png"}},
{
              "id":"7a93e127d7df47b8a404e40c2a5a10be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":198,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8e8d6e3db7164e0d998e3f81b802f738",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":198,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u45.png"}},
{
              "id":"c8b0b6d5b010485f9aaddc1207e1aa90",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":198,
                  "y":90},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c23c442a3ec84186ab8a004213dbe258",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":198,
                      "y":90},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u47.png"}},
{
              "id":"f83d1864104c41de9474c942cadaa024",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":336,
                  "y":90},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3201216ac4504a99b8b7c2625837734c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":336,
                      "y":90},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u49.png"}},
{
              "id":"8a69582884cc4010b0a68cc456fde57e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":451,
                  "y":90},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16ddb2d13a204af2875a6f96bab90b8a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":451,
                      "y":90},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/信息发布/u105.png"}},
{
              "id":"2b83e4ca83d24c04a6e2c31dd5e95adc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":571,
                  "y":90},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"88a43abd4e11471b90b39c5492b1b25a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":571,
                      "y":90},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u53.png"}},
{
              "id":"5d86b842bbeb4db7a940df9f99aa89eb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":688,
                  "y":90},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e03cf60ddb1847ceac9dcc428b4a4b5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":688,
                      "y":90},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u47.png"}},
{
              "id":"284303a133ba481e8549ffd8fbe28a10",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":826,
                  "y":0},
                "size":{
                  "width":137,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d3a71b49194949738782995289883257",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":826,
                      "y":0},
                    "size":{
                      "width":137,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u15.png"}},
{
              "id":"8f47f7ddb9f34f5c8391cebe3855b7b8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":826,
                  "y":30},
                "size":{
                  "width":137,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d39b4368984e4a829db6b008d824c8d3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":826,
                      "y":30},
                    "size":{
                      "width":137,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u29.png"}},
{
              "id":"c93f337f551c488890e3333e415279e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":826,
                  "y":60},
                "size":{
                  "width":137,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"35194dd20a9046de8bcc08d07cf9436c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":826,
                      "y":60},
                    "size":{
                      "width":137,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u29.png"}},
{
              "id":"071aeaacb64a48c687e3db2e659ae041",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":826,
                  "y":90},
                "size":{
                  "width":137,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"380bf4b1fa8f443fb6a043af605ebd09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":826,
                      "y":90},
                    "size":{
                      "width":137,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短信平台/u57.png"}}]},
{
          "id":"61d839ba1f8544cab1305733c51965cd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":133},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "98bcd12d34eb47d9a6dd8545cb072d9a":{
      "scriptId":"u0"},
    "787a6f58cfa6493db0ffe9fe2c6f1cf5":{
      "scriptId":"u1"},
    "2a57f2396110473ba930fea964e22f98":{
      "scriptId":"u2"},
    "4ae35188ea934082881b6600defbc1ab":{
      "scriptId":"u3"},
    "29dddea0c9124a73aea2f33cbda7ffeb":{
      "scriptId":"u4"},
    "7d1d2043b69745e8b05c7c9fbaa9cf0d":{
      "scriptId":"u5"},
    "a1870dec368049c39e8713be1efec2d6":{
      "scriptId":"u6"},
    "ea400858dc544065bd85be298d755572":{
      "scriptId":"u7"},
    "14086c0596aa4361bc8d6745ed38dd03":{
      "scriptId":"u8"},
    "88ae0348e7d8448f8c459d23442d840b":{
      "scriptId":"u9"},
    "cc90d20e18fd40868c047ee1eda94318":{
      "scriptId":"u10"},
    "a80a0bbe8d7c467eb91265710cff0f91":{
      "scriptId":"u11"},
    "e3aa7de84fb74d4da200930260a03601":{
      "scriptId":"u12"},
    "5736089567014f4d8c319e3eb4d8721e":{
      "scriptId":"u13"},
    "c0c888e7aeca410c8c44e680b49e00f1":{
      "scriptId":"u14"},
    "284303a133ba481e8549ffd8fbe28a10":{
      "scriptId":"u15"},
    "d3a71b49194949738782995289883257":{
      "scriptId":"u16"},
    "746dfc058cfe49e5bf75acb6de47548b":{
      "scriptId":"u17"},
    "fb535dbe34254b41a9965261a7b4fee6":{
      "scriptId":"u18"},
    "48585501a8ad448e9672b0c5f6489a81":{
      "scriptId":"u19"},
    "802a05cc365d4c5d84657bc9bc0778fd":{
      "scriptId":"u20"},
    "b7a64d2808ce4ca08f3792697964100c":{
      "scriptId":"u21"},
    "c763ba69000d4cd3aa091668897d5978":{
      "scriptId":"u22"},
    "055b82ecbcfd4463a6a621f59e48f034":{
      "scriptId":"u23"},
    "b37e975b39c040e98efeefa4faea2c42":{
      "scriptId":"u24"},
    "d9cb7d3603aa47c799efed2137bab0b6":{
      "scriptId":"u25"},
    "5d759cef547e49d9b54987d438b179a3":{
      "scriptId":"u26"},
    "1956cca4b376443085e31dc294b82efc":{
      "scriptId":"u27"},
    "4a6d12e732284c2e9487471c90b8bd79":{
      "scriptId":"u28"},
    "8f47f7ddb9f34f5c8391cebe3855b7b8":{
      "scriptId":"u29"},
    "d39b4368984e4a829db6b008d824c8d3":{
      "scriptId":"u30"},
    "84c038b8245444bb9de80786709f8fc0":{
      "scriptId":"u31"},
    "4ba5eeabb906450388972474644d2077":{
      "scriptId":"u32"},
    "0d77cd13b158478bb5ef2df1a0215c7e":{
      "scriptId":"u33"},
    "2fc4b8c6fae24d8cadb10a1d764271de":{
      "scriptId":"u34"},
    "beab2f55e0c040b0adbf37a922849257":{
      "scriptId":"u35"},
    "6112d27101e34a8ca28289a3a2bf8c47":{
      "scriptId":"u36"},
    "b79595dc3e1847208c92462b3aa77c01":{
      "scriptId":"u37"},
    "f8d9710d79af4d0b97e1ca978b2ad168":{
      "scriptId":"u38"},
    "3261d311ff1143f4ba3541e1bcd5febf":{
      "scriptId":"u39"},
    "c8d41170d7254ca8ad76ed962dc6dfa6":{
      "scriptId":"u40"},
    "e8d4701cc9e945e0b0d6ec8e4b0d054a":{
      "scriptId":"u41"},
    "0ebdac03e5b744be88020ac23637f421":{
      "scriptId":"u42"},
    "c93f337f551c488890e3333e415279e4":{
      "scriptId":"u43"},
    "35194dd20a9046de8bcc08d07cf9436c":{
      "scriptId":"u44"},
    "7a93e127d7df47b8a404e40c2a5a10be":{
      "scriptId":"u45"},
    "8e8d6e3db7164e0d998e3f81b802f738":{
      "scriptId":"u46"},
    "c8b0b6d5b010485f9aaddc1207e1aa90":{
      "scriptId":"u47"},
    "c23c442a3ec84186ab8a004213dbe258":{
      "scriptId":"u48"},
    "f83d1864104c41de9474c942cadaa024":{
      "scriptId":"u49"},
    "3201216ac4504a99b8b7c2625837734c":{
      "scriptId":"u50"},
    "8a69582884cc4010b0a68cc456fde57e":{
      "scriptId":"u51"},
    "16ddb2d13a204af2875a6f96bab90b8a":{
      "scriptId":"u52"},
    "2b83e4ca83d24c04a6e2c31dd5e95adc":{
      "scriptId":"u53"},
    "88a43abd4e11471b90b39c5492b1b25a":{
      "scriptId":"u54"},
    "5d86b842bbeb4db7a940df9f99aa89eb":{
      "scriptId":"u55"},
    "e03cf60ddb1847ceac9dcc428b4a4b5b":{
      "scriptId":"u56"},
    "071aeaacb64a48c687e3db2e659ae041":{
      "scriptId":"u57"},
    "380bf4b1fa8f443fb6a043af605ebd09":{
      "scriptId":"u58"},
    "61d839ba1f8544cab1305733c51965cd":{
      "scriptId":"u59"}}});