/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.justonetech.expert.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Expert service. Represents a row in the &quot;expert_Expert&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.justonetech.expert.model.impl.ExpertModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.justonetech.expert.model.impl.ExpertImpl}.
 * </p>
 *
 * @author fanqi
 * @see Expert
 * @see com.justonetech.expert.model.impl.ExpertImpl
 * @see com.justonetech.expert.model.impl.ExpertModelImpl
 * @generated
 */
public interface ExpertModel extends BaseModel<Expert> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a expert model instance should use the {@link Expert} interface instead.
	 */

	/**
	 * Returns the primary key of this expert.
	 *
	 * @return the primary key of this expert
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this expert.
	 *
	 * @param primaryKey the primary key of this expert
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the expert ID of this expert.
	 *
	 * @return the expert ID of this expert
	 */
	public long getExpertId();

	/**
	 * Sets the expert ID of this expert.
	 *
	 * @param expertId the expert ID of this expert
	 */
	public void setExpertId(long expertId);

	/**
	 * Returns the user ID of this expert.
	 *
	 * @return the user ID of this expert
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this expert.
	 *
	 * @param userId the user ID of this expert
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this expert.
	 *
	 * @return the user uuid of this expert
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this expert.
	 *
	 * @param userUuid the user uuid of this expert
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the xm of this expert.
	 *
	 * @return the xm of this expert
	 */
	@AutoEscape
	public String getXm();

	/**
	 * Sets the xm of this expert.
	 *
	 * @param xm the xm of this expert
	 */
	public void setXm(String xm);

	/**
	 * Returns the xb of this expert.
	 *
	 * @return the xb of this expert
	 */
	@AutoEscape
	public String getXb();

	/**
	 * Sets the xb of this expert.
	 *
	 * @param xb the xb of this expert
	 */
	public void setXb(String xb);

	/**
	 * Returns the sfzh of this expert.
	 *
	 * @return the sfzh of this expert
	 */
	@AutoEscape
	public String getSfzh();

	/**
	 * Sets the sfzh of this expert.
	 *
	 * @param sfzh the sfzh of this expert
	 */
	public void setSfzh(String sfzh);

	/**
	 * Returns the csny of this expert.
	 *
	 * @return the csny of this expert
	 */
	public Date getCsny();

	/**
	 * Sets the csny of this expert.
	 *
	 * @param csny the csny of this expert
	 */
	public void setCsny(Date csny);

	/**
	 * Returns the gzdw of this expert.
	 *
	 * @return the gzdw of this expert
	 */
	@AutoEscape
	public String getGzdw();

	/**
	 * Sets the gzdw of this expert.
	 *
	 * @param gzdw the gzdw of this expert
	 */
	public void setGzdw(String gzdw);

	/**
	 * Returns the dzyx of this expert.
	 *
	 * @return the dzyx of this expert
	 */
	@AutoEscape
	public String getDzyx();

	/**
	 * Sets the dzyx of this expert.
	 *
	 * @param dzyx the dzyx of this expert
	 */
	public void setDzyx(String dzyx);

	/**
	 * Returns the txdz of this expert.
	 *
	 * @return the txdz of this expert
	 */
	@AutoEscape
	public String getTxdz();

	/**
	 * Sets the txdz of this expert.
	 *
	 * @param txdz the txdz of this expert
	 */
	public void setTxdz(String txdz);

	/**
	 * Returns the yzbm of this expert.
	 *
	 * @return the yzbm of this expert
	 */
	@AutoEscape
	public String getYzbm();

	/**
	 * Sets the yzbm of this expert.
	 *
	 * @param yzbm the yzbm of this expert
	 */
	public void setYzbm(String yzbm);

	/**
	 * Returns the xrzw of this expert.
	 *
	 * @return the xrzw of this expert
	 */
	@AutoEscape
	public String getXrzw();

	/**
	 * Sets the xrzw of this expert.
	 *
	 * @param xrzw the xrzw of this expert
	 */
	public void setXrzw(String xrzw);

	/**
	 * Returns the zc of this expert.
	 *
	 * @return the zc of this expert
	 */
	@AutoEscape
	public String getZc();

	/**
	 * Sets the zc of this expert.
	 *
	 * @param zc the zc of this expert
	 */
	public void setZc(String zc);

	/**
	 * Returns the zyzg of this expert.
	 *
	 * @return the zyzg of this expert
	 */
	@AutoEscape
	public String getZyzg();

	/**
	 * Sets the zyzg of this expert.
	 *
	 * @param zyzg the zyzg of this expert
	 */
	public void setZyzg(String zyzg);

	/**
	 * Returns the cszy of this expert.
	 *
	 * @return the cszy of this expert
	 */
	@AutoEscape
	public String getCszy();

	/**
	 * Sets the cszy of this expert.
	 *
	 * @param cszy the cszy of this expert
	 */
	public void setCszy(String cszy);

	/**
	 * Returns the zygznx of this expert.
	 *
	 * @return the zygznx of this expert
	 */
	@AutoEscape
	public String getZygznx();

	/**
	 * Sets the zygznx of this expert.
	 *
	 * @param zygznx the zygznx of this expert
	 */
	public void setZygznx(String zygznx);

	/**
	 * Returns the sjhm of this expert.
	 *
	 * @return the sjhm of this expert
	 */
	@AutoEscape
	public String getSjhm();

	/**
	 * Sets the sjhm of this expert.
	 *
	 * @param sjhm the sjhm of this expert
	 */
	public void setSjhm(String sjhm);

	/**
	 * Returns the lxdh of this expert.
	 *
	 * @return the lxdh of this expert
	 */
	@AutoEscape
	public String getLxdh();

	/**
	 * Sets the lxdh of this expert.
	 *
	 * @param lxdh the lxdh of this expert
	 */
	public void setLxdh(String lxdh);

	/**
	 * Returns the cz of this expert.
	 *
	 * @return the cz of this expert
	 */
	@AutoEscape
	public String getCz();

	/**
	 * Sets the cz of this expert.
	 *
	 * @param cz the cz of this expert
	 */
	public void setCz(String cz);

	/**
	 * Returns the sqbz of this expert.
	 *
	 * @return the sqbz of this expert
	 */
	public int getSqbz();

	/**
	 * Sets the sqbz of this expert.
	 *
	 * @param sqbz the sqbz of this expert
	 */
	public void setSqbz(int sqbz);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.justonetech.expert.model.Expert expert);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.justonetech.expert.model.Expert> toCacheModel();

	@Override
	public com.justonetech.expert.model.Expert toEscapedModel();

	@Override
	public com.justonetech.expert.model.Expert toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}